version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "main"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:17"
      timezone: "America/New_York"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "dependencies-actions"
    groups:
      minor-and-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
    commit-message:
      prefix: "build(actions)"

  - package-ecosystem: "pip"
    directory: "/docs"
    target-branch: "main"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "04:29"
      timezone: "America/New_York"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "dependencies-docs"
    groups:
      minor-and-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
    commit-message:
      prefix: "build(docs)"

  - package-ecosystem: "swift"
    directory: "/"
    target-branch: "main"
    schedule:
      interval: "weekly"
      day: "wednesday"
      time: "04:41"
      timezone: "America/New_York"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "dependencies-swift"
    groups:
      minor-and-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
    commit-message:
      prefix: "build(swift)"
