import Foundation
import Testing
@testable import NotesKit

/// Corpus differential for `firstVisibleHtmlLine` against apple-notes-mcp 2.6.12.
///
/// WHY THIS EXISTS. NOTES-M6 originally shipped 52 hand-selected golden rows. Three reviewers
/// independently found ICU-vs-JS divergences that all 52 rows passed straight through, and the
/// critic's diagnosis was exact: each hazard class had been identified, documented in a comment,
/// fixed at the site where it was noticed, and NOT swept across its sibling sites in the same
/// function. Curated rows test the site you were thinking about. A generated corpus tests the
/// ones you were not — it is what turned up all three defects.
///
/// The rows below are EMITTED MECHANICALLY by running the oracle's own `firstVisibleHtmlLine`
/// (transcribed verbatim from `build/index.js:41841-41866`) over a generated corpus under node,
/// so a transcription slip cannot define the expectations. `nil` means the oracle's
/// `.find(Boolean)` returned `undefined`, i.e. nothing renders and the caller keeps the current
/// title.
///
/// The generator's alphabet deliberately REACHES the shapes that discriminate — a negative result
/// is only as strong as the generator's reach, which is the lesson this suite was built from.
/// The reach controls below assert that, so the corpus cannot silently stop testing a class.
@Suite("firstVisibleHtmlLine corpus differential (oracle 2.6.12)")
struct FirstVisibleLineCorpusTests {

    /// (html, oracle result or nil)
    static let corpus: [(String, String?)] = [
        ("<script\u{212a}>body</script>tail", "tail"),
        ("<style\u{17f}>body</style>tail", "tail"),
        ("A<script\u{212a}>body</script>B", "AB"),
        ("A<style\u{17f}>body</style>B", "AB"),
        ("<\u{17f}cript>alert(1)</\u{17f}cript>Visible", "alert(1)Visible"),
        ("<script>x</\u{17f}cript>After", nil),
        ("First<br\u{feff}>Second", "First"),
        ("First<br\u{85}>Second", "FirstSecond"),
        ("<script>\u{85}", nil),
        ("<script>hidden\u{85}", nil),
        ("<script>hidden\n", nil),
        ("<script>hidden\u{2028}", nil),
        ("<div>a</div><div>b</div>", "a"),
        ("<scr<script>X</script>ipt>SECRET</script>", nil),
        ("", nil),
        ("   ", nil),
        ("<div></div>", nil),
        ("<p>\u{85}<script\u{212a}>", "\u{85}"),
        ("&nbsp;</\u{17f}cript><br>\u{feff}<p><script\u{212a}><h6>", nil),
        ("&amp;<div>\u{feff}\u{d}<br></script></style>", "&"),
        ("\u{a0}\n<BR>", nil),
        ("\n\u{212a}.</h1><script", "\u{212a}."),
        ("</style>\u{c}<h6>1 </li>", "1"),
        ("\u{feff}style&#x48;\u{2028}", "styleH"),
        (">\n</script><br \u{feff}/>&amp;\u{2028}<SCRIPT>1", ">"),
        ("</div>\u{a0}<h6>1<script\u{212a}>\u{a0}<script<br></style>style", "1"),
        ("</b>\u{d}\u{85}</\u{17f}cript>&nbsp;\u{2028}", "\u{85}"),
        ("&#1F;<h6>aipt", "\u{1}F;aipt"),
        ("&amp;lt;<b>1\u{2028}-\u{c}<BR>\u{85}1\u{2028}", "&lt;1"),
        ("<style></div><BR>", nil),
        ("SCRIPTastyle\u{2028}&#1F;<BR></SCRIPT></SCRIPT>-", "SCRIPTastyle"),
        ("\u{a0}</script>&#xD800;style><style&#xD800;<br\u{feff}></SCRIPT><br \u{feff}/>", "&#xD800;style>"),
        ("&#x48;&amp;lt;<br\u{85}></div><br \u{feff}/>", "H&lt;"),
        ("&gt;Title</h6>&amp;</li><style>", ">Title"),
        ("&amp;lt;\u{2028}</script>\u{feff}", "&lt;"),
        ("ipt<br><h1><h1><br>", "ipt"),
        ("&#xD800;", "&#xD800;"),
        ("<br\u{85}>", nil),
        ("<scriptb<script>le...\u{c}</\u{17f}cript> scr", "<scriptb"),
        ("Real<script\u{212a}>Title<br\u{85}>Body\u{212a}<script>script\u{212a}", "Real"),
        ("<h1></div>scr<BR>&amp;lt;&amp;<style", "scr"),
        ("<h6><scriptle\"</h1><b>&amp;lt;", "&lt;"),
        ("</p>\u{b}", nil),
        ("&gt;\u{feff}<div></h1><SCRIPT></li>&#1F;</li>&lt;\u{feff}", ">"),
        ("\u{c}Title>.\u{b}\n\u{c}", "Title>."),
        ("scrStYlE</\u{17f}cript>style<\u{17f}cript>b</li></h6>\u{212a}a<style<b>", "scrStYlEstyleb"),
        ("<\u{17f}cript>\t&lt;style\u{feff}", "<style"),
        ("<br\u{feff}><script&amp;lt;<b></\u{17f}cript>", nil),
        ("<SCRIPT<style>\u{2029}", nil),
        ("</\u{17f}cript>1\u{b}<br/>&amp;lt;", "1"),
        ("</p><</SCRIPT> \u{2029}SCRIPT</\u{17f}cript>sty<\u{17f}cript>Title&amp;lt;<b>", "SCRIPTstyTitle&lt;"),
        ("<li>scriptSCRIPT<h6>>\u{c}&nbsp;</script>", "scriptSCRIPT>"),
        ("1", "1"),
        ("\u{212a}sty<BR><b></li>&amp;SCRIPT", "\u{212a}sty"),
        ("&#xD800;<style\u{17f}>\n", "&#xD800;"),
        ("sty=", "sty="),
        ("\"\u{d}Real</style><script<b>x</SCRIPT>><", "\""),
        ("</\u{17f}cript>\t\u{2029}\"&#1F;</p>", "\"\u{1}F;"),
        ("&lt;<style\u{17f}>", "<"),
        ("<br />\n\u{a0}<\u{17f}cript>\na<SCRIPT></h1>", "a"),
        ("\u{a0}<br></b>&gt;<br />\u{2029}", ">"),
        ("&#1F;", "\u{1}F;"),
        ("<\u{17f}cript><<b><style<b>&#72;sty</SCRIPT><<BR>\"<\u{17f}cript>", nil),
        ("<br />StYlEBody", "StYlEBody"),
        ("</style><br \u{feff}/>", nil),
        ("<\u{17f}cript></SCRIPT><style</script>", nil),
        ("\u{a0}<div><<scriptSCRIPTsty><h1>", nil),
        ("ipt.a", "ipt.a"),
        ("\u{2029}<br\u{85}><h6>&#x48;\u{a0}</SCRIPT>&nbsp\u{feff}</h1>", "H"),
        ("&gt;b\u{2029}<BR>&amp;&#x48;", ">b"),
        ("/&gt;<p><br/>\u{c}<li><style\u{17f}>scr<b>\t<p>le", "/>"),
        ("&nbsp<script\u{212a}>&nbspscript\"ipt\u{212a}", nil),
        ("&lt;&nbsp&#72;\u{b}\u{b}", "<&nbspH"),
        ("<style&amp;</h6>&#72;", nil),
        ("scr\tBody<<<script>&#xD800;", "scr Body<<"),
        ("&lt;&amp;lt;<h1>\"=/x", "<&lt;\"=/x"),
        ("&amp;lt;<br\u{85}><br\u{85}><script\u{212a}>&amp;\u{b}Body</p>><</p>&amp;lt;", "&lt;"),
        (" ", nil),
        ("x&amp;lt;</\u{17f}cript></script></h1>=<br\u{feff}></li>Body<script<style", "x&lt;"),
        ("StYlE<h1><\u{17f}cript>aBody</script><br \u{feff}/><br/></h1>b\u{2029}</div>", "StYlEaBody"),
        ("b\t&#x48;<style\u{17f}><\u{17f}cript>\u{b}astyle ", "b H"),
        ("<h1><p><h6><b>", nil),
        ("<br><br\u{feff}><li>&gt;</li>\u{2029}=a", ">"),
        ("&nbsp<SCRIPT>&amp;&#xD800;.script</\u{17f}cript>\u{feff}<h1><h1>", nil),
        ("<p></p>&amp;lt;\u{2029}", "&lt;"),
        ("script&nbsp;<SCRIPT><script", "script"),
        ("</style>", nil),
        ("le&#x48;<script\u{212a}><br\u{85}>-Title&nbsp<h1></style>StYlEStYlE", "leH"),
        ("<script></div>\tsty<div><style<br\u{85}>Title", nil),
        (" <script\u{212a}><style><p><br\u{feff}><script", nil),
        ("\u{d}<br/><h6><br/>StYlE\u{212a}</b><BR>&lt;scr\u{a0}scr", "StYlE\u{212a}"),
        ("a</p>&#1F;Titlescr/&lt;<br />", "a"),
        ("styReal </div>\u{212a}<scriptBody", "styReal"),
        ("leSCRIPT&gt;&amp;lt;&nbsp</\u{17f}cript>1Body\"Real", "leSCRIPT>&lt;&nbsp1Body\"Real"),
        ("\u{85}", "\u{85}"),
        ("</p> \u{2028}</h1>a\u{2029}<script<h6><SCRIPT>", "a"),
        ("&gt;styleRealReal\t<br><b>ipt", ">styleRealReal"),
        ("1<script\u{212a}><SCRIPT>\u{2028}<BR></SCRIPT>1", "11"),
        ("<p></SCRIPT>Title.=\u{2029}</b><style<script></SCRIPT>stystyle", "Title.="),
        ("\u{b}scrscra<script\"\u{c}ipt<\u{17f}cript></p><br \u{feff}/>", "scrscra"),
        ("ipt", "ipt"),
        ("<\u{17f}cript><br>\u{17f}b&#x48;StYlE", "\u{17f}bHStYlE"),
        ("le<br\u{85}>SCRIPTReal</h6><", "leSCRIPTReal"),
        ("<BR>\n\u{feff}<.script\u{a0}<br/><div><\u{17f}cript>", nil),
        ("\u{17f}Real", "\u{17f}Real"),
        ("&amp;lt;</div>\u{212a}ipt<script", "&lt;"),
        ("&nbsp;&#xD800;<div>styleStYlEiptSCRIPT\u{2029}StYlE&amp;<br>", "&#xD800;styleStYlEiptSCRIPT"),
        ("=</SCRIPT><style>&nbsp;sty<br />Title<h1>&#xD800;<style\u{17f}>\u{d}/", "="),
        ("<p>\"<h6><SCRIPT>\u{2029}", "\""),
        ("\taipt&gt;&amp;&nbsp;\u{212a}<a<script\u{212a}>\u{212a}", "aipt>& \u{212a}<a"),
        ("</h6></h1>.<br\u{85}><SCRIPT>&lt;<b>-<li>\u{2028}", "."),
        ("</style>&amp;", "&"),
        ("\u{212a}</\u{17f}cript>&#1F;\u{b}</SCRIPT>\u{2029}</script></SCRIPT>=<br>1le", "\u{212a}\u{1}F;"),
        ("></style>style", ">style"),
        ("<BR></b>\u{b}-</script>&nbsp;&lt;<h6>", "- <"),
        ("<b>scr</\u{17f}cript></li><style<br/><br /></b><br />&lt;", "scr"),
        ("</SCRIPT><br/><div>. <div>", "."),
        ("b<br\u{85}>&gt;&#xD800;Body</h6><script\u{212a}></div>&gt;\u{c}<br>Title", "b>&#xD800;Body"),
        ("<BR>\u{b}<\u{17f}cript>\u{feff}scr\u{2029}&nbsp;&#xD800;</li><h1><script\u{212a}>", "scr"),
        ("\u{c}\u{17f}&#xD800;<br\u{feff}>&amp;lt;Real<br></SCRIPT><script>style</b>", "\u{17f}&#xD800;"),
        ("b", "b"),
        ("1SCRIPT<&#1F;<br/>\n", "1SCRIPT<\u{1}F;"),
        ("&#xD800;<style\u{17f}><br />&#x48;<br>StYlE.</SCRIPT><script>script", "&#xD800;"),
        ("\u{d}</b>-<br \u{feff}/>&#1F;</p>\u{d}\u{2028}\nSCRIPT<b>&gt;", "-"),
        ("<li><style>&amp;scr</SCRIPT>a&nbsp;>Body\u{17f}-style", nil),
        ("<br><h1>\u{a0}<br\u{85}>", nil),
        ("sty</style>\u{17f}<p><b>&#xD800;&nbsp&nbsp\u{2028}<script", "sty\u{17f}&#xD800;"),
        (".<br/>\u{a0}\u{212a}<br\u{85}>", "."),
        ("<style\u{17f}>-&amp;>&#xD800;<br\u{85}>Title\u{b}<style>&#x48;\u{a0}1", nil),
        ("&amp;StYlE-scr</h6></b>=<BR></div>", "&StYlE-scr"),
        ("&nbsp;<style\u{17f}>\n&nbsp", nil),
        ("\u{c}le<script\u{212a}>a</SCRIPT>", "le"),
        ("\"\u{212a}&#1F;</p></h6>=script&nbspBody<li><\u{17f}cript>", "\"\u{212a}\u{1}F;"),
        ("\u{2028}&amp;", "&"),
        (">&nbsp", ">"),
        ("</h6><p>&#x48;<br \u{feff}/></h6>\u{b}ipt1</li>", "H"),
        ("<h6><h6><br /><br\u{feff}>", nil),
        ("style", "style"),
        ("/sty<script>", "/sty"),
        ("x<br \u{feff}/>&nbsple\u{b}1script<BR>", "x"),
        ("</style><br/>script", "script"),
        ("Title</li><<li>\t-style<br>", "Title"),
        ("Real&#xD800;&#xD800;  le<style<br>", "Real&#xD800;&#xD800; le"),
        ("\"stylea<=\u{a0}Realscr&nbsp;</div>", "\"stylea<= Realscr"),
        ("&nbsp;==Real", "==Real"),
        ("\n\u{a0}&amp;\u{c}Body<style><style\u{17f}><b>1 ", "& Body"),
        ("</p><br>", nil),
        ("<SCRIPT>sty", nil),
        ("<style>\u{c}\u{2029}<br>&nbsp<script></\u{17f}cript>\u{c}1Real<style\u{17f}><br \u{feff}/>", nil),
        ("<br /><br />", nil),
        ("\u{17f}</\u{17f}cript>&#x48;<script</b><br \u{feff}/><BR>&#1F;", "\u{17f}H"),
        ("<SCRIPT>&#x48;</\u{17f}cript>\u{b}<b>&#72;>>le\u{2028}<script\u{212a}>", nil),
        ("\u{c}", nil),
        ("<li>-<scriptBody<script<\u{17f}\n", "-<scriptBody<script<\u{17f}"),
        ("<br\u{85}>&#x48;<div>scr\u{212a}<br />", "Hscr\u{212a}"),
        ("<div>StYlEscript", "StYlEscript"),
        ("\u{17f}<style>ipt<<li>\u{2029}</script>", "\u{17f}"),
        ("\u{d}<style-Title<\u{212a}</SCRIPT>-</h1><br\u{85}>script", nil),
        ("..<br /><style\u{17f}>le\n", ".."),
        ("&lt;<b><scriptBody<\u{17f}cript>", "<"),
        ("\t", nil),
        ("&nbsp", nil),
        ("iptscr<\u{17f}cript><br\u{85}>-\u{2029}-</b>&#1F;</b>&#1F;ipt", "iptscr-"),
        ("&#1F;&nbsp;<h1><h1>style&#xD800;<br\u{85}>\n<li>", "\u{1}F; style&#xD800;"),
        ("<br \u{feff}/>scrx&nbsp1</script>\u{a0}a=\u{d}", "scrx&nbsp1 a="),
        ("<script>", nil),
        (">&amp;\u{212a}", ">&\u{212a}"),
        ("style\u{c}.<script>&amp;&#72;&amp;Body\u{c}<br />\u{2029}SCRIPT", "style ."),
        ("<h1>\u{85}", "\u{85}"),
        ("<SCRIPT>\u{feff}</b></div>b<br \u{feff}/>\ta<p><SCRIPT><script>ipt", nil),
        ("\"b<b>\u{2028}", "\"b"),
        ("a\u{d}\u{2029}\u{2029}=\u{a0} ", "a"),
        ("\u{feff}<BR>", nil),
        ("<br\u{85}>\u{212a}<script><\u{17f}cript>.scriptRealBody<br /></SCRIPT>\u{c}", "\u{212a}"),
        ("<p><.&#1F;<br/></style>\u{d}</style>.", "."),
        ("<style>&lt;\u{2029}<li></li></script>&#xD800;<style\u{17f}>\u{212a}SCRIPT</li>Title", nil),
        ("&gt;</div>aStYlE\u{17f}&amp;</script>a<br>&#72;", ">"),
        ("b<div>", "b"),
        ("SCRIPT</script>Body<script<style", "SCRIPTBody<script<style"),
        ("<BR>&#x48;\u{17f}&gt;&amp;<br \u{feff}/></SCRIPT>&#72;<li><br></\u{17f}cript>", "H\u{17f}>&"),
        ("<br/>&lt;<br \u{feff}/>\u{212a}<style-\u{c}", "<"),
        ("<\u{17f}cript><script\u{212a}>1&gt;&#1F;\u{a0}\u{d}&nbsp&gt;", nil),
        ("SCRIPT</style><br/>/</SCRIPT><h6>", "SCRIPT"),
        ("<p></p>SCRIPT&#72;<div>&gt;Titlea\t</li>", "SCRIPTH>Titlea"),
        ("-", "-"),
        ("<&#1F;&#72;</style>\u{212a}<br\u{85}>\u{85}</div>\">scr\u{85}", "\u{212a}\u{85}"),
        ("StYlE\u{212a}<p>&#72;\u{212a}", "StYlE\u{212a}H\u{212a}"),
        ("1<br\u{feff}>", "1"),
        ("1&gt;", "1>"),
        ("<script<li>", nil),
        ("<br\u{feff}>\u{2029}aBody</SCRIPT><div><h6></style>1</h1>Real&#x48;", "aBody1"),
        ("Title</\u{17f}cript>", "Title"),
        ("&#xD800;\"\u{17f}</h1>\u{17f}&nbsp&#1F;<BR>\u{17f}&nbsp\u{c}\u{c}", "&#xD800;\"\u{17f}"),
        ("scr\u{d}<h6></script><br>\u{17f}", "scr"),
        ("&#72;script<br/><SCRIPT><style<style\u{17f}>Titlescrstyle", "Hscript"),
        ("script\u{17f}\u{85}&#1F;<style\u{17f}>.<", "script\u{17f}\u{85}\u{1}F;"),
        ("<h6>script<style><br>&nbsp\u{c}<br\u{feff}><style\u{17f}>&amp;lt;", "script"),
        ("RealReal</h6></li><SCRIPT>sty", "RealReal"),
        (">", ">"),
        ("&#x48;</p>&#72;</b></p><br\u{feff}></style>\u{17f}", "H"),
        ("Title&#1F;ble&nbsp;ipt=/<BR>-&nbsp;", "Title\u{1}F;ble ipt=/"),
        ("</p>", nil),
        ("<li></script>sty\t", "sty"),
        ("<br/>", nil),
        ("<script\u{212a}><br\u{85}>1=-\u{feff}aStYlE&#xD800;<h1>", nil),
        ("<br /><br />\u{85}\u{d}<stylescript&#72;", "\u{85}"),
        ("<p><li>", nil),
        ("</style>></h1><style></\u{17f}cript>Body", ">"),
        ("\u{212a}x", "\u{212a}x"),
        ("a\u{c}.=&amp;lt;", "a .=&lt;"),
        ("a-&#xD800;</script>Real><br />", "a-&#xD800;Real>"),
        ("\u{85}StYlE</div>&#1F;</b>Body&lt;<style", "\u{85}StYlE"),
        ("&#72;b<</style>\t<br>\u{2028}<br /><br\u{85}>ipt=<BR>", "Hb"),
        ("</SCRIPT>-&amp;<div><style\u{17f}>StYlE <SCRIPT><h1>-", "-&"),
        ("<style<br\u{85}>", nil),
        ("le&amp;<style>&#xD800;<SCRIPT><script", "le&"),
        ("Real </li>styleTitle&#xD800;StYlE<", "Real"),
        ("<style>&amp;lt;<h1>></script><BR>SCRIPT", nil),
        ("b", "b"),
        ("<h6>Body\u{a0}\"<b><style\u{17f}>sty<p>&#72;Body", "Body \""),
        ("x", "x"),
        ("b&#xD800;\u{feff}a", "b&#xD800; a"),
        ("bscr<br/>Body<h6>1\t</SCRIPT><br \u{feff}/>", "bscr"),
        ("sty=\u{2029}&amp;lt;</\u{17f}cript>StYlEle\u{212a}", "sty="),
        ("</div><style>", nil),
        ("\"</style></SCRIPT><div>", "\""),
        ("\u{b}", nil),
        ("</h6>a<Body</h6><SCRIPT><br><\u{17f}cript>\n</style><br\u{85}>script", "a<Body"),
        ("\"\u{feff}scriptb1</h1><script&nbsp<SCRIPT><br>\u{b}>", "\" scriptb1"),
        ("<br\u{feff}>\u{85}</li>", "\u{85}"),
        ("&#xD800;<br />", "&#xD800;"),
        ("\u{85}Real\u{2028}<script\u{212a}>\u{17f}<div>", "\u{85}Real"),
        ("&lt;\u{85}SCRIPT <script>\u{17f}", "<\u{85}SCRIPT"),
        ("/<p><styleBody<h6><h6><li>&#72;</script>", "/H"),
        ("<li>style</\u{17f}cript><style>\u{a0}SCRIPT", "style"),
        (".<br><style></h6></script>&amp;lt;<script><style>\u{feff}ipt", "."),
        ("&amp;<b>", "&"),
        ("Bodyle", "Bodyle"),
        (">le\t\n ", ">le"),
        ("<h1></script>&amp;lt;le</b></p>\"<br/><br/><SCRIPT>", "&lt;le"),
        ("<p><br>\u{2029}</p><h6><BR>&#72;&amp;&#1F;sty", "H&\u{1}F;sty"),
        ("<br\u{85}>b<style<p>style\u{17f}StYlE<li>&#72;", "b"),
        ("&gt;<br>.", ">"),
        ("<br/>\u{17f}<script>=<script\u{212a}>\u{a0}&gt;<\u{17f}cript></p>>", "\u{17f}"),
        ("<\u{17f}cript><\u{17f}cript>", nil),
        ("</SCRIPT>", nil),
        ("<h6>", nil),
        ("<br><h6>style-</\u{17f}cript>", "style-"),
        ("Title\nSCRIPT<\u{17f}cript><script>StYlE&#1F;Real<h1>\u{b}", "Title"),
        ("/<div>\u{2028}", "/"),
        ("<\u{17f}cript><br\u{feff}>\"<style\u{17f}>", "\""),
        ("<style>-<script\u{212a}><br />\n<br><p>b&amp;", nil),
        ("/\u{a0}<h1>b<br />Real<br \u{feff}/><br />\n<\u{17f}cript>", "/ b"),
        ("script</\u{17f}cript><SCRIPT></b><p></b><style\u{85}<p>SCRIPT", "script"),
        ("<script\u{212a}></script>script\u{17f}<br\u{feff}><style\u{212a}<br\u{feff}></li><script></\u{17f}cript>\u{d}", "script\u{17f}"),
        ("<stylex&amp;</script>Real&#1F;", "Real\u{1}F;"),
        ("&amp;1<style.", "&1<style."),
        ("<br\u{feff}><BR><br\u{85}>&gt;=", ">="),
        ("\t<li><SCRIPT></h1>sty</h6>b</h6><li>/\u{a0}\u{d}", nil),
        ("\u{85}&amp;\"1", "\u{85}&\"1"),
        ("<SCRIPT>&#72;\u{2028}", nil),
        ("&#x48;", "H"),
        ("&amp;&nbsp</SCRIPT>\n&#72;<style\u{212a}</\u{17f}cript>x<script\u{212a}>x", "&"),
        ("</b><h1>&#xD800;<p><br\u{feff}>", "&#xD800;"),
        ("</p>&#72;\u{17f}\"xscriptReal>Real", "H\u{17f}\"xscriptReal>Real"),
        ("TitleTitle&gt;<br\u{feff}><\u{17f}cript>&#1F;\u{d}le</b>", "TitleTitle>"),
        ("&gt;<br /><style<style></script></div>b\u{feff}bTitle</p>", ">"),
        ("<style&gt;script<script></b>Body<b>&#72;", nil),
        ("&nbsp<script><styleStYlE\u{2029}<\u{17f}cript>", nil),
        ("\u{d}<h6>le<li>scr\u{c}", "lescr"),
        ("\"<script\u{212a}> &#72;x&#x48; &#72;-</b>", "\""),
        ("a<style><style>\t<h6>&#x48;.<\u{17f}cript>style ", "a"),
        ("SCRIPTstyle<style\u{17f}>", "SCRIPTstyle"),
        ("<h1></p>", nil),
        ("&gt;\t<br>&#x48;</div></li>Real", ">"),
        ("StYlE>&amp;lt;&#xD800;ipt<br>SCRIPT\u{d} <h6>", "StYlE>&lt;&#xD800;ipt"),
        ("<br \u{feff}/><div>\u{b}</p></b><br />/</b><li>=", "/="),
        ("&#xD800;&amp;lt;<li>\t&amp;\t", "&#xD800;&lt; &"),
        ("</h1></li></li><br><br/>x</h1>", "x"),
        ("</h6></li></script><li></style>style", "style"),
        ("\u{85}&#xD800;<style>\u{2028}<\u{17f}cript>&lt;\u{feff}</style><h1>", "\u{85}&#xD800;"),
        ("stylesty</h6>Real/script<br /></style>&amp;", "stylesty"),
        ("<style\u{17f}></b><script\u{212a}>&#xD800;\u{b}</style>", nil),
        ("</div>\"SCRIPT&#72; <b><br>&#72;1<\u{17f}cript></SCRIPT>", "\"SCRIPTH"),
        ("style&amp;Body", "style&Body"),
        (" Real<p>\u{d}\n", "Real"),
        ("&lt;<h6></h6>", "<"),
        ("<br\u{85}>", nil),
        ("<script\u{212a}><script\u{212a}></li></h1><script\u{212a}><br \u{feff}/><script<\u{17f}cript>\"&nbsp<br />", nil),
        ("<style>", nil),
        ("<br/>SCRIPT&lt;<b></li></script>", "SCRIPT<"),
        ("\u{2028}<br />\u{d}<p></div>", nil),
        ("ipt<h1>&amp;lt;\u{17f}scr<br />", "ipt&lt;\u{17f}scr"),
        ("style.StYlE=<br\u{85}><\t&#x48;<scriptipt\u{2029}", "style.StYlE=< H<scriptipt"),
        ("Body\u{feff}</p>-</\u{17f}cript>StYlE", "Body"),
        ("<br/><script\u{212a}><script>\"\u{d}<\u{17f}cript>", nil),
        ("<script\u{212a}><li><script<br/>&lt;&amp;lt;\u{212a}", nil),
        ("</b>style<script\u{212a}>&amp;<br \u{feff}/>\u{2028}", "style"),
        ("<br><div><style>\u{212a}\u{85}</p>", nil),
        ("&#x48;</\u{17f}cript><script\u{212a}><script>\u{17f}</SCRIPT></li>", "H"),
        ("</h1><script>&#x48;", nil),
        ("<script\u{212a}>script&#72;</div><br\u{feff}>le<style\u{17f}>", nil),
        (".</\u{17f}cript><style&#1F;<style</b>", "."),
        ("</\u{17f}cript>&lt;StYlE<li><br\u{feff}>SCRIPT", "<StYlE"),
        ("x</script></div></li>&#xD800;", "x"),
        ("<\u{17f}cript>&lt;le", "<le"),
        ("&amp;<br>&nbsp;Body\u{17f}style", "&"),
        ("\u{212a}\u{212a}&lt;<br\u{feff}>", "\u{212a}\u{212a}<"),
        ("<SCRIPT>&lt;/\u{c}\u{c}><style\u{17f}>/&amp;lt;", nil),
        ("</\u{17f}cript><h6></h6>ipt<style&#xD800;<SCRIPT>&amp;", "ipt"),
        ("</li></div><br\u{85}></SCRIPT>\u{17f}script", "\u{17f}script"),
        ("<style</SCRIPT>\u{2028}script\u{feff}&gt;&lt;</h6>-</li>", nil),
        ("<style>\u{a0}SCRIPTBody=</style>stylescript&#72;<br/>le\"", "stylescriptH"),
        ("<br /></script></SCRIPT>SCRIPTBody<script\u{212a}>StYlEstyle</SCRIPT><b>\u{b}", "SCRIPTBody"),
        ("<br />&gt;&nbsp;</style>.Body", "> .Body"),
        (" </div><style></\u{17f}cript><script\u{212a}>\u{85}<SCRIPT>><&#x48;&#xD800;", nil),
        ("\u{212a}\u{b}ipt<br\u{85}>styleBody <script</li>ipt</b>&nbsp", "\u{212a} iptstyleBody"),
        ("</style>\u{212a}<script\u{212a}>iptscr<<script\u{212a}></p></SCRIPT>ipt-", "\u{212a}ipt-"),
        ("<SCRIPT>\u{212a}iptipt\u{85}</li></script> \u{2029}&gt;<SCRIPT>", ">"),
        ("</b><style\u{17f}>\nipt<BR></script>&amp; ", nil),
        ("&nbsp<br\u{feff}>&#72;<p><br/><script\u{212a}>", "H"),
        ("x<br><style&lt;&#72;<br>&nbsp;", "x"),
        ("\u{a0}\u{a0}&nbsp</SCRIPT>\u{b}<h1> </h6><br\u{feff}>\u{85}", "\u{85}"),
        ("<h6>/=styipt<style", "/=styipt<style"),
        ("<script>le</SCRIPT>b<br />", "b"),
        ("<script\u{212a}>\u{85}<h1><br\u{feff}><li>&#1F;", nil),
        (".<BR></b></style><SCRIPT<br/>.a\u{feff}<\u{17f}cript>style", "."),
        ("&gt;\u{d}</p>\u{212a}", ">"),
        ("&nbsp</SCRIPT>", nil),
        ("&#1F;&#x48;</h6>=<h1>Title\u{2028}\"\u{85}", "\u{1}F;H"),
        ("</p>", nil),
        ("<br />\n1", "1"),
        ("\u{b}</h1>/", "/"),
        ("<style\u{17f}></div>", nil),
        ("<br><SCRIPT>\u{2029}<br /></h6>", nil),
        ("\u{c}<li><br \u{feff}/><scripta.</h6>&gt;", "<scripta."),
        ("<br \u{feff}/><b>\t</SCRIPT>", nil),
        ("</SCRIPT>x<\u{17f}cript>\u{2029}&#x48;</h6><SCRIPT>aa<style\u{17f}>", "x"),
        ("</li><style>Bodyle", nil),
        ("<p>x<script<h1><br\u{feff}>scr<p>Body</style>\u{a0}", "x"),
        ("<style", "<style"),
        ("scriptStYlE", "scriptStYlE"),
        ("a</SCRIPT> \u{212a}&#x48;x<br/></li></script>", "a \u{212a}Hx"),
        ("\u{d}", nil),
        ("<h6>Titlescr<script&amp;lt;", "Titlescr<script&lt;"),
        ("</style>", nil),
        ("<p></b> </style>\nsty", "sty"),
        ("<script\u{212a}>-\u{b} ipt>\n/</SCRIPT><br\u{feff}><script\u{212a}>", nil),
        ("<BR><SCRIPT>&amp;lt;", nil),
        ("&#72;</b>scr<style>\n\u{a0}ipt", "Hscr"),
        ("<h1></b>xBodylex", "xBodylex"),
        ("<br\u{feff}>", nil),
        ("<style\u{17f}>-le<script\u{212a}>", nil),
        ("\t\u{2029}&amp;", "&"),
        ("<script&#xD800;<b><h1>\u{17f}TitleBody\t<br\u{feff}>", nil),
        ("Body&gt;<style>&nbsp&#xD800;&lt;<br\u{feff}></h6>scr<script>\n<h1>", "Body>"),
        ("style<h6>b", "styleb"),
        ("&#xD800;stylescr<script\u{85}<p>=", "&#xD800;stylescr"),
        ("\u{c}\nBody</\u{17f}cript></h1>\u{212a}></script>\u{a0}\"", "Body"),
        ("&nbsple\u{212a}.1</script> <br />style", "&nbsple\u{212a}.1"),
        ("1<br>SCRIPT<p><br\u{feff}>sty\"<br />&#72;\u{2028}<br \u{feff}/></style>", "1"),
        ("&#72;.\u{2028}</h1></h6><BR><br\u{85}>", "H."),
        ("<script\u{212a}><script>/\"Body<\u{17f}cript><script<h1>1</\u{17f}cript><br/></style>", nil),
        ("Body", "Body"),
        ("</h1>Realle</li>&gt;</p><style\u{17f}>style", "Realle"),
        ("<li>&#1F;\u{85}", "\u{1}F;\u{85}"),
        ("\u{2029}</SCRIPT>Real</li><h6><div>\u{d}<h1><script>", "Real"),
        ("</\u{17f}cript><SCRIPT><br\u{85}>&#72;1\u{d}&lt;</script>", nil),
        ("\u{2028}=-", "=-"),
        ("<script>\n<br\u{85}>scr\u{feff}<script\u{212a}><br \u{feff}/><h6><b><style", nil),
        ("StYlE<b>\u{a0}\u{a0}\t/a<br\u{feff}>&#72;", "StYlE /a"),
        ("x.=&gt;<br />&lt;\u{17f}StYlE&nbsp", "x.=>"),
        ("<div><br/>\u{2028}Title\u{c}>&nbsp;&#1F;", "Title > \u{1}F;"),
        ("</p><h1>SCRIPT&gt;</\u{17f}cript>&#72;scr\u{c}<br \u{feff}/><\u{17f}cript>le", "SCRIPT>Hscr"),
        ("<br />", nil),
        ("\u{212a}\u{a0}<br/><SCRIPT>TitleBodyBody></style>/\u{feff}", "\u{212a}"),
        ("\"></SCRIPT>&lt;/\u{feff}</div>x", "\"></"),
        ("\tb", "b"),
        ("<b><styleSCRIPT&nbsp;\u{212a}script\u{b}<h1>/\u{17f}", "/\u{17f}"),
        ("&amp;lt; xscript", "&lt; xscript"),
        ("<li><h1>", nil),
        ("<li>></b>le\u{c}\u{2028}>", ">le"),
        ("\u{2029}/1\u{17f}&#72;\n<SCRIPT><br\u{feff}>x<div>\t", "/1\u{17f}H"),
        (" &nbsp;<p>&lt;\u{d}\u{c}<script</SCRIPT>x", "<"),
        ("<br\u{85}>x\u{212a}\u{17f}</div><li>", "x\u{212a}\u{17f}"),
        ("SCRIPT<<br><style</script>x/</script><b>", "SCRIPT<"),
        ("</p><script></div></p>&lt;<br \u{feff}/><b></p>script", nil),
        ("\tReal\t<&amp;\u{c}=", "Real <& ="),
        ("&#xD800;\"xscr sty/&gt;", "&#xD800;\"xscr sty/>"),
        ("\u{17f}Body \u{a0}RealStYlEsty", "\u{17f}Body RealStYlEsty"),
        ("&nbsp;</\u{17f}cript><br\u{feff}>ipt&lt;&amp;<br/></style>le", "ipt<&"),
        ("</b><script>&nbsp;b\u{c}/<div></script>\u{feff}</SCRIPT>", nil),
        ("<h6>Real</script><style</script>\u{17f}</li>-<\u{17f}cript></script>", "Real"),
        ("\u{a0}\n</h6>script<script&nbsp<h1><style></li> </\u{17f}cript>", "script"),
        ("x", "x"),
        ("<br>&#x48;\u{c}</b>&nbsp;</h1>\n-</style><h1>\u{212a}", "H"),
        ("a</div>", "a"),
        ("sty<br\u{feff}>b.\u{feff}<style>styTitleTitle", "sty"),
        ("\t<br \u{feff}/></p>&gt;</style></h1></SCRIPT>\u{17f}<SCRIPT>", ">"),
        ("<script>", nil),
        ("&#x48;<style<BR>/<style\u{17f}><b><\u{17f}cript>script", "H"),
        ("</\u{17f}cript>\"\u{2028}</b>x<br \u{feff}/>", "\""),
        ("<<style</li>", "<"),
        ("Title<\u{17f}cript><br\u{feff}><style\u{17f}>a", "Title"),
        ("&amp;lt;</div><h1>\u{2028}Real\u{85}&#72;</p>\t&nbspx\u{c}", "&lt;"),
        ("<\u{17f}cript><b>\u{2028} &#72;a=", "Ha="),
        ("&#x48;<h6></li>&#xD800;</div>ipt</p><script\u{a0}<scriptTitle", "H"),
        ("<div>xx<br\u{feff}><br\u{85}><br\u{feff}>\"</script>\tReal</SCRIPT>", "xx"),
        ("&gt;bStYlE<br\u{feff}>\u{2029}<BR>", ">bStYlE"),
        ("\u{2029}<br\u{feff}> SCRIPT", "SCRIPT"),
        ("\u{b}&nbsp;</h1>&nbsp;</div>sty1&lt;", "sty1<"),
        ("\u{c}&#xD800;b\u{212a}\u{85}\u{b}", "&#xD800;b\u{212a}\u{85}"),
        ("&amp;&nbsp<\u{17f}cript><br \u{feff}/>>\u{b}<p>", "&"),
        ("<script\u{212a}><\u{17f}cript>\u{b}Bodyscript", nil),
        ("&nbsp</div>&#72;\u{2029}scr\u{feff}&amp;lt;<br><&nbsp;\u{d}", "H"),
        ("\u{2028}&gt;&lt;1\u{c}&amp;lt;<BR>", "><1 &lt;"),
        ("<style><p>\n<style>Title><li>b\"\u{b}", nil),
        ("<li>&#xD800;/", "&#xD800;/"),
        ("&#xD800;\u{85}<script\u{212a}>\u{a0}\u{d}/style\u{c}leTitle", "&#xD800;\u{85}"),
        ("<br />ipt</li>&#x48;\n<br>", "ipt"),
        ("le", "le"),
        ("&#x48;=leb\"<style>\n<br></SCRIPT>sty\u{feff}\u{b}", "H=leb\""),
        ("StYlE.<br/><script></style><script&#x48;b\u{feff}<br></h1>", "StYlE."),
        ("<BR>\t</h1>b&gt;le&amp;<br\u{85}>", "b>le&"),
        ("\u{a0}le</b><br />\u{b}&#1F;&#xD800;&nbsp;leSCRIPT\"", "le"),
        ("ab\"", "ab\""),
        ("</b><SCRIPT><\u{17f}cript>\u{85}</\u{17f}cript></\u{17f}cript><br />", nil),
        ("</h6></SCRIPT>&#72;<b>\"1", "H\"1"),
        ("&amp;lt;a</div>scr&nbsp;</h1>", "&lt;a"),
        ("\"<h1>&#x48;", "\"H"),
        ("StYlE\tReal<h1>", "StYlE Real"),
        ("<SCRIPT>b", nil),
        ("Title/xTitle1\t&nbsp;</\u{17f}cript>sty", "Title/xTitle1 sty"),
        (".\u{2029}\u{212a}script&lt;\nscript<br \u{feff}/>&amp;lt;sty<script\u{212a}>script", "."),
        ("<br\u{feff}></style></h6><script\u{212a}><br /><script>script</li><style>", nil),
        ("x<h1>\u{2029}\u{a0}<script>\u{a0}<script\u{212a}></script>", "x"),
        ("sty-&lt;<br>=&gt;Body", "sty-<"),
        (">\u{17f}</p>&amp;lt;", ">\u{17f}"),
        ("/</h6></script>&nbsp-\u{2029}", "/"),
        ("</style>\u{2028}1<br />\n\u{2028}", "1"),
        (">\t", ">"),
        ("<b>StYlE</SCRIPT>", "StYlE"),
        (" \u{a0}</div>StYlE", "StYlE"),
        ("\u{85}-\u{212a}<b>", "\u{85}-\u{212a}"),
        (" <style>&gt;<h6>", nil),
        ("</style>\u{d}</SCRIPT>-<style\u{17f}>/</SCRIPT>-\u{2029}iptle", "-"),
        ("<div>=StYlE</div><script\u{212a}></div></style>le<script>&#1F;", "=StYlE"),
        ("<BR><</h1>.&#72;\u{b}", "<"),
        ("x<br/><h1><h1>", "x"),
        ("<script\u{212a}>", nil),
        (".RealRealTitleSCRIPT&amp;lt;&amp;&amp;lt;ipt</script><h6>", ".RealRealTitleSCRIPT&lt;&&lt;ipt"),
        ("\u{a0}le", "le"),
        ("<br/>&#xD800;</style></style>&#72;\u{d}iptscriptipt</div>", "&#xD800;H"),
        ("Real\u{d}", "Real"),
        ("<br>b</h6>\u{2029}\"", "b"),
        ("<BR>&amp;lt;style\u{2028}", "&lt;style"),
        (">", ">"),
        ("</li>", nil),
        ("&nbsp\u{c}sty<br>&#72;<p>b</\u{17f}cript>", "sty"),
        ("</h1><h1>\u{85}&lt; <br /><h6>&#72;-&gt;Body", "\u{85}<"),
        ("<br/>b</div><style\u{17f}>-Title<style><style>", "b"),
        ("Body&amp;Title&amp;lt;<br/></b>", "Body&Title&lt;"),
        ("SCRIPT<style>", "SCRIPT"),
        (" ", nil),
        ("&#xD800;sty\u{212a}</b>&gt;&gt;<style\u{17f}>\u{2028}<br></b><SCRIPT>1", "&#xD800;sty\u{212a}>>"),
        ("a.&#72;<style</div>/\u{212a}</b>\u{feff}</SCRIPT><h1>&#xD800;", "a.H"),
        ("scr<BR>\u{2028}\u{2029}", "scr"),
        ("TitleStYlE\u{17f}&gt;<br\u{85}>\u{2028}ipt", "TitleStYlE\u{17f}>"),
        ("Real</style>&#x48;", "RealH"),
        ("<SCRIPTTitlestyle&amp;lt;</div>", "<SCRIPTTitlestyle&lt;"),
        ("</div><div>\u{212a}StYlEx/.</script>&gt;&amp;lt;", "\u{212a}StYlEx/.>&lt;"),
        ("<br\u{feff}><b></h6><style\t\u{d}Title<br\u{feff}>style\u{212a}Real", nil),
        ("/\u{c}</script>\u{d}<script\u{212a}><br\u{feff}><script>&#xD800;", "/"),
        ("SCRIPT&#1F;<script\u{212a}>ipt<br\u{feff}>Title&#1F;scrsty<div><style><br\u{85}>", "SCRIPT\u{1}F;"),
        ("</\u{17f}cript><style><h6>\u{b}", nil),
        ("\"", "\""),
        ("</script>&gt;</script><style&amp;lt; SCRIPT1&lt;", "><style&lt; SCRIPT1<"),
        ("-<&amp;lt;SCRIPT", "-<&lt;SCRIPT"),
        ("BodySCRIPT<SCRIPT>&amp;lt;&gt;<script>b>\u{b}-", "BodySCRIPT"),
        ("</h6>-<h6><br\u{85}>\u{2029}<script<style\u{17f}>", "-"),
        ("\u{2029}1<h6></h6><div>&gt;", "1"),
        ("b\n<h6>&#1F;&#xD800;<h1>Real", "b"),
        ("<br /><h6></\u{17f}cript><b>le\u{2028}</style>", "le"),
        ("<h6>\u{2028}<style<SCRIPT>\u{feff}<h6>", nil),
        ("sty<style>sty</h1>ipt", "sty"),
        ("<script>x", nil),
        ("<li>&amp;lt;scr<BR>ipt<script\u{212a}>SCRIPT", "&lt;scr"),
        ("\u{2028}<br \u{feff}/>-/sty\u{17f}", "-/sty\u{17f}"),
        ("<br/><br><br /><br/>b<style>ba\n-", "b"),
        ("b\u{feff}</SCRIPT>\u{c}&#xD800;<b> &amp;lt;<p>a<\u{17f}cript>", "b &#xD800; &lt;a"),
        ("SCRIPT<br/></\u{17f}cript>SCRIPT</b>>&lt;<br/><\u{17f}cript>&#72;&nbsp;\n", "SCRIPT"),
        ("&#72;StYlE&#xD800;<style\u{17f}>&#72;<br \u{feff}/>\u{85}script", "HStYlE&#xD800;"),
        ("\u{17f}<h1>1sty</b><br />\u{2028}</\u{17f}cript>&#1F;le", "\u{17f}1sty"),
        ("sty<p>&nbsp;&amp;&#x48;<b></h1></\u{17f}cript>\n</style>", "sty &H"),
        ("Real<SCRIPT><style><SCRIPT><style\u{17f}>", "Real"),
        ("<br\u{feff}>\u{d}x\u{b}", "x"),
        ("&nbsp", nil),
        ("Title&nbsp;\"&gt;<li></h6>\"", "Title \">"),
        ("\u{2029}<h1>scriptx<scriptlescript\u{b}", "scriptx<scriptlescript"),
        ("b-<li>StYlE&#72;&amp;lt;\u{212a}</\u{17f}cript><h1></b></div>", "b-StYlEH&lt;\u{212a}"),
        ("<br\u{85}>", nil),
        ("\t<style\u{17f}>\u{2028}.<br/>\u{a0}", nil),
        ("<script>>>xscript<br />", nil),
        ("\u{d}\u{d}<p><h1><SCRIPT></\u{17f}cript>&#x48;</\u{17f}cript>></script>Title", "Title"),
        ("SCRIPT\t</p>=<script\u{212a}></h1><br/>/&nbsp;<br\u{feff}>script", "SCRIPT"),
        ("<style>style&#72;", nil),
        ("Body<SCRIPT>x\u{2028}<br \u{feff}/><div><script\u{212a}></SCRIPT>a", "Bodya"),
        ("&gt;\u{b}&amp;lt;", "> &lt;"),
        ("\u{2028}&#x48;&lt;le</SCRIPT><p>\u{a0}</p>Real", "H<le"),
        ("ipt\u{2029}", "ipt"),
        ("<h6>&#1F;</script></b>\u{212a}/<style\u{17f}>\u{85}<Realipt</\u{17f}cript>", "\u{1}F;\u{212a}/"),
        ("<h1>&#1F;<br\u{85}>\u{17f}>&amp;lt;&#72;\n\u{d}</h1>x</style>", "\u{1}F;\u{17f}>&lt;H"),
        ("</div></script></div><b>", nil),
        ("&gt;x\u{85}\u{b}&gt;&#xD800;<h1><script><br/>\u{2028}<style\u{17f}>", ">x\u{85} >&#xD800;"),
        ("le<h1><script&#72;<br />\u{b}<h6>\u{17f}StYlE</div>", "le"),
        ("&amp;lt;Real<BR>&nbsp\u{17f}\u{2028}-\u{2029}>", "&lt;Real"),
        ("</h1><br/>&#72;sty<<style>1</div>", "Hsty<"),
        ("x </li>le<b>\u{85}\u{b}&amp;lt; Real", "x"),
        ("\u{a0}\n&#x48;", "H"),
        ("></div></li><b<", ">"),
        ("<\u{17f}cript>SCRIPT</h1>&#1F;<script\u{212a}></style>\nStYlE\u{2028}<script<br\u{85}>&#72;", "SCRIPT"),
        ("Body\u{c}\u{b}<li>", "Body"),
        ("</style>", nil),
        ("><br\u{85}>Body", ">Body"),
        ("<style>", nil),
        ("<br />", nil),
        ("<br\u{feff}>", nil),
        ("</SCRIPT>\u{212a}<div><style></script>&#xD800;a<style><br>\u{85}\u{feff}<SCRIPT>", "\u{212a}"),
        ("<&gt;a<\u{d}Bodyipt<br/></\u{17f}cript>Body\u{2028}&nbsp;", "Body"),
        ("<style>&amp;<script><style><br/>1</style></h1></\u{17f}cript><p>StYlE", "StYlE"),
        ("\u{a0}<li>\u{d}<br>\u{b}<p>&nbsp;&nbspTitle", "&nbspTitle"),
        ("<style\u{17f}>&amp;lt;=</SCRIPT>x", nil),
        ("\u{c}</div><</li>sty<br />\u{d}SCRIPT ", "<"),
        ("&#xD800;&#xD800;\u{c}", "&#xD800;&#xD800;"),
        ("<div><b>", nil),
        ("&#72;<br\u{85}>Title</li></h6>&#72;", "HTitle"),
        ("\u{a0}<script\u{212a}>", nil),
        ("1<SCRIPT>ipt<h6>b&#x48;", "1"),
        ("<\u{17f}cript>.ipt\u{c}le<\u{17f}cript>\u{d}<b></SCRIPT>sty<br/>\"", ".ipt le"),
        ("<h6>a<p>\u{85}bsty&#x48;&lt;&#72;\"", "a\u{85}bstyH<H\""),
        ("<style&amp;script<h1><br></SCRIPT><br />-&amp;", nil),
        ("sty</script>scriptx&amp;lt;Body\"ipt\u{d}scr", "styscriptx&lt;Body\"ipt"),
        ("\u{212a} /<b><h1><br/>Body\"<\u{17f}cript>&nbspscript&#72;", "\u{212a} /"),
        ("&nbsp<style><br/>&amp;", nil),
        ("</script><b>&gt;\u{2028}</div>style</b>", ">"),
        ("</h6>\u{2029}<script", "<script"),
        ("\u{b}", nil),
        ("</script><li>", nil),
        ("<br>le\n&lt;&#1F;", "le"),
        ("</SCRIPT>&nbsp;-scr</h6>", "-scr"),
        ("\u{c}le</div><br \u{feff}/></li>", "le"),
        ("1<style>b</h1>-&nbsp<BR><div>\u{2029}", "1"),
        ("\u{feff}ipt\u{b}</h1>\t\t", "ipt"),
        ("style", "style"),
        ("b</div>&gt;\n&lt;</SCRIPT>RealStYlEscrab</div>", "b"),
        ("\u{a0}\u{d}\u{c}Title", "Title"),
        ("<div>&#xD800;", "&#xD800;"),
        ("<script\u{212a}>\u{a0}<script\u{212a}>=&#xD800;</style>\u{17f}</h6><BR><h1>", nil),
        ("-<h1>\u{17f} \u{feff}</li>Real/</\u{17f}cript>", "-\u{17f}"),
        ("\u{b}&amp;<stylescript&gt;1StYlE<style\u{17f}><h1></SCRIPT>", "&<stylescript>1StYlE"),
        ("&amp;lt;", "&lt;"),
        ("</style><li>/", "/"),
        ("&#x48;\u{d}\" \u{a0}", "H"),
        ("</style>.\u{2028}<SCRIPT>", "."),
        ("&gt;//", ">//"),
        ("script&nbsp;\"", "script \""),
        ("\u{2029}<a", "<a"),
        ("scr&lt;<div>", "scr<"),
        ("SCRIPT<li><BR>\u{2028}", "SCRIPT"),
        ("</\u{17f}cript><li>\u{212a}Titleb", "\u{212a}Titleb"),
        ("<br />", nil),
        ("&gt;</style>\u{17f}<h6>><BR>", ">\u{17f}>"),
        ("<style\u{17f}>\u{a0}StYlE/", nil),
        ("-<script\u{212a}><BR><p>&#1F;le=Real</\u{17f}cript>\u{b}<br\u{feff}>&#x48;", "-"),
        ("Real</li>1\u{85}<p>", "Real"),
        ("\u{feff}<style<li>&amp;&nbsp\u{d}\"", nil),
        ("&amp;sty-</h6>x<br\u{85}>", "&sty-"),
        ("&amp;</p> Real", "&"),
        ("</div>=\u{212a}\"<style</div>&gt;", "=\u{212a}\""),
        ("&lt;Title&#1F;SCRIPT<li><br\u{feff}>Body=<script><div><style>", "<Title\u{1}F;SCRIPT"),
        (" 1Real&#x48;le\u{85}</script>", "1RealHle\u{85}"),
        ("</p>Body\nle<br/><BR>StYlE\u{b}&amp;</\u{17f}cript>.</p>", "Body"),
        ("</li>sty<SCRIPT>", "sty"),
        ("<style><br\u{85}><p>Body&#72;StYlE leipt</li><br/>", nil),
        ("\u{212a}=<SCRIPT>Body<BR><br\u{feff}>&#72;<br /><br></\u{17f}cript>", "\u{212a}="),
        ("<style\u{17f}>style&#1F;\u{b}<li><style>", nil),
        ("scr\u{b}&gt;1/script&nbsp\u{17f}Title</p>\t<", "scr >1/script \u{17f}Title"),
        ("</li>xa<\u{17f}cript>StYlE\u{2029}\u{c}", "xaStYlE"),
        ("&#x48;\n\u{2028}&lt;\n</li>=<SCRIPT>\u{b}\u{feff}<\u{17f}cript>\n", "H"),
        ("\u{c}&lt;Body<script><style\u{17f}></script></b>", "<Body"),
        ("<style></\u{17f}cript>/\u{17f}", nil),
        ("\t&#1F;", "\u{1}F;"),
        ("<BR>\t&nbsp</h6><br/>", nil),
        ("\u{2028}\u{feff}.<<script\u{212a}><br />&#x48;<p>", ".<"),
        ("&amp;ipt</style><SCRIPT>", "&ipt"),
        ("<br\u{feff}></script><h1><style<br\u{85}>\u{d}&amp;", nil),
        ("\u{feff}</SCRIPT>", nil),
        ("</div>/=&#xD800;&#1F;", "/=&#xD800;\u{1}F;"),
        (" ", nil),
        ("sty", "sty"),
        ("le.stylelescript&#x48;\u{c}", "le.stylelescriptH"),
        ("<\u{17f}cript>", nil),
        ("1sty</h1>\u{d}<br />/\u{17f}&amp;lt;le<p>&amp;lt;&amp;", "1sty"),
        ("</SCRIPT>&#1F;&#xD800;\u{212a}<h6><b><br \u{feff}/>=<style>", "\u{1}F;&#xD800;\u{212a}"),
        ("Body\n</\u{17f}cript><br\u{85}></div>b", "Body"),
        ("\"</SCRIPT>ipt", "\"ipt"),
        ("&#xD800;&#xD800;=", "&#xD800;&#xD800;="),
        ("</\u{17f}cript></h6>\u{d}1<b>sty<SCRIPT><li>", "1sty"),
        ("scr<h6>scr&#72;\u{feff}<br\u{85}>><BR></div>\t", "scrscrH >"),
        ("<<BR>/</style>x", "x"),
        ("<p><br>\u{b}<script\u{212a}><scriptBody</h1><BR>\u{feff}", nil),
        ("&#72;ipt&#1F;<div>\n<SCRIPT>&gt;<SCRIPT>", "Hipt\u{1}F;"),
        ("ipt<h1>", "ipt"),
        ("ipt</li>\u{2028}<br\u{feff}>", "ipt"),
        ("SCRIPT<div><script\u{212a}></SCRIPT>&nbsp;1", "SCRIPT 1"),
        ("ipt<style>&amp;\u{212a}<b>\t", "ipt"),
        ("<script&#xD800;&nbsp;\u{feff}", "<script&#xD800;"),
        ("</SCRIPT>&nbsp;</b>&#1F;a<style\u{17f}>&amp; ", "\u{1}F;a"),
        ("&amp;lt;x</h1><BR></style>a&gt;", "&lt;x"),
        ("\u{feff}\n.<style\u{17f}>\n<SCRIPT>&lt;&amp;lt;script<h1>\u{2028}</div>", "."),
        ("\u{17f}<style\u{17f}>\t<div></p>.<style\u{17f}>SCRIPTipt\u{2028}", "\u{17f}"),
        ("</style>&#xD800;sty>", "&#xD800;sty>"),
        ("&#x48;=\u{d}</p><br \u{feff}/>\t></div>&#xD800;\u{17f}Title\n", "H="),
        ("&#xD800;<h1><br\u{feff}>scr&#72;\u{c}<h6>&amp;lt;--", "&#xD800;"),
        ("<style\u{17f}><SCRIPT><b><br\u{feff}>.</div></p></script>&#x48;le", nil),
        ("<style\u{17f}>", nil),
        ("<li>\u{b}&gt;", ">"),
        ("</\u{17f}cript>scriptsty&amp;lt;</\u{17f}cript>a<br\u{85}>", "scriptsty&lt;a"),
        ("<br \u{feff}/>&#72;", "H"),
        ("</h1>b", "b"),
        ("</\u{17f}cript><style>>a", nil),
        ("style", "style"),
        ("scr</h1>", "scr"),
        ("<stylea<br /></h1>", "<stylea"),
        ("</script>\u{2028}script</\u{17f}cript>script<script\u{212a}>aBody<h6>1\u{b}<p>", "scriptscript"),
        ("&#1F;scr<h1>b\u{212a}", "\u{1}F;scrb\u{212a}"),
        ("script\u{feff}</h6>", "script"),
        ("\u{2029}\"&nbsp;<div>\u{2028}", "\""),
        (" &nbsp;<\u{17f}cript></h6></h6><b>StYlEb<h1>SCRIPT<style", "StYlEbSCRIPT<style"),
        ("Title\t>script\n", "Title >script"),
        ("</div>&lt;&#xD800;<p>\t</li></p>", "<&#xD800;"),
        ("<style\u{17f}>\u{feff}&nbsp;</li><p>&amp;lt;&gt;<script\u{212a}></li>", nil),
        ("Body\u{212a}&#x48;\nBodyReal", "Body\u{212a}H"),
        ("<script></b><br\u{85}> \u{feff}\u{2028}a<style", nil),
        ("Body&amp;\u{212a}\u{c}<br\u{85}></p>", "Body&\u{212a}"),
        ("x<script>\u{85}>\u{212a}\u{d}<\u{17f}cript>", "x"),
        ("<div>-<SCRIPT>-</\u{17f}cript>BodyStYlE", "-"),
        ("\"StYlE", "\"StYlE"),
        ("<script>></div>\u{17f}scr\u{feff}<h6><br\u{feff}><script>/<script<script\u{212a}>", nil),
        ("<script<b><style\u{17f}>style</b><\u{17f}cript> style\u{b}<scriptStYlE", nil),
        ("<div><script\u{212a}>&nbspipt<br />\u{d}</li>", nil),
        ("<script\u{85}</style>&#xD800;< script<\u{d}", nil),
        (".</p><BR>\u{a0}", "."),
        ("\u{d}<b></style>sty<script<br \u{feff}/></h1>&amp;1<script></\u{17f}cript><h1>", "sty"),
        ("\u{feff}<BR>", nil),
        ("&#72;\u{17f}1\t\u{2029}", "H\u{17f}1"),
        (" .\u{2029}<p></b>&#xD800;<script\u{212a}>", "."),
        ("<styleipt1", "<styleipt1"),
        ("Body&amp;lt;</p>Title", "Body&lt;"),
        ("<script\u{212a}></script><\u{17f}cript>SCRIPT", "SCRIPT"),
        ("\u{2029}&nbsp<li><p></\u{17f}cript><\u{17f}cript>", nil),
        ("</p>", nil),
        ("\u{a0}&gt;</style>\u{d}", ">"),
        ("<br />x\u{2029}<p></SCRIPT><br\u{85}><SCRIPT>\u{2029}style<h6></\u{17f}cript>", "x"),
        ("</p>Body", "Body"),
        ("Title<h6><div></h1>&amp;>&amp;lt;\u{d}</p>le&amp;sty", "Title"),
        (".-</h6>&#x48;", ".-"),
        ("&amp;", "&"),
        ("</h6>le&nbsp </\u{17f}cript>b", "le b"),
        ("&gt;x<p><br \u{feff}/><script><BR><script><br></script>", ">x"),
        ("\u{feff}x-&nbsp;>", "x- >"),
        ("<SCRIPT><br\u{feff}><br \u{feff}/>sty", nil),
        ("style.</p><script>&#x48;<SCRIPT><SCRIPT>b", "style."),
        ("<BR>", nil),
        ("&nbsp;<br>=<h6><style>&lt;\u{212a}", "="),
        ("</div>\u{a0}Real<script><style><style\u{17f}>\"\u{85}<BR></style>1", "Real"),
        ("<style\u{17f}>x\u{c}b&lt;\u{feff}\u{c}<SCRIPT></script>script", nil),
        ("\u{feff}<script></SCRIPT>\u{c}\t</b>", nil),
        ("-\u{85}</SCRIPT>&amp;lt;", "-\u{85}&lt;"),
        ("scriptle<li><br><style<div><style<br />style<scriptsty", "scriptle"),
        ("&amp;lt;", "&lt;"),
        ("<script><br/><li>le&#x48;&#72;", nil),
        ("<br\u{85}><style\u{17f}><h1>/Real&#72;b<style\u{17f}>Body", nil),
        ("<SCRIPT>\t=\u{b}Body<script</SCRIPT><br\u{85}>sty\t\u{212a}", "sty \u{212a}"),
        ("sty\"<scriptx<BR>", "sty\"<scriptx"),
        ("\t<scriptsty/\u{c}-le<div>stystyle<SCRIPT>=", "stystyle"),
        ("<h1></b><script", "<script"),
        ("sty<\u{17f}cript></script><b><style\u{17f}>\u{b}<br/>\u{85}<BR>SCRIPT</h6>", "sty"),
        ("<br>&gt;\u{feff}\u{85}\u{2029}", "> \u{85}"),
        ("&#72;<h1>", "H"),
        ("<BR>\t<br>b\n\u{b}&#x48;\"", "b"),
        ("<\u{17f}cript><br \u{feff}/>1Real&#x48;", "1RealH"),
        ("script</div>&#72;<br\u{85}><br>", "script"),
        ("&#72;script<b>Body<br /><SCRIPT></p>Title<h6>", "HscriptBody"),
        ("</script></li>", nil),
        ("<style<script\u{212a}>\u{2029}Real<p>bale<script>", nil),
        ("<br \u{feff}/>&#1F;sty<div><br>\n</SCRIPT>scriptscr", "\u{1}F;sty"),
        ("-\t<br\u{85}>\u{c}a", "- a"),
        ("</h6>.", "."),
        ("&lt;<style\u{17f}>\u{feff}</SCRIPT><br/>Body&#x48;", "<"),
        ("b<stylescript", "b<stylescript"),
        ("<BR>\"<div><br \u{feff}/>.<script\u{212a}>ipt</SCRIPT></h6>&amp;<style\u{17f}>", "\""),
        ("<script\u{212a}><h6>", nil),
        ("<script<", "<script<"),
        ("Real", "Real"),
        ("&#x48;", "H"),
        ("&#x48;&#xD800;<script\u{212a}>>&amp;lt;</li></style></h6>StYlE\u{2029}", "H&#xD800;"),
        ("&nbspSCRIPT", "&nbspSCRIPT"),
        ("SCRIPT<SCRIPT><b>\u{212a}<br\u{85}>&#1F;/\u{85}\n \u{a0}>", "SCRIPT"),
        ("\u{b}<style\u{17f}>styleSCRIPTReal<h6>StYlE&#x48;</script> </style>", nil),
        ("<style\u{17f}>", nil),
        ("<br /><style</h1>style=</li>", nil),
        ("\n\u{b}Title<br\u{feff}>\u{a0}.", "Title"),
        ("\u{b}<script\u{212a}>\u{feff}\u{2028}<b>1le</h6><script\u{212a}><script\u{212a}>\u{85}", nil),
        ("<script><\u{17f}cript> <script\u{212a}>\u{2028}></\u{17f}cript></p>1&amp;", nil),
        ("</style><BR>\u{a0}\u{2028}</h6>&#xD800;&gt;<BR>", "&#xD800;>"),
        ("&amp;<BR>b</p></b></script>StYlE&#1F;<style>/<p>\u{2029}", "&"),
        ("</h6></li></p>StYlE<\u{17f}cript>&#72;<h1>", "StYlEH"),
        ("<\u{feff}</b><script<script\u{212a}>\u{b}\t<script<li>scrReal", nil),
        ("<br \u{feff}/><SCRIPT><script\u{212a}&#72;\u{c}<p>\u{c}<br>", nil),
        ("&lt;\t\u{2029}styTitle", "<"),
        ("sty</p>\n/<br\u{85}>SCRIPT&#xD800;", "sty"),
        ("<style\u{17f}>.Real<br/>&nbsp</script><div>sty<b>\u{b}\u{c}<br \u{feff}/>", nil),
        ("=1</script>&nbsp-<p>a<b>&#x48;\u{17f}\u{a0}<br>", "=1 -aH\u{17f}"),
        ("<style</style>\u{b}lescr<li></div><div>", nil),
        ("<style\u{212a}style\u{c}<b></p>\u{b}", nil),
        ("&nbsp<br/></h1>script&gt;ipt<p>&nbsp;", "script>ipt"),
        ("&#72;<script&#x48;<\u{17f}cript><script</SCRIPT>b.</script>a<SCRIPT>Body", "Hb.a"),
        ("script\u{2029}</h6>", "script"),
        ("</b><br /></p>SCRIPT<h6>-<BR>&lt;", "SCRIPT-"),
        ("-<h6>&#x48;a", "-Ha"),
        ("\u{d}<style><h1>Bodystyle\u{feff}ipt</h6><br \u{feff}/>", nil),
        ("a1<br \u{feff}/><SCRIPT></h1>", "a1"),
        ("\u{a0}<BR><h1>&#72;\tstyle-", "H style-"),
        ("b<BR><p>&amp;lt;\u{feff}<\u{17f}cript>", "b"),
        ("a<style></b>ipt<style> &amp;lt;</script>&lt;SCRIPT", "a"),
        ("<style><BR>&#72;<script><style<li><br \u{feff}/><div><p></h6><BR>", nil),
        ("<br \u{feff}/></li><\u{17f}cript>&amp;lt;SCRIPT\"</li>\u{2028}<style\u{17f}>", "&lt;SCRIPT\""),
        ("le&gt;<h6>style<br/>&#72;&amp;lt;</SCRIPT>\t</SCRIPT>", "le>style"),
        ("&#72;<p>\t</SCRIPT>&gt;SCRIPT </b>\u{b}", "H >SCRIPT"),
        ("style</\u{17f}cript><br\u{85}>=</b>\u{feff}<script\u{212a}>", "style="),
        ("<br/>\u{2029}<style>&amp;lt;<script><br>&nbsp;", nil),
        ("Title.&amp;lt;scriptSCRIPT</h6>sty", "Title.&lt;scriptSCRIPT"),
        ("<h6></h6>&lt;", "<"),
        ("Body<script\u{212a}><br>\"\n1</script>", "Body"),
        ("&amp;lt;.le>\u{2028}\u{a0}&#x48;=", "&lt;.le>"),
        ("&lt;", "<"),
        ("&nbsp;\u{17f}&#1F;", "\u{17f}\u{1}F;"),
        ("&amp;lt;", "&lt;"),
        ("<script\u{212a}><script\u{212a}>\t\u{d}</h6><br\u{85}>\u{feff}\u{212a}scriptReal</\u{17f}cript>", nil),
        ("sty\u{d}<div>\u{85}&amp;\u{feff}<SCRIPT>", "sty"),
        ("<\u{2028}<br\u{feff}>&amp;lt;&nbsp<br />", "<"),
        ("<\u{17f}cript>\u{17f}", "\u{17f}"),
        ("/<BR><script&lt;/\"", "/"),
        ("<br /><br\u{feff}><style>Title&nbsp\t&nbsp</script><script\u{212a}>scriptscript", nil),
        ("\u{85}\u{a0}/<h1><styleBody", "\u{85} /<styleBody"),
        ("<br \u{feff}/>></b>\u{feff}<SCRIPT><h6><style>&nbsp<p>", ">"),
        ("\u{b}", nil),
        ("&amp;\u{2028}StYlE", "&"),
        ("ipt<script\u{212a}><h6>style</style>&amp;lt;", "ipt"),
        ("\u{85}", "\u{85}"),
        ("\u{2028}\u{212a}<br\u{85}></\u{17f}cript>\"<SCRIPT><div><b>\u{b}&nbsp;=", "\u{212a}\""),
        ("<br\u{feff}>style\u{c}</\u{17f}cript></\u{17f}cript>", "style"),
        ("Real&#72;&lt;<br\u{85}><br \u{feff}/>\u{17f}/<br\u{feff}>", "RealH<"),
        ("\u{c}\u{b}<p><\u{17f}cript>sty<br\u{feff}>\t&#xD800;", "sty"),
        ("Real&#72;", "RealH"),
        ("<h1>&nbsp;<h6><=scr\u{2028}", "<=scr"),
        ("styscr<br>&#xD800;<style", "styscr"),
        ("<style\u{17f}></script>x\n <style\u{17f}>", nil),
        ("&nbsp<style\u{17f}>&#xD800;\u{b}<li>b<SCRIPT>\u{a0}&lt;<", nil),
        ("StYlE", "StYlE"),
        ("ipt&#xD800;<SCRIPT>&nbsp</style>\u{2029}<li></div></style></style></b>\u{17f}", "ipt&#xD800;"),
        ("\t/&lt;&#72;<br\u{feff}>", "/<H"),
        ("&#72;lescript", "Hlescript"),
        ("<br\u{85}><script\u{212a}>1<script>", nil),
        ("ascript\u{2029}<style>=\u{feff}", "ascript"),
        ("script<br/>x\u{85}Body&#72;</b>", "script"),
        ("=b<style><p>.&gt;StYlE\u{2029}<br/><style\u{17f}>", "=b"),
        ("\u{c}<script>/1\t<style>>.\u{85}\u{d}<br/>\u{2029}", nil),
        ("<h1>&amp;", "&"),
        ("<style\u{17f}>\n\u{a0}</div><SCRIPT></SCRIPT></li>\"\u{d}<li>\u{b}<\u{17f}cript>", nil),
        ("<div>&nbsp&#1F;&nbsp;<p>&amp;lt;<&gt;\u{2029}&lt;\u{feff}", "\u{1}F; &lt;<>"),
        ("<h6><br\u{feff}>\u{c}&nbsp;&#72;</\u{17f}cript><p></\u{17f}cript>\u{17f}<br/>", "H\u{17f}"),
        ("Real\u{85}/</style> <BR>", "Real\u{85}/"),
        ("b\u{2029}<br />\u{c}script&nbsp;<style>&gt;</SCRIPT><br />\u{b}", "b"),
        ("xx><b>x</div>1script\u{85}\u{d}", "xx>x"),
        ("a<br\u{85}><SCRIPT><br \u{feff}/>", "a"),
        ("<br/>style</style></li><BR><\u{17f}cript></script></div>&nbsp", "style"),
        ("<br\u{85}>.<&amp;lt;", ".<&lt;"),
        ("Real&amp;lt;-", "Real&lt;-"),
        ("\u{feff}<br\u{feff}></p>style", "style"),
        ("<style\u{17f}><SCRIPT>=&#72;Real<script<BR><b>&gt;<div>", nil),
        ("\u{c}StYlE<\u{17f}cript>\u{212a}1<h1>a<script\u{212a}>-<b>", "StYlE\u{212a}1a"),
        ("<p><script\u{212a}>", nil),
        ("\tscript<br\u{feff}></h1>\u{feff}", "script"),
        ("<style>SCRIPT/&#1F;&#x48;<br\u{feff}><<br>\u{a0}Titlesty", nil),
        (">", ">"),
        ("ipt&#xD800;\n\u{2029}<script&#x48;\u{17f}<\u{17f}cript></b><br/>", "ipt&#xD800;"),
        ("&#xD800;\u{feff}</div></h1><br\u{feff}><b><style><SCRIPT></style>styleReal", "&#xD800;"),
        ("<br/>sty<h6></SCRIPT>\"<SCRIPT>", "sty\""),
        ("\"</b><br><li><br/>", "\""),
        ("<h6>&#1F;&lt;le</SCRIPT><br\u{feff}>b", "\u{1}F;<le"),
        ("<BR><script<h1><SCRIPT><h1>\"</h1></\u{feff}", nil),
        ("&nbsp\u{2029}<li><br \u{feff}/></div>leb\u{c}&#1F;</h1>", "leb \u{1}F;"),
        ("<h6><br\u{85}>&amp;<BR>Bodyscript<script<script<br\u{85}> ", "&"),
        ("&#x48;xSCRIPT\u{2029}&amp;", "HxSCRIPT"),
        ("&nbsp<li></b>-sty&nbsp;<br\u{feff}>", "-sty"),
        ("\"", "\""),
        ("=\"<\u{17f}cript>", "=\""),
        ("/</script>", "/"),
        ("b<script\u{212a}>&amp;lt;&amp;lt; \u{85}<\u{17f}cript>", "b"),
        ("<styleb\nb&nbspa<p></h1><h6></h1>\u{85}", "\u{85}"),
        ("</h6>\u{feff}&gt;\u{212a}\u{2029}1</li></SCRIPT>x\u{feff}<br\u{feff}>", ">\u{212a}"),
        ("<h6>\u{c}\n<br />\t", nil),
        ("\n<style>\u{c}\t<\u{17f}cript></div>Title\u{2028}", nil),
        ("<li>", nil),
        ("&amp;lt;", "&lt;"),
        ("</p>&amp;lt;\u{b}", "&lt;"),
        ("\u{c}", nil),
        ("</p>x&nbsp;>aReal</p>script<style\u{17f}><b>", "x >aReal"),
        ("&#1F;/\u{c}</style><<div>", "\u{1}F;/"),
        ("<br\u{feff}></div><br \u{feff}/>\u{2029}<style>", nil),
        ("<br\u{85}>b<\u{17f}cript><p>", "b"),
        ("&nbsp</h6>script</h1><script\u{212a}></p>", "script"),
        (".<style\u{17f}>sty</b>x\u{d}", "."),
        ("&lt;</\u{17f}cript>\u{d}StYlE.<BR>StYlE<br\u{85}></h1></script><script", "<"),
        ("\u{17f}</h6>\u{c}1Title<\u{17f}cript><br><b>\u{85}", "\u{17f}"),
        ("<script\u{212a}>&#x48;&#x48;<br\u{feff}></SCRIPT>&#1F;", "\u{1}F;"),
        ("&amp;lt;<br/><style\u{17f}><br\u{feff}>>", "&lt;"),
        ("<br\u{85}>x&lt;&lt;", "x<<"),
        ("<BR><br\u{feff}>", nil),
        ("<p>\u{17f}<br\u{feff}>\u{c}\u{2029}</style><script></h6><script\u{212a}>", "\u{17f}"),
        ("<SCRIPT>&amp;-", nil),
        ("\"\n\u{c}<b>><SCRIPT>styleTitle&#x48;", "\""),
        ("\t<div>", nil),
        ("style", "style"),
        ("<\u{17f}cript>=<li>&#x48;<</h1>\n=", "=H<"),
        ("<br\u{feff}><styleb<h6><script\u{212a}>scrx", nil),
        ("<br/>&#xD800;<br \u{feff}/><&nbsp;</style><script\u{212a}>", "&#xD800;"),
        ("<script\u{a0}\u{a0}</p>Body</div>scr\u{2029}<br></h6>", nil),
        ("\u{85}&#x48;</\u{17f}cript>-script", "\u{85}H-script"),
        ("<div><BR></h6>\u{feff}<p>/<style>&nbsp;", "/"),
        ("<br\u{85}></li>-", "-"),
        ("</h6>=<\u{17f}cript></h1></b>", "="),
        ("\u{2029}\u{2028}</div>\n<br /><style\u{17f}><script>", nil),
        ("x&nbsp<li></h6>SCRIPT</h1>\u{2029}<BR></p>>\u{2029}", "x"),
        ("&nbsp\u{2028}1", "1"),
        ("&#x48;&#x48;Real</h1>", "HHReal"),
        ("scr<style\n<Real1<\u{17f}cript>bx<h6></style></p>", "scr"),
        ("</SCRIPT>.", "."),
        ("1</li>", "1"),
        ("</h1>&nbsp;</h1><h1>scr<style>StYlEx&gt;&#x48;</SCRIPT>script", "scr"),
        ("</h1>", nil),
        ("</b>Real<style\u{17f}><br />StYlE\u{2029}Real", "Real"),
        ("\u{85}<style></div></h6>script&nbsp&#x48;<style>", "\u{85}"),
        ("<br\u{feff}>>\u{2029}\"", ">"),
        ("&#x48;", "H"),
        ("</style>", nil),
        ("<br><h1>.\u{feff}</script><h1>\"\u{2028}", ". \""),
        ("<script=&#1F;<b>Title", nil),
        ("script\u{feff}", "script"),
        ("&gt;</SCRIPT>1\t&#x48;</p>", ">1 H"),
        ("\u{85}==<li>", "\u{85}=="),
        ("b", "b"),
        ("style</SCRIPT>\u{b}\u{d}", "style"),
        ("\u{b}&amp;<SCRIPT></h1>\t<style><b><b>&lt;x ", "&"),
        ("<li>1\u{a0}.<br>&nbsp;\"", "1 ."),
        ("<br/>&lt;\u{feff}<br><script\u{212a}><style>\u{a0}<div></SCRIPT>\u{2029}</div>", "<"),
        ("&amp;<h1>\"<style>", "&\""),
        ("</b>\"\u{c}scr\u{b}<script\u{212a}></div>", "\" scr"),
        ("</p><b><br/>&#xD800;</li>\u{212a}\u{a0}<li>Title\"<style\u{17f}>StYlE", "&#xD800;"),
        ("<h1>x</b>a<li><script\u{212a}><br /><br\u{85}>\u{17f}scr", "xa"),
        ("<BR>a", "a"),
        ("</div><p>a<br /></SCRIPT>\u{a0}\"", "a"),
        ("&#x48;</SCRIPT>", "H"),
        ("sty<b></style>style</script>SCRIPT\u{212a}", "stystyleSCRIPT\u{212a}"),
        ("a<br\u{85}>", "a"),
        ("<br/><br> \n&#xD800;&lt;\u{d}<br />", "&#xD800;<"),
        ("&nbsp&gt;</SCRIPT>", ">"),
        ("><b>\u{b}</p>\u{17f}StYlE&gt;", ">"),
        ("SCRIPT&amp;lt;<SCRIPT>&lt;le<br><<\u{17f}cript>\u{17f}1", "SCRIPT&lt;"),
        ("\u{85}</b>", "\u{85}"),
        ("<br><br/></h6>le=</p></style>\u{feff}>", "le="),
        ("&#xD800;<h6>Real\"</p></li>\u{d}&nbsp<br \u{feff}/>", "&#xD800;Real\""),
        ("<br \u{feff}/>x</div><b>/style//&#xD800;&lt;scr", "x"),
        ("Title\u{feff}<style</h6></p><li></h6>\n<1", "Title"),
        ("<br\u{85}>Real", "Real"),
        ("<script> <&nbsp <b>\u{b}&nbsp;<SCRIPT>\u{c}\u{d}", nil),
        ("</h1><h1>\u{c}", nil),
        ("\u{17f}", "\u{17f}"),
        ("Title&amp;lt;", "Title&lt;"),
        ("\u{a0}=<h6><li>\u{17f}", "=\u{17f}"),
        (" /", "/"),
        ("<script>\"&lt;=\u{feff}", nil),
        ("<li><&nbsp;.<BR></script><script\u{212a}><h6>", nil),
        ("ipt", "ipt"),
        ("Bodya&gt;\"<p>.\u{212a}\n\u{d}", "Bodya>\".\u{212a}"),
        ("<p>\u{feff}<.</\u{17f}cript>SCRIPT", "SCRIPT"),
        ("<br/></p><style><br\u{feff}><style></div>", nil),
        ("ipt\u{b}", "ipt"),
        ("SCRIPT</b>StYlEa<&#1F;iptStYlE", "SCRIPTStYlEa<\u{1}F;iptStYlE"),
        ("<script\u{212a}></\u{17f}cript>", nil),
        ("a&#1F;<br\u{85}>\u{2029}/le</b>&#xD800;&amp;<b><b>", "a\u{1}F;"),
        ("&gt;scriptle<h6></h6><style\u{17f}>a\n<br\u{feff}><br\u{85}>", ">scriptle"),
        ("</style><br>Bodystyle-\u{2029}<h6><style</li>&amp;lt;</div>", "Bodystyle-"),
        ("1", "1"),
        ("\u{d}<script></style>\u{b}\u{b}\u{feff}<li>&#72;script", nil),
        ("\u{b}<style</script>", nil),
        ("<li>\n</script>\u{feff}\"", "\""),
        ("<style>&#1F;Real\n>&lt;", nil),
        ("\u{2029}\u{b}styleTitle<b>", "styleTitle"),
        ("<br></p> ", nil),
        ("&amp;lt;", "&lt;"),
        ("&amp;1<br\u{feff}><BR><p><br />\u{212a}&#72;\n", "&1"),
        ("<h1><\u{17f}cript><p><h1>&lt;\u{c}StYlE</style></b></style>\u{2028}</b>", "< StYlE"),
        (">&#72;script\u{85}<b><br><SCRIPT><br>", ">Hscript\u{85}"),
        ("<br\u{85}>&nbspStYlE</b>Real<SCRIPT>a", "&nbspStYlEReal"),
        ("&amp;lt;", "&lt;"),
        ("<br\u{feff}>=<br\u{feff}>\n<br /><script>-\u{a0}", "="),
        ("<script\u{b}&#xD800;", "<script &#xD800;"),
        ("<h6>", nil),
        ("&lt;.\u{d}", "<."),
        ("<div><style\u{17f}>le<style\u{17f}>\u{85}\u{a0}<br />&#x48;iptle\u{b}", nil),
        ("<li>", nil),
        ("\u{feff}\u{c}1SCRIPT\"&gt;&amp; <p>&#xD800;1", "1SCRIPT\">& &#xD800;1"),
        ("<li></script>\u{2029}<br\u{85}><\u{17f}cript>\u{c}Body&lt;", "Body<"),
        ("&#1F;", "\u{1}F;"),
        ("&amp;", "&"),
        ("a<h1></div>\t>x.", "a"),
        ("\nb<script>SCRIPT<script\u{212a}><br \u{feff}/>", "b"),
        ("\u{b}&amp;lt;</h1>Body</div>", "&lt;"),
        ("</script><br />\u{c}<SCRIPT>Body&#xD800;<br/></h1>\"<script>x", nil),
        ("</style><p>\u{a0}", nil),
        ("\n.b<script><li>", ".b"),
        ("&#xD800;</p>Title", "&#xD800;"),
        ("<script</SCRIPT>scr><<h6><script\u{212a}>\n<\u{feff}&amp;lt;<SCRIPT>", nil),
        ("&nbsp<p>", nil),
        (">=&#x48;", ">=H"),
        ("le", "le"),
        ("&gt;Title&amp;lt;\u{17f}\u{c}\u{b}</h6>/1<style>Title", ">Title&lt;\u{17f}"),
        ("&#x48;<script>", "H"),
        ("&amp;lt;</h1>\n\u{c}</script>\u{17f}<style", "&lt;"),
        ("<script&#1F;<br>Body1script=1&amp;", nil),
        ("\"1<br\u{85}><\u{17f}cript><h1>SCRIPTStYlE\u{d}<style<style\u{17f}><h1>", "\"1SCRIPTStYlE"),
        ("\u{b}/&#1F;scr<p>&amp;lt; </li><BR></h1><h1>\u{2029}", "/\u{1}F;scr&lt;"),
        ("<br></style>\u{85}&gt;\"<style\u{2028}1", "\u{85}>\"<style"),
        ("&nbsp&#1F;\u{d}</p>\"\u{a0}1&gt;&#72;\t<script<SCRIPT>", "\u{1}F;"),
        ("Real</h6>&nbsp<br>\u{b}>", "Real"),
        ("\nTitle\nscript&#x48;-\u{a0}StYlE<\u{17f}cript>", "Title"),
        ("\u{17f}\u{2028}&nbsp;\u{c}scr\"", "\u{17f}"),
        ("\txle&nbsp &gt;</h1> &nbspipt", "xle >"),
        ("&#xD800;</li>\nstyle<li>b\u{a0}style</div><li>", "&#xD800;"),
        ("</p>\u{212a}", "\u{212a}"),
        ("<style>/-x<b><h1>.</p><\u{17f}cript><div></\u{17f}cript>", nil),
        ("&amp;lt;</\u{17f}cript>", "&lt;"),
        ("style<BR><h1><div></li>sty&amp;\u{b}", "style"),
        ("</SCRIPT>le&#1F;\u{2029}</h1>\u{2028}<\u{17f}cript>style\u{b}<br>", "le\u{1}F;"),
        ("ipt&#xD800;</li><style\u{17f}>StYlE</li>", "ipt&#xD800;"),
        ("</SCRIPT>sty&#1F;</b>&amp;lt;SCRIPT&gt;\u{2028}", "sty\u{1}F;&lt;SCRIPT>"),
        ("&#xD800;b\t</\u{17f}cript>\u{feff}<br/>\u{85}", "&#xD800;b"),
        ("</h6>\u{2028}</SCRIPT>StYlE\u{c}", "StYlE"),
        ("</div>-<p>\u{212a}</li><h6>style\u{d}</div>=</style></style>", "-\u{212a}"),
        ("</\u{17f}cript>\u{2028}Real</h1><li>ipt<h6>Body<div> </p>", "Real"),
        ("</b>style<SCRIPT><stylex", "style"),
        ("<BR><br />\u{2028}<script>\t", nil),
        ("</script><p><br><h6>/&#1F;\u{d}ipt<br\u{feff}>b", "/\u{1}F;"),
        ("1xstylesty<BR><li></div><h1>\u{feff}<h1>", "1xstylesty"),
        ("</b>=Body\u{17f}</b></script>=</SCRIPT>", "=Body\u{17f}="),
        ("</\u{17f}cript>\u{2028}scr<li>", "scr"),
        ("style&lt;StYlE>le\nx<\u{17f}cript>StYlE</h1></p>sty", "style<StYlE>le"),
        ("\u{c}scr\u{c}\u{2029}", "scr"),
        ("x", "x"),
        ("<script\u{212a}>SCRIPT<b>", nil),
        ("Title\u{17f}script<div>Title", "Title\u{17f}scriptTitle"),
        ("ba\u{a0}Title\u{212a}", "ba Title\u{212a}"),
        ("Title", "Title"),
        ("a\u{2028}&gt;<style><BR><\u{17f}cript>&amp;", "a"),
        ("le", "le"),
        ("</SCRIPT>&#xD800;<div><style>/", "&#xD800;"),
        ("\u{d}</script></li><\u{17f}cript><b><\n<script\u{212a}><b></script>", "<"),
        ("StYlE&gt;<br\u{85}>StYlE</script></b>aTitle<<br\u{feff}>>>", "StYlE>StYlEaTitle>"),
        ("style<script>.b=/\u{feff}<style>\u{2028}<p><p>&nbsp;", "style"),
        ("<br>", nil),
        ("sty\u{feff}<script<br\u{feff}>\t\u{b}<b>", "sty"),
        (".\u{85}\n-&nbspa<h1>", ".\u{85}"),
        ("&amp;.=stylescra", "&.=stylescra"),
        ("<br>scr/\u{d}\u{b}", "scr/"),
        ("<li></SCRIPT>\u{d}<br\u{85}></li>scrle<script\u{212a}><br/>", "scrle"),
        ("\t<br\u{85}></h6>&amp;lt;\n<style<h1>scr</li>StYlE\u{d}&gt;", "&lt;"),
        ("</p>1\u{feff}</li><h6><h1>\u{a0}<p>", "1"),
        ("&#x48;\t>\t", "H >"),
        ("<\u{17f}cript>", nil),
        ("xStYlE<br><scriptscript", "xStYlE"),
        ("</script><br\u{85}><scriptstyleBody<li>&#x48;<br \u{feff}/><script><div><script></div>", "H"),
        ("<script\u{212a}> Real<h6>&gt;</script><\u{c}b-", "< b-"),
        ("xsty\u{b}<br\u{feff}></\u{17f}cript><script><&lt;<script\u{212a}>=-SCRIPT", "xsty"),
        ("Real&amp;&#72;", "Real&H"),
        ("<br/>&gt;\u{b}<script\u{212a}></h1><br /><br\u{85}></b>le</SCRIPT>", ">"),
        ("\u{2029}b><li></h6><BR>1\u{17f}<SCRIPT></script>", "b>"),
        ("<script=b<script><script\u{212a}><br /><script>a</h6>&nbsp", nil),
        ("&#x48;", "H"),
        ("</style>\u{85}</style>\u{85}&#72;<BR></h6>", "\u{85}\u{85}H"),
        ("\u{85}<SCRIPT>style\u{85}<br>\u{d}<p>>", "\u{85}"),
        ("<br>scriptSCRIPT", "scriptSCRIPT"),
        ("ipt\n", "ipt"),
        ("<h1>\u{feff}<h1> <scriptx</div></h1>&amp;", "<scriptx"),
        ("<b><style\u{17f}>\u{2028}style", nil),
        ("/\t\t", "/"),
        ("StYlE<style\u{17f}>\t/stylesty<h6>", "StYlE"),
        ("stystyle</div>", "stystyle"),
        ("\u{2028}le=Title</style>", "le=Title"),
        ("<BR>ipt\u{2029}\u{feff}", "ipt"),
        ("\u{a0}</script>\u{a0}<b>&lt;<h6>\"", "<\""),
        ("<script<script\u{2029}<script\u{212a}>&#x48;<br>\u{2028}StYlEReal&#1F;<style\u{17f}>", nil),
        ("<style<style><br \u{feff}/>Body\t\u{b}&#xD800;ba<SCRIPT>", nil),
        ("<style<br>x", nil),
        ("1</h1>&gt;\u{feff}le<br\u{feff}><br\u{feff}><div>\u{212a}</h1></h6>\u{212a}", "1"),
        ("</li>Body.<script\u{212a}><style><br/>&#x48;", "Body."),
        ("&nbsp&gt;&#x48;\u{2029}&#72;le1", ">H"),
        ("<script\u{212a}>", nil),
        ("<div><\u{17f}cript><script\u{212a}>", nil),
        ("&lt;&#1F;</h6>&amp;&#1F;&amp;lt;", "<\u{1}F;"),
        ("1>ipt<br />", "1>ipt"),
        ("\u{212a}</p>\u{d}\n<h6><br\u{feff}>&lt;<br\u{85}>&lt;&amp;lt;<br\u{feff}>\u{c}", "\u{212a}"),
        ("&gt;", ">"),
        ("\u{2029}=", "="),
        ("StYlE<<style<\u{17f}cript>></h6>", "StYlE<"),
        (" </script>sty<br\u{85}>\u{d}</script></li><script>", "sty"),
        ("a<h6></b><SCRIPT>", "a"),
        ("</style>StYlE&amp;-.\u{b}", "StYlE&-."),
        ("\u{d}\"\u{d}<br \u{feff}/>", "\""),
        ("Title<br/>&#1F;&nbsp</div><\u{17f}cript>Body", "Title"),
        ("StYlE<li>\tsty<br /><h6>xBody\u{2029}", "StYlE sty"),
        ("\u{b}<script<style>\u{17f}<div>=&#xD800;", nil),
        ("<br/>&nbsp;<b>style\u{a0}SCRIPTReal<p><BR>>.<style>", "style SCRIPTReal"),
        ("a <br/><style\u{17f}><style\u{17f}><\u{17f}cript></h6>&gt;</li></h6>", "a"),
        ("<br /><br\u{feff}></script><script\u{212a}>-<br\u{85}>sty&#x48;-", nil),
        ("</li>&#x48;\u{b}\u{c}<br\u{feff}></SCRIPT></b>", "H"),
        ("b1", "b1"),
        ("<div>.<\u{17f}cript>\u{17f}&nbsp;<script<style\u{17f}> <BR><style\u{c}", ".\u{17f}"),
        ("\".</style><p>&amp;lt;<br>", "\".&lt;"),
        ("Body<styleReal", "Body<styleReal"),
        ("<SCRIPT>&lt;\u{212a}</script>>\u{2028}\u{a0}", ">"),
        ("=\u{85}&#x48;<BR><script\u{212a}><p>>scrBody", "=\u{85}H"),
        ("\u{85}\t\u{b}", "\u{85}"),
        ("\u{feff}<script\u{212a}>&#1F;", nil),
        ("&gt;></h6>Real&#x48;", ">>"),
        ("<h1><SCRIPT>script</script>", nil),
        ("style<\u{17f}cript></b></h1>&lt;\u{b}", "style"),
        ("&gt;<br>", ">"),
        ("a\u{212a}\u{b}\u{b}\u{212a}><script\u{2029}</script><br\u{85}>", "a\u{212a} \u{212a}>"),
        ("\u{212a}\u{85}<BR>\u{b}</\u{17f}cript><style>&nbsp;Real=", "\u{212a}\u{85}"),
        ("</SCRIPT>&nbsp<style><style><br/><div>&gt;<br />&#x48;&nbsp\t", nil),
        ("\u{212a}&nbsp;style<br\u{feff}><script\u{212a}>Body&lt;<style<BR>&nbsp;", "\u{212a} style"),
        ("&amp;lt;&#xD800;</script>script<li>\u{2028}&lt;Body<script\u{2028}SCRIPT<b>", "&lt;&#xD800;script"),
        ("&lt;&amp;lt;\u{c}<\u{17f}cript><br \u{feff}/>", "<&lt;"),
        ("<h1><script><style>", nil),
        ("\n<<br><style", "<"),
        ("<b>", nil),
        ("\t</h6>\u{212a}<b>", "\u{212a}"),
        ("&gt;<br />Titleipt", ">"),
        ("script<br>\u{212a}\"&#72;</li></SCRIPT>a", "script"),
        ("</div>", nil),
        ("\t&amp;Title<br \u{feff}/>", "&Title"),
        ("/&amp;lt; StYlE&amp;Real&gt;&amp;lt;\u{85} ", "/&lt; StYlE&Real>&lt;\u{85}"),
        ("\nStYlE", "StYlE"),
        ("&lt;RealBodysty&#1F;", "<RealBodysty\u{1}F;"),
        ("<\u{17f}cript>", nil),
        ("Title&nbsp;<script><p>sty</b>", "Title"),
        ("&gt;<h1>scr<SCRIPT><b>Body\u{c}scriptb", ">scr"),
        ("\t</style></h1>scr-&nbsp;<script</h1> b<style&#1F;", "scr-"),
        ("\u{212a}<ipt<br\u{feff}></style>", "\u{212a}"),
        ("</h6>&#x48;\n<SCRIPT></script>", "H"),
        ("<SCRIPT><\u{feff}<style<h1>\u{b}", nil),
        ("&#x48;\u{b}</div>&amp;lt;<&#x48;&nbsp\u{d}", "H"),
        ("\"</script>\u{a0}<BR>&nbsp\u{c}", "\""),
        ("\"-\t</script></style>.x&#72;&#x48;script\u{85}", "\"- .xHHscript\u{85}"),
        ("a\u{2029}</b>/sty", "a"),
        ("<br/>&#1F;Real\u{a0}<br \u{feff}/>&#x48;<script><", "\u{1}F;Real"),
        ("&#x48;", "H"),
        ("<br/><p>&#72;<p>\u{a0}", "H"),
        ("<script<script\u{212a}></p>script\u{feff}/<br>\u{b}", nil),
        ("</p><BR><br /><b>/</style>Title", "/Title"),
        ("<h6><BR><script\u{212a}>\u{2028}<h6>", nil),
        ("=&gt;", "=>"),
        ("<style\u{17f}>", nil),
        ("scr<script\u{212a}>", "scr"),
        ("</h1><\u{17f}cript><BR>aSCRIPT<script\u{212a}>\u{2028}", "aSCRIPT"),
        ("\u{a0}\t\n\n</h1>", nil),
        ("&amp;", "&"),
        ("sty<h1><style>\u{17f}/\n</li>Title\u{b}", "sty"),
        ("<script\u{212a}></h1>1<br/><br /></\u{17f}cript>&amp;lt;<\u{17f}cript>", nil),
        ("b\u{b}", "b"),
        ("SCRIPTstyleSCRIPT<stylescript\u{c}\u{2029}\tscr<h6><li>", "SCRIPTstyleSCRIPT"),
        ("x\u{d}\u{b}", "x"),
        ("<br>-\u{feff}\u{85}\u{c}", "- \u{85}"),
        ("stysty<BR>", "stysty"),
        ("\"\"&nbsp", "\"\""),
        ("Real<style\u{17f}>\u{feff}&lt;<br \u{feff}/>", "Real"),
        ("&amp;lt;", "&lt;"),
        ("-</style></div>&#x48;&#1F;<div>/", "-"),
        ("</h1></style><b><br /><br /></li><script\u{212a}></div>&#72;", nil),
        ("sty\u{17f}", "sty\u{17f}"),
        ("StYlEscr/a&#xD800;>", "StYlEscr/a&#xD800;>"),
        ("\"<SCRIPT></b><h6><script</SCRIPT>.&#x48;<SCRIPT>", "\".H"),
        ("\u{a0}-<h6>sty\u{feff}&#1F;<b></div>", "-sty \u{1}F;"),
        ("&nbsp", nil),
        ("<div>a&#x48;</SCRIPT></p>", "aH"),
        ("\u{17f}</script>\"xTitle<br>.\t<", "\u{17f}\"xTitle"),
        ("</li>ipt&amp;lt;&#x48;", "ipt&lt;H"),
        ("sty <BR>", "sty"),
        ("\u{feff}\u{17f}\u{2029}\"<br\u{85}><\u{17f}cript><br\u{85}>script/<h1></h1>", "\u{17f}"),
        ("styx><script>styscra", "styx>"),
        ("</style>", nil),
        ("StYlEscr<<script&amp; <br\u{feff}><BR>=</\u{17f}cript>\u{d}a", "StYlEscr<"),
        ("</script>", nil),
        ("&gt;styleb</h6></b>", ">styleb"),
        ("<script&amp;lt;script\u{feff}<div>&amp;<b>style</script>", nil),
        ("<style&amp;ipt>", nil),
        ("\u{17f}</h6></style></h1>", "\u{17f}"),
        ("</h6>\u{212a}\u{feff}</h6>script\"\t<h1><br /><\u{17f}cript>", "\u{212a}"),
        ("</div> <br /><style>&#xD800;\u{feff}<h1><style\u{17f}><script>Body>", nil),
        ("&gt;<h6>\u{a0}ipt", "> ipt"),
        ("<h6>&#72;<\u{17f}cript><\u{17f}cript><div>ipt<h1>\u{b}</p>\u{17f}<style", "Hipt"),
        ("a</\u{17f}cript><br/><br\u{85}>\n\u{feff}a&nbsp", "a"),
        ("&nbsp;\u{17f}\u{c}<br>StYlE&nbsp<script\u{212a}><script\u{feff}<div>script", "\u{17f}"),
        ("&#1F; <script\u{212a}></h6>", "\u{1}F;"),
        ("&amp;lt;<p></script>style<br />\u{17f}</b>\t", "&lt;style"),
        ("x\u{17f}&#x48;&lt;<br>", "x\u{17f}H<"),
        ("<SCRIPT>\nBody&#72;\u{c}Body", nil),
        ("<li>&lt;", "<"),
        ("leb<p></b><b></h6></script>-", "leb"),
        ("\n", nil),
        ("--", "--"),
        ("\u{c}scr</h6>/", "scr"),
        ("<style<div>-<b>\u{2028}", nil),
        ("StYlE</script>.StYlE<br /><p><h6><script\u{212a}>\t", "StYlE.StYlE"),
        ("\u{b}</script>", nil),
        ("\nTitle", "Title"),
        ("<SCRIPT>&lt;<script>\u{2028}Real<script><b>", nil),
        ("<p>&nbsp<b>\u{d}-<style\u{17f}>\u{feff}", "-"),
        ("</style>&#72;Body\n\u{85}\n&lt;&amp;lt;<<style</li> ", "HBody"),
        ("\u{2028}</b>=<br \u{feff}/></li>&nbsp<\u{17f}cript>\u{b}a<BR>", "="),
        ("\"&lt;</\u{17f}cript><div>", "\"<"),
        ("<\u{d}</SCRIPT></h1>&#72;\u{212a}1le</SCRIPT>\n<br\u{feff}><style>", "H\u{212a}1le"),
        ("&amp;\u{212a}&lt;<p>&#72;le\u{17f}<\u{b}\u{feff}", "&\u{212a}<Hle\u{17f}<"),
        ("\"b=<br\u{feff}><div>scr\u{a0}&amp;lt;", "\"b="),
        ("Titlea</p><BR><li>\"", "Titlea"),
        ("\u{c}&nbsp;\u{b}&#72;\u{2029}le\u{d}&nbsp", "H"),
        ("</h1><\u{17f}cript>&#x48;<\u{17f}cript>Bodyipt\u{b}le\u{b}", "HBodyipt le"),
        ("<script\nTitle=&gt;<div>", nil),
        ("a1\u{c}</li>\u{2029}\nipt<br/>Body<br />", "a1"),
        ("<\u{17f}cript>SCRIPT&#72;", "SCRIPTH"),
        ("\u{b}", nil),
        ("<SCRIPT><b>&#xD800;<br\u{85}><br\u{85}><script>b<li></li>>\u{17f}<br\u{85}>", nil),
        ("<br\u{85}><br \u{feff}/>\"\n/<script>\u{17f}<BR></SCRIPT></script>", "\""),
        ("&amp;lt;</p></p><style><b>", "&lt;"),
        ("&#72;&#xD800;script&gt;\n", "H&#xD800;script>"),
        ("\u{b}>", ">"),
        ("<br></script><script><br>Body<style><b>le", nil),
        ("<scriptSCRIPT", "<scriptSCRIPT"),
        ("SCRIPT<div>-&#xD800;<h6>.", "SCRIPT-&#xD800;."),
        ("<p></script></h1>", nil),
        ("Title </p>&nbsp;<li>-\u{17f}\n<BR>Real", "Title"),
        ("StYlE&#x48;scriptscript</script>", "StYlEHscriptscript"),
        ("styReal\"", "styReal\""),
        ("\u{c}<br\u{feff}>&#1F;\u{b}\u{c}b<h1><SCRIPT>Body<h6>Title", "\u{1}F; b"),
        ("&nbsp<script<b>/", nil),
        ("&nbsp;<BR><p>&gt;<script\u{212a}><li></div>ipt&lt;\n/", ">"),
        ("<br \u{feff}/>\u{2029}", nil),
        ("</li>style<script</p>\u{17f}<script\u{212a}></style>&lt;", "style"),
        ("\u{feff}<script</h1><br>/&nbsp;sty", nil),
        ("&nbsp;", nil),
        ("</script>\u{17f}</script>.", "\u{17f}."),
        ("Body<script>&amp;lt;</style></SCRIPT>\u{c}<h1>&nbsp=<h6><script\u{212a}>\u{2029}", "Body ="),
        ("<style&nbsp;style<h1>style</li><script\u{212a}>", nil),
        ("</p></script>/<h1>\u{85}</b>=</h1><br />.\u{b}", "/\u{85}="),
        ("<br/><p><br /></div>.&nbsp;<b>ipt", ". ipt"),
        ("<style\u{17f}>\u{17f}></script>iptSCRIPT\t-\u{feff}Real", nil),
        ("\u{2029}1<br />", "1"),
        ("le<li><style-<script&#72;</style>", "le"),
        ("&nbspipt", "&nbspipt"),
        ("<BR><h6><style></p>scrTitle<br>", nil),
        ("le\t</script><b>", "le"),
        ("StYlE", "StYlE"),
        ("a<li>/ x&amp;1", "a/ x&1"),
        ("&lt;\"&#xD800;\"&nbsp;</div>\u{b}<script<BR>1", "<\"&#xD800;\""),
        (" \u{b}&amp;lt;&nbsp<br \u{feff}/><BR><<br/>bx&nbsp</b>", "&lt;"),
        ("<scriptStYlE\"=scr<style</p><script\u{212a}></h6>", "<scriptStYlE\"=scr"),
        ("<\u{17f}cript>.=<h6>&nbsp;", ".="),
        ("<br\u{85}>BodyTitle", "BodyTitle"),
        ("<br>&#1F;<stylestyle<h6>&#72;</style>Body", "\u{1}F;HBody"),
        ("=&amp;lt;", "=&lt;"),
        ("<br /></h6>&lt;<br\u{feff}>&nbsp;", "<"),
        ("<br \u{feff}/>&amp;lt;<scriptle\u{feff}\u{c}\u{b}&amp;<p>&lt;\u{c}a", "&lt;< a"),
        ("<BR>\n<li>-", "-"),
        ("</div>&amp;lt;</\u{17f}cript>", "&lt;"),
        ("<\u{17f}cript><br \u{feff}/><script\u{212a}>>&#xD800;<li>\u{b}", nil),
        ("</h6></\u{17f}cript><br\u{feff}>", nil),
        ("\u{17f}<li>&#xD800;<p><li><li>StYlE\u{a0}<br></SCRIPT>\u{c}", "\u{17f}&#xD800;StYlE"),
        ("&#1F;<li>script<h6>\u{85}<p>&amp;</h1>", "\u{1}F;script\u{85}&"),
        ("<br></li></SCRIPT>\u{b} ", nil),
        ("<br><b>&amp;<style<h6><li><style\u{17f}>\u{d}\u{2028}<style\u{17f}><br>", "&"),
        ("&amp;lt;le\u{85}&amp;lt;<SCRIPT>", "&lt;le\u{85}&lt;"),
        ("sty&#xD800;<h6>\u{c}", "sty&#xD800;"),
        ("</p></h6><br/>scr\u{a0}<b>&#x48;b<div>1", "scr Hb1"),
        (" script</div>&#72;&nbsp;", "script"),
        ("script</h1>&lt;&nbsp", "script"),
        ("sty</p><h1>&#xD800;<script\u{212a}><br/>\u{a0}</style>\u{85}</SCRIPT>/</h1>", "sty"),
        ("scr\u{2028}<b></style>Title</style>\u{2029}</h1></h6>", "scr"),
        ("<br></b></script>\u{17f}</p><b><script</li>", "\u{17f}"),
        ("\u{b}<script\u{212a}>\u{c}", nil),
        ("<\u{17f}cript></\u{17f}cript>=\u{17f}<li><b>", "=\u{17f}"),
        (" <SCRIPT><br>", nil),
        ("Title", "Title"),
        ("\u{85}<style\u{17f}>&amp;lt;Body&nbspSCRIPT<br \u{feff}/>style&lt;<style\u{17f}></div>", "\u{85}"),
        ("-&nbsp&nbsp;", "-"),
        ("<script></p><br\u{85}><br \u{feff}/>11", nil),
        ("\u{85}<p>\"<SCRIPT><br\u{feff}>", "\u{85}\""),
        ("\u{2029}script<br/><b>&#xD800;StYlE<style>iptTitle-&#xD800;&amp;", "script"),
        ("<script\u{212a}>\n<SCRIPT><style\u{17f}>-SCRIPT\u{c}</\u{17f}cript>", nil),
        ("</h1>\u{b}&gt;\u{feff}&amp;lt;<SCRIPT>StYlETitle", "> &lt;"),
        ("sty<style><br/><br \u{feff}/></div><li></SCRIPT>-</SCRIPT><br></SCRIPT>", "sty"),
        ("</div>&#1F;.\"  ", "\u{1}F;.\""),
        ("<BR><SCRIPT>", nil),
        ("scr\n\u{85}<h1><script</h6>&gt;<div>", "scr"),
        ("</b><br \u{feff}/>&nbsp<scriptscriptscript", "<scriptscriptscript"),
        ("leBody\t&#72;<script=<h1>", "leBody H"),
        ("\u{17f}&lt;<style\u{17f}>1<script></li></h1><b><script>\u{85}<le", "\u{17f}<"),
        ("-\u{17f}<br />script<script>scr</p>\u{85}\u{212a}<br\u{feff}>&amp;lt;", "-\u{17f}"),
        ("<style\u{17f}>\u{d}\u{b}iptx&amp;lt;</div>\u{a0}", nil),
        ("<br/>&amp;lt;x</h6>script<style\u{17f}>", "&lt;x"),
        ("<br \u{feff}/>sty\u{2028}", "sty"),
        ("\u{212a}\u{2029}</li>\u{2028} <br\u{85}>", "\u{212a}"),
        ("<div>", nil),
        ("scr", "scr"),
        (" &nbsp&#1F;</SCRIPT></h6></div><\u{17f}cript>-&#x48;<h6>\u{17f}", "\u{1}F;"),
        ("a\"Reala&#x48;<style><b></b>", "a\"RealaH"),
        ("<style&#x48;&#x48;\u{212a}b<style\u{17f}>StYlEx</div>scr", nil),
        ("&amp;lt;&#xD800;</h6>&gt;<br\u{feff}>iptstyle<br\u{85}>=", "&lt;&#xD800;"),
        ("<div>le<style\u{17f}></b><br/><style&lt;</h6>x", "le"),
        (".\u{feff}StYlE\u{c}\u{2028}<br>-", ". StYlE"),
        (".<script\u{212a}>&lt; <SCRIPT>\u{feff}Body\u{2028}\u{feff}", "."),
        ("\u{85}=\u{2029}<br \u{feff}/><style\u{17f}>b<li>b&lt;</li>", "\u{85}="),
        ("-\u{a0}&gt;=<h6>\u{2028}<br><br\u{85}></div>&#x48;\u{b}\u{c}", "- >="),
        ("<br />", nil),
        ("\u{2029}\u{c}\u{a0}", nil),
        ("&amp;<style><br/></SCRIPT><br\u{85}>", "&"),
        ("&gt;</style>styStYlE>b", ">styStYlE>b"),
        ("\u{c}</\u{17f}cript>StYlEstyle.\u{212a}</li><SCRIPT>", "StYlEstyle.\u{212a}"),
        ("</h6>&#xD800;", "&#xD800;"),
        ("</li>\u{17f}RealReal</SCRIPT><script>\u{d}&#xD800;\"<li><SCRIPT>", "\u{17f}RealReal"),
        ("ipt\u{d}/\n", "ipt"),
        ("</li><style\u{17f}>\u{b}</script>Body<div>&#xD800; </p>", nil),
        ("&amp;<SCRIPT>iptle", "&"),
        ("a\u{2028}<style\u{17f}>\u{17f}", "a"),
        ("<br>", nil),
        ("</\u{17f}cript><br/><br\u{85}>&amp;lt;\u{85}&#x48;</p>", "&lt;\u{85}H"),
        ("ipt&gt;<br\u{feff}>Body\u{feff}</SCRIPT></p>", "ipt>"),
        ("Real\t<scriptle&gt;<SCRIPT>Body</p>", "Real <scriptle>"),
        ("Title<p>\u{2029}<script>Title&lt;\n\u{b}scr<li><script<br \u{feff}/>", "Title"),
        ("<br /><h6>1\u{212a}<style<script>&amp;lt;=1", "1\u{212a}"),
        ("<\u{17f}cript><1<h6>\u{a0}/</li>RealBody-&nbsp;", "/"),
        ("<\u{17f}cript><h1>sty\u{a0}\"\t\u{a0}Realstyle<script</p>\u{b}", "sty \" Realstyle"),
        ("\u{212a}<BR>", "\u{212a}"),
        ("<BR><style><br\u{85}></\u{17f}cript>&nbsp;</h6>\u{2029}x<scriptle\u{85}<BR>", nil),
        (".", "."),
        ("1>", "1>"),
        ("-&amp;lt;<br\u{85}>", "-&lt;"),
        ("</b>&#72;&#x48;<style\u{17f}>le<p>\u{85}<script></h1></h6>\u{feff}\u{2029}", "HH"),
        ("&lt;<\u{17f}cript><script \u{2029}", "<<script"),
        ("<br\u{85}></div>&gt;1&amp;\u{17f}\u{2028}x", ">1&\u{17f}"),
        ("</\u{17f}cript>&amp;ipt<br \u{feff}/>&nbspSCRIPT\u{feff}&#72;b<br\u{85}>&#72;&amp;lt;", "&ipt"),
        ("Body<style>Body<li>\u{2029}", "Body"),
        ("</h1>", nil),
        ("Real\u{b}&nbsp\t1<b>Real<script</h6></\u{17f}cript>", "Real 1Real"),
        ("&#xD800;<h6><br/></style>TitleSCRIPT</h6>&nbsp\u{85}</li>=&amp;lt;", "&#xD800;"),
        ("&lt;</li><script>&nbsp/</script><div>sty", "<"),
        ("\t<li>", nil),
        ("<h1>\u{c}&#x48;&amp;lt;\u{feff}\u{17f}/\u{c}</b>", "H&lt; \u{17f}/"),
        ("sty<p><BR>", "sty"),
        ("/&nbsp;<\u{17f}cript><br/>><\u{17f}cript><style>", "/"),
        ("ipt&nbsp;.-", "ipt .-"),
        ("\u{85}<style><div><h1><script\u{212a}>", "\u{85}"),
        ("style\u{2029}", "style"),
        ("<div></style>=\u{212a}<h6>", "=\u{212a}"),
        ("\t-&nbsp;<br \u{feff}/>iptTitle\u{17f}", "-"),
        ("<h1><style</style>-<li>\u{17f}&#72;</\u{17f}cript>le\u{17f}/</p>", nil),
        ("\u{c}<br/>=-&nbsp;", "=-"),
        (">\u{2029}x<BR>&#1F;<b><b></SCRIPT>ipta\u{b}", ">"),
        ("style\n&#1F;&nbsp;</h1></style><style-<script>Body", "style"),
        ("\u{2029}<style&amp;lt;styleTitlele<br\u{85}>", nil),
        ("</h1></script>", nil),
        ("<h1>le<\u{17f}cript>SCRIPT", "leSCRIPT"),
        ("style&amp;lt;<</h6>StYlE\"</SCRIPT>script", "style&lt;script"),
        ("le<br />\u{b}\u{b}</script></\u{17f}cript><br><h1>-", "le"),
        ("x<p>><br/>a<\u{17f}cript>ipt", "x>"),
        ("<style><h1></h1>\u{d}<b></SCRIPT><br/>\tBody<script\u{212a}><b>", nil),
        ("<</h1>&nbsp;", "<"),
        ("</h6><style\u{17f}>scr<br/>ipt<script", nil),
        ("&amp;lt;-Title</\u{17f}cript>", "&lt;-Title"),
        ("\u{c}", nil),
        ("<div><p>&#1F;&nbsp;", "\u{1}F;"),
        ("-<BR>\u{a0}\"sty.", "-"),
        ("</style></b>\u{c}\u{c}\u{212a}>Real<\u{17f}cript>\u{2028}<\u{17f}cript>Title&#72;", "\u{212a}>Real"),
        ("<h1><li>\u{2028}le<p>&#1F;\n<br/><style", "le\u{1}F;"),
        ("\u{b}>\u{a0}", ">"),
        ("&lt;", "<"),
        ("style<b>\u{b}&amp;<br />a\n</style><br \u{feff}/>&lt;", "style &"),
        ("Body<div>\u{b}</h6></b>style", "Body"),
        ("<br/><b></p>sty<br \u{feff}/>&gt;<br\u{85}>&#1F;&nbsp;", "sty"),
        ("</h6>", nil),
        ("x1x", "x1x"),
        ("</h6>\u{b}x<br\u{feff}><b><b>&#x48;", "x"),
        ("<script><script&nbsp;", nil),
        ("\u{17f} <&amp;-", "\u{17f} <&-"),
        ("<br \u{feff}/><SCRIPT></\u{17f}cript><br><br\u{85}>", nil),
        (".", "."),
        ("-</SCRIPT><script\u{212a}><br\u{85}>", "-"),
        ("<p>&gt;", ">"),
        ("<style\u{17f}><br \u{feff}/><script</h6></b>", nil),
        ("<h1><</b><h6>1</\u{17f}cript>\u{85}<p></style>Real", "1\u{85}Real"),
        ("<=&gt;>\u{2029}</p></SCRIPT><h1><br\u{85}>", nil),
        ("\u{a0}<scriptStYlE&gt;\u{2029}<div><h1>", nil),
        ("\u{17f}</b>", "\u{17f}"),
        ("<br\u{85}></div>\u{b}\u{2029}", nil),
        ("<br /><br/>", nil),
        ("Title\u{a0}<style\u{17f}>&amp;lt;", "Title"),
        (" 1</script>x", "1x"),
        (">\tTitleSCRIPT<br\u{feff}>\u{2029}&#x48;iptBody&#1F;<br \u{feff}/><style>", "> TitleSCRIPT"),
        ("<SCRIPT><\u{17f}cript>", nil),
        ("<style>ipt<br \u{feff}/>\n/<li>\u{2029}&lt;</p>x</\u{17f}cript></h1>", nil),
        ("&#xD800;<BR>style", "&#xD800;"),
        ("&#xD800;&#72;<SCRIPT>ipt&amp;lt;scriptscr</p>/\u{17f}", "&#xD800;H"),
        ("script</h6><\u{17f}cript>", "script"),
        (">\u{2029}</SCRIPT></script>StYlE<br\u{feff}>", ">"),
        ("&nbsp;<h1>Bodyipt", "Bodyipt"),
        ("scr</b>&lt;", "scr<"),
        ("<style<div></div>Title", nil),
        ("\u{c}<div>=<div></h1><stylescrle<h6><br\u{feff}></style>", "="),
        ("=</h1>scriptscrle<br\u{85}>&gt;</\u{17f}cript>b\u{a0}</h1>", "="),
        ("&amp;<style> <SCRIPT></p>\n\u{c}", "&"),
        ("</div>style\u{17f}</li>Title<SCRIPT></h1>", "style\u{17f}"),
        ("<style><style\u{17f}><br\u{85}>&nbsp\u{2028} StYlE", nil),
        ("<style></b>&amp;<li><br \u{feff}/></p>&lt;=\u{2028}script</h6>", nil),
        ("SCRIPT", "SCRIPT"),
        ("<h1>.&#72;</SCRIPT><b>&#xD800;", ".H&#xD800;"),
        ("Body<h6>style\u{a0}</div></p>scr&gt;\"</h1><\u{b}", "Bodystyle"),
        ("a\u{17f}</li>\u{b}sty&#x48;<BR></style>", "a\u{17f}"),
        ("<br />stylesty&nbsp;</h6>scr</div><style>", "stylesty"),
        ("</h1><h1>sty\u{17f}scr</h6>\"&lt;a&lt;a", "sty\u{17f}scr"),
        ("<h6>\u{212a}ipt<div></SCRIPT><BR>/scriptStYlE", "\u{212a}ipt"),
        ("</li>\u{feff}", nil),
        ("Body", "Body"),
        ("<BR>\n&#x48;</p>Real</h1>", "H"),
        ("</SCRIPT>&nbspipt<br><h1>scr", "&nbspipt"),
        ("<h6>&gt;&amp;", ">&"),
        ("<b>&lt;<stylex&nbsp; </style>SCRIPTTitle<b>", "<SCRIPTTitle"),
        ("<br>\u{85}sty><script\u{a0}<br\u{feff}>scr</h6>\t<h6>", "\u{85}sty>"),
        ("&gt;&amp;<br\u{85}>>\u{85}<BR><style></SCRIPT>", ">&>\u{85}"),
        ("<style<h1>\u{d}&#xD800;<style>&gt;=<br\u{85}>", nil),
        ("script</h6>&#72;\u{17f}Real\u{2028}", "script"),
        ("x\u{17f}.&#72;\n\u{c}Real</b></p>=\u{b}&amp;lt;", "x\u{17f}.H"),
        ("</SCRIPT>&#1F;/", "\u{1}F;/"),
        ("<style></\u{17f}cript><b>", nil),
        ("\u{2028}</h6> le-<li>Real<</style><br\u{85}><script\u{212a}>", "le-Real"),
        ("ipt\u{c}<p>", "ipt"),
        ("\u{b}</div>\nSCRIPT", "SCRIPT"),
        (">&#1F;&nbsp=\u{85}\u{feff}</p><script>\"", ">\u{1}F; =\u{85}"),
        ("1<style.scr-</SCRIPT> </style>\u{a0}<script", "1 <script"),
        ("\"&amp;\u{d}\u{c}\nscr<\u{212a}<SCRIPT>&lt;", "\"&"),
        ("\u{212a}&#72;<b>b1</b>", "\u{212a}Hb1"),
        ("</\u{17f}cript>script&gt;<br\u{feff}><\u{17f}cript>&amp;", "script>"),
        ("<br \u{feff}/><br\u{feff}>", nil),
        ("ipt&nbsple\u{b}\u{212a}<br /><br\u{feff}>\u{85}\u{85}", "ipt&nbsple \u{212a}"),
        ("\u{c}&amp;\u{85}<br \u{feff}/>Title", "&\u{85}"),
        ("</h6>\u{2029}\"", "\""),
        ("</SCRIPT><style\u{17f}></\u{17f}cript><SCRIPT>\u{feff}ipt\t&#x48;</li></script>&#1F;<br\u{85}>", nil),
        ("StYlE1<p></p><script", "StYlE1"),
        (".\u{a0}\u{212a}", ". \u{212a}"),
        ("<p><style><b>&#x48;<br\u{85}>styleipt&nbsp;<br\u{feff}><h1><br\u{feff}></li>", nil),
        ("&#xD800;\u{212a}=Title\t<SCRIPT>&nbsp", "&#xD800;\u{212a}=Title"),
        ("\u{feff}<style</b>\u{17f} \u{2029}lesty <h6><br />\u{b}", nil),
        (".<\u{d}&amp;&nbsp;le\u{2029}</script></div>\u{b}</h6>&#72;", "."),
        ("<style\u{17f}></script>", nil),
        ("\u{2029}a", "a"),
        ("<br/>\u{a0}</SCRIPT></SCRIPT></script>&#72;StYlE&lt;</script>", "HStYlE<"),
        ("</li>-StYlE=-a<br>\n", "-StYlE=-a"),
        ("\tx", "x"),
        ("<li>&#x48;<br /><\u{17f}cript><p></h6>", "H"),
        ("Real&gt;", "Real>"),
        ("&#1F;&#1F;</script></li>&#1F; ", "\u{1}F;\u{1}F;"),
        ("</h6><b>", nil),
        ("</p>sty&amp;lt;x<style>\u{feff}<p>", "sty&lt;x"),
        ("&#1F;<br \u{feff}/><br \u{feff}/><BR><h6>\u{b}", "\u{1}F;"),
        ("SCRIPT\u{a0}script/", "SCRIPT script/"),
        ("</style>&#1F;<br/>-SCRIPT<script><style\u{17f}>&nbsp;&#xD800;\u{d}b", "\u{1}F;"),
        ("<br><script\t", "<script"),
        ("<BR><script\u{212a}><\u{17f}cript></h1>\u{d}b1RealTitle</b>", nil),
        ("</\u{17f}cript>\u{c}<br /><\u{17f}cript>x", "x"),
        ("&#x48;", "H"),
        ("</style><style><style>", nil),
        ("StYlEscript&amp;<style&amp;&gt;iptBody</SCRIPT><br />Title", "StYlEscript&"),
        ("&lt;\u{2028}\u{2029}1.< \n&#72;\u{d}", "<"),
        ("<style\u{17f}><b>Body&#xD800;stylestylele</h6>", nil),
        ("-", "-"),
        ("</div><h6>\u{2028}<b>", nil),
        ("&#xD800;</h6><BR>\u{a0}<SCRIPT>&#x48;", "&#xD800;"),
        ("&#72;&nbsp<<p><h1></li>Title</h6>sty<SCRIPT>\u{17f}</script>", "H"),
        ("b<p><p>ipt<b>\u{a0}</script><li><style\u{17f}>\u{212a}<script><style\u{17f}>", "bipt"),
        ("\u{212a}\u{c}\u{a0}", "\u{212a}"),
        ("\u{212a}&nbsp;<\u{17f}cript><br>", "\u{212a}"),
        ("style&#x48;</li>b</script>SCRIPT\n\u{2029}\u{212a}</div>&#xD800;", "styleH"),
        ("<script\u{212a}>", nil),
        ("\u{b}\u{2028}&#xD800;", "&#xD800;"),
        ("</style>", nil),
        ("</\u{17f}cript>&nbsp</h6></div>&amp;lt;a&amp;<br \u{feff}/>\u{17f}le", "&lt;a&"),
    ]

    @Test("every generated body matches the oracle")
    func matchesOracle() {
        var checked = 0
        for (html, expected) in Self.corpus {
            let got = NotesText.firstVisibleHtmlLine(html)
            #expect(got == expected,
                    "firstVisibleHtmlLine(\(html.debugDescription)) = \(String(describing: got)), oracle says \(String(describing: expected))")
            checked += 1
        }
        #expect(checked == Self.corpus.count)
        #expect(Self.corpus.count >= 1_400, "control: the corpus must not shrink")
    }

    @Test("no quadratic shape on the post-write path")
    func noQuadraticOnPostWritePath() {
        // ABSOLUTE bounds, deliberately not a ratio. The ratio form measured ~40 ms against
        // ~40 ms and review clocked it failing 10 runs in 60 under load — a quotient of two
        // small timings is noise-dominated, and a flaky perf assertion trains people to re-run
        // until green. Each bound below has >100x headroom while still catching its regression
        // by >10x, because the failure modes are catastrophic rather than marginal.
        //
        // NOTE these regressions are invisible to BOTH correctness suites: reverting either one
        // scores 0/57 golden and 0/1417 corpus, because they change only time, not output. That
        // is the entire reason a timing assertion lives in the logic tier at all.
        func time(_ body: String) -> TimeInterval {
            let started = Date()
            _ = NotesText.firstVisibleHtmlLine(body)
            return Date().timeIntervalSince(started)
        }
        _ = time("<script>warmup</script>")

        // (a) the script/style scanner's bail-out. `<script` repeated with no `>` ANYWHERE is
        // the shape that blew up; bare `<` is not, because it never matches a tag name and so
        // takes the cheap reject path — review caught me benchmarking exactly that wrong shape.
        // 50k repeats (~342 KiB), not the full 1 MiB ARG_MAX payload: reverting the bail-out
        // makes the 1 MiB case take ~8 MINUTES to fail, which is miserable CI feedback for a
        // regression that is already unmistakable at a third the size. 50k separates by >10x
        // and fails in about a minute.
        let unclosedTagName = time(String(repeating: "<script", count: 50_000))
        #expect(unclosedTagName < 5.0,
                "342 KiB of `<script` took \(unclosedTagName)s; pre-bail-out this was ~55 s")

        // (b) the `<br>` whitespace class. Two adjacent unbounded quantifiers around `/?` is
        // polynomial backtracking; the possessive form is flat. Pre-fix this measured 0.28 s at
        // 8 KiB and could exhaust the stack outright at larger sizes.
        let brWhitespaceRun = time("<div>a<br" + String(repeating: " ", count: 64 * 1024) + "x</div>")
        #expect(brWhitespaceRun < 5.0,
                "64 KiB whitespace run after `<br` took \(brWhitespaceRun)s; pre-fix this was minutes")
    }

    /// Reach controls. Each asserts the corpus still contains inputs that discriminate a specific
    /// ICU-vs-JS hazard. Delete the atom that produces one and this fails LOUDLY, rather than the
    /// corpus quietly going green while no longer testing the class.
    @Test("the corpus reaches every hazard class it claims to cover")
    func reachControls() {
        func count(_ pred: (String) -> Bool) -> Int {
            var n = 0
            for (html, _) in Self.corpus where pred(html) { n += 1 }
            return n
        }

        // ICU full case folding maps U+017F onto `s` and U+212A onto `k`, so an ASCII-only
        // `(script|style)` / `[A-Za-z0-9_]` silently widens. Must appear right after a tag name.
        let tagNameTerminator = count { html in
            let lower = html.lowercased()
            for name in ["script", "style"] {
                var search = lower.startIndex
                while let r = lower.range(of: "<" + name, range: search..<lower.endIndex) {
                    let after = r.upperBound
                    if after < html.endIndex {
                        let scalars = String(html[after...]).unicodeScalars
                        if let f = scalars.first, f.value == 0x17F || f.value == 0x212A { return true }
                    }
                    search = r.upperBound
                }
            }
            return false
        }
        #expect(tagNameTerminator > 150, "reach: U+017F/U+212A in the tag-name terminator position (\(tagNameTerminator))")

        // JS `\s` includes U+FEFF and EXCLUDES U+0085; ICU's does the opposite. Must appear
        // inside a `<br …>` for the BREAK_RE class to be exercised.
        let brWhitespace = count { $0.contains("<br\u{feff}") || $0.contains("<br\u{85}") || $0.contains("<br \u{feff}") }
        #expect(brWhitespace > 200, "reach: U+FEFF/U+0085 inside <br> (\(brWhitespace))")

        // ICU `$` matches before a FINAL line terminator; JS `$` without `m` does not.
        let trailingTerminator = count { html in
            guard let last = html.unicodeScalars.last else { return false }
            return [0x0A, 0x0D, 0x85, 0x2028, 0x2029, 0x0B, 0x0C].contains(Int(last.value))
        }
        #expect(trailingTerminator > 100, "reach: trailing line terminator (\(trailingTerminator))")

        // The script/style fixed point is load-bearing only when removing a block SPLICES a new
        // tag out of its neighbours, which needs FRAGMENTS, not whole tokens. The obvious
        // predicate is a trap: `"<script>".contains("scr")` is true, so counting raw substrings
        // scores ~967 while the genuine-fragment rows number far fewer — delete every real splice
        // row and the control would still pass. Strip whole tags FIRST, then look for fragments.
        let spliceFragments = count { html in
            let stripped = html.replacingOccurrences(
                of: "</?(script|style)\\b[^>]*>", with: "", options: [.regularExpression, .caseInsensitive])
            return stripped.contains("scr") || stripped.contains("ipt") || stripped.contains("sty")
        }
        #expect(spliceFragments > 400, "reach: TRUE splice fragments, whole tags removed (\(spliceFragments))")

        let entities = count { $0.contains("&") }
        #expect(entities > 100, "reach: entity decoding (\(entities))")

        // A corpus of only-renders-nothing inputs would pass trivially; assert both outcomes.
        let nilResults = Self.corpus.lazy.filter { $0.1 == nil }.count
        #expect(nilResults > 100, "reach: bodies that render nothing (\(nilResults))")
        #expect(Self.corpus.count - nilResults > 100, "reach: bodies that do render")
    }
}
