import Testing
@testable import NotesKit

/// `get-note-markdown` list rendering against apple-notes-mcp 2.6.12 (NOTES-M2).
///
/// GOLDEN VALUES PRODUCED BY THE ORACLE'S OWN ENGINE, not by hand and not by recording what this
/// port happens to emit. The oracle converts note HTML with **turndown 7.2.4** configured at
/// `build/index.js:41466-41477` as `{headingStyle:"atx", codeBlockStyle:"fenced",
/// bulletListMarker:"-"}` plus a `notesDivs` rule, then `.trim()`. These rows were generated by
/// running that exact configuration under node against turndown@7.2.4 — the version the bundle
/// pins — so they fail if this port and the oracle disagree at all, which is the parity claim.
/// Hand-written expectations would only re-encode whatever the port already does.
///
/// The generator lives in `Tests/NotesKitTests/fixtures/notes-markdown-oracle/` (checked in, with
/// turndown pinned to 7.2.4 exactly). `corpus.mjs` is the single source of the input list, and
/// `GoldenSyncTests` compares the rows below against the generator's committed `goldens.json`, so
/// a hand-edited row fails the suite rather than quietly turning this file into a record of
/// whatever the port already does. See that directory's README.
///
/// WHAT THIS CAUGHT. Before NOTES-M2 the port rendered every `<li>` as `"- "` via
/// `<li\b[^>]*>(.*?)</li>`, which (a) destroyed ordered-list numbering outright, (b) used one
/// trailing space where turndown uses three for bullets and two after `N.`, and (c) CORRUPTED
/// nesting: the non-greedy body stopped at the first `</li>`, so an inner item swallowed its
/// parent's close tag and the outer item lost its marker entirely. It also caught two bugs in the
/// replacement while it was being written — `lastElementChild` semantics (a trailing TEXT node
/// does not displace a nested list) and the fact that turndown indents by `prefix.length`, so a
/// sublist under item `10.` indents five spaces, not four.
struct ListMarkdownParityTests {

    /// Corpus rows the port does NOT match, each pinned with BOTH sides so the gap is a recorded
    /// fact rather than a silent omission.
    ///
    /// I first wrote that EVERY one of these is "a non-list rule leaking into a list item, which is
    /// why they are out of scope for NOTES-M2". Review rejected the universal, and it was right:
    /// that sentence is a category argument doing the work of five separate judgements, and I had
    /// already twice used the same reasoning to defer something I then turned around and fixed (the
    /// recursion depth cap, and the `Number()` decimal-only limit — both had been written up as
    /// deliberate documented divergences before being closed). A claim that clears four items at
    /// once is exactly the shape to distrust. Per row, then:
    ///
    /// - `ol_br_in_item` - turndown's `br` emits a two-space hard break; our per-line trim strips
    ///   trailing spaces. The trim governs ALL non-list text, so fixing it here would either
    ///   special-case lists or change every other surface — genuinely NOTES-L1.
    /// - `ol_p_between`  - a `<p>` between two `<li>`s is blank-line separated by turndown; we emit
    ///   it inline. This one IS list-shaped: it is our `.other` child rendering, not a foreign rule.
    ///   It is deferred because block-separation is the same rule NOTES-L1 must implement anyway,
    ///   NOT because it is out of scope. The numbering it shifts is already correct (`3.  b`).
    /// - `li_img`        - turndown renders `<img>` as `![alt](src)`; this port renders `<img>` as
    ///   markdown nowhere. That is true and checkable, but "it predates NOTES-M2" is a statement
    ///   about blame, not about scope: the gap is now VISIBLE inside a list because this file makes
    ///   list output exact. Deferred as NOTES-L1 because an inline `img` rule belongs with the
    ///   other inline rules, not because this change is innocent of it.
    /// - `li_empty_td`   - an empty `<table>` in an item; turndown keeps a blank line because `td`
    ///   is meaningfulWhenBlank. Table rendering is unimplemented pipeline-wide.
    /// - `blank_runs_between_lists` - review found this one and it was NOT in the corpus, which is
    ///   the more useful half of the finding. The oracle separates two lists across three empty
    ///   `<div><br></div>`s as `1.  a\n\n  \n\n  \n\n  \n\n1.  b` — those `  ` lines are
    ///   two-space hard breaks, so it never emits three consecutive newlines. We trim each line
    ///   (killing the two spaces) and then collapse `\n{3,}` to `\n\n`, giving `1.  a\n\n1.  b`:
    ///   the blank run is gone entirely. SAME root cause as `ol_br_in_item` — the per-line trim —
    ///   which is why the `\n{3,}` collapse cannot simply be deleted: with the trim in place it is
    ///   load-bearing for every other surface. Both close together in NOTES-L1.
    ///
    /// These go RED when the corresponding gap is closed, which is the point: closing NOTES-L1
    /// must not silently leave this file asserting the old behaviour.
    static let divergent: [(name: String, html: String, oracle: String, port: String)] = [
        ("ol_br_in_item", "<ol><li>a<br>b</li></ol>", "1.  a  \n    b", "1.  a\n    b"),
        ("ol_p_between", "<ol><li>a</li><p>mid</p><li>b</li></ol>", "1.  a\n\nmid\n\n3.  b", "1.  a\nmid\n3.  b"),
        ("li_img", "<ol><li><img src=\"x.png\" alt=\"pic\"></li><li>b</li></ol>", "1.  ![pic](x.png)\n2.  b", "1.  \n2.  b"),
        ("li_empty_td", "<ol><li><table><tr><td></td></tr></table></li><li>b</li></ol>", "1.  \n    \n2.  b", "1.  \n2.  b"),
        ("blank_runs_between_lists", "<ol><li>a</li></ol><div><br></div><div><br></div><div><br></div><ol><li>b</li></ol>", "1.  a\n\n  \n\n  \n\n  \n\n1.  b", "1.  a\n\n1.  b"),
    ]

    /// 79 rows the port must match BYTE-FOR-BYTE. Together with the 5 `divergent` rows above, that
    /// is every row in `corpus.mjs` — the reach control asserts the two counts sum to the corpus
    /// size, so a row cannot be quietly dropped from here to make the suite pass.
    static let exact: [(name: String, html: String, markdown: String)] = [
        ("ol_simple", "<ol><li>alpha</li><li>beta</li><li>gamma</li></ol>", "1.  alpha\n2.  beta\n3.  gamma"),
        ("ul_simple", "<ul><li>alpha</li><li>beta</li></ul>", "-   alpha\n-   beta"),
        ("ol_start5", "<ol start=\"5\"><li>five</li><li>six</li></ol>", "5.  five\n6.  six"),
        ("ol_start0", "<ol start=\"0\"><li>zero</li><li>one</li></ol>", "0.  zero\n1.  one"),
        ("ol_startneg", "<ol start=\"-3\"><li>x</li><li>y</li></ol>", "-3.  x\n-2.  y"),
        ("ol_startnan", "<ol start=\"abc\"><li>x</li></ol>", "NaN.  x"),
        ("ol_in_ol", "<ol><li>a<ol><li>a1</li><li>a2</li></ol></li><li>b</li></ol>", "1.  a\n    1.  a1\n    2.  a2\n2.  b"),
        ("ol_in_ul", "<ul><li>a<ol><li>a1</li></ol></li></ul>", "-   a\n    1.  a1"),
        ("ul_in_ul", "<ul><li>one<ul><li>deep</li></ul></li></ul>", "-   one\n    -   deep"),
        ("ol_in_divs", "<div><ol><li>one</li><li>two</li></ol></div>", "1.  one\n2.  two"),
        ("ol_eleven", "<ol><li>i1</li><li>i2</li><li>i3</li><li>i4</li><li>i5</li><li>i6</li><li>i7</li><li>i8</li><li>i9</li><li>i10</li><li>i11</li></ol>", "1.  i1\n2.  i2\n3.  i3\n4.  i4\n5.  i5\n6.  i6\n7.  i7\n8.  i8\n9.  i9\n10.  i10\n11.  i11"),
        ("ol_deep_under10", "<ol><li>i1</li><li>i2</li><li>i3</li><li>i4</li><li>i5</li><li>i6</li><li>i7</li><li>i8</li><li>i9</li><li>ten<ol><li>deep</li></ol></li></ol>", "1.  i1\n2.  i2\n3.  i3\n4.  i4\n5.  i5\n6.  i6\n7.  i7\n8.  i8\n9.  i9\n10.  ten\n     1.  deep"),
        ("ol_start99_nested", "<ol start=\"99\"><li>x<ol><li>deep</li></ol></li></ol>", "99.  x\n     1.  deep"),
        ("ol_empty_item", "<ol><li></li><li>b</li></ol>", "2.  b"),
        ("ul_empty_item", "<ul><li></li><li>b</li></ul>", "-   b"),
        ("ol_ws_between", "<ol>\n  <li>a</li>\n  <li>b</li>\n</ol>", "1.  a\n2.  b"),
        ("heading_then_ol", "<div><h1>Title</h1></div><ol><li>one</li></ol>", "# Title\n\n1.  one"),
        ("ol_inline_bold", "<ol><li><b>bold</b> tail</li></ol>", "1.  **bold** tail"),
        ("ol_link", "<ol><li><a href=\"https://x.test\">link</a></li></ol>", "1.  [link](https://x.test)"),
        ("ol_entities", "<ol><li>a &amp; b &lt; c</li></ol>", "1.  a & b < c"),
        ("ul_three_levels", "<ul><li>a<ul><li>b<ul><li>c</li></ul></li></ul></li></ul>", "-   a\n    -   b\n        -   c"),
        ("ol_two_lists", "<ol><li>a</li></ol><ol><li>b</li></ol>", "1.  a\n\n1.  b"),
        ("ol_after_text", "<div>intro</div><ol><li>a</li></ol>", "intro\n\n1.  a"),
        ("ol_li_div", "<ol><li><div>d</div></li><li>b</li></ol>", "1.  d\n    \n2.  b"),
        ("ol_li_para", "<ol><li><p>para</p></li><li>b</li></ol>", "1.  para\n    \n2.  b"),
        ("ol_attrs_noise", "<ol class=\"x\" start=\"3\" data-y=\"z\"><li>a</li></ol>", "3.  a"),
        ("ol_start_quoted1", "<ol start='7'><li>a</li></ol>", "7.  a"),
        ("ol_start_bare", "<ol start=4><li>a</li></ol>", "4.  a"),
        ("ol_start_empty", "<ol start=\"\"><li>a</li></ol>", "1.  a"),
        ("ol_start_space", "<ol start=\" 5 \"><li>a</li></ol>", "5.  a"),
        ("ol_start_float", "<ol start=\"1.5\"><li>a</li><li>b</li></ol>", "1.5.  a\n2.5.  b"),
        ("ul_mixed_nest_ol", "<ul><li>a<ol><li>n1</li><li>n2</li></ol></li><li>b</li></ul>", "-   a\n    1.  n1\n    2.  n2\n-   b"),
        ("ol_nested_then_text", "<ol><li>a<ol><li>x</li></ol>tail</li></ol>", "1.  a\n    1.  xtail"),
        ("ol_uppercase_tags", "<OL><LI>a</LI><LI>b</LI></OL>", "1.  a\n2.  b"),
        ("ol_multi_blank", "<ol><li></li><li></li><li>c</li></ol>", "3.  c"),
        ("ul_only_blanks", "<ul><li></li></ul>", ""),
        ("ol_text_before_after", "<div>pre</div><ol><li>a</li></ol><div>post</div>", "pre\n\n1.  a\n\npost"),
        ("ol_four_deep", "<ol><li>a<ol><li>b<ol><li>c<ol><li>d</li></ol></li></ol></li></ol></li></ol>", "1.  a\n    1.  b\n        1.  c\n            1.  d"),
        ("ol_li_unclosed", "<ol><li>a<li>b</ol>", "1.  a\n2.  b"),
        ("ol_unclosed_list", "<ol><li>a</li>", "1.  a"),
        ("ol_nbsp_item", "<ol><li>&nbsp;</li><li>b</li></ol>", "2.  b"),
        ("sib_ul_apple", "<ul class=\"Apple-dash-list\"><li>a</li><ul class=\"Apple-dash-list\"><li>b</li></ul><li>c</li></ul>", "-   a\n\n-   b\n\n-   c"),
        ("sib_ol_numbering", "<ol><li>a</li><ol><li>b</li></ol><li>c</li></ol>", "1.  a\n\n1.  b\n\n3.  c"),
        ("sib_two_deep", "<ul><li>a</li><ul><li>b</li><ul><li>c</li></ul></ul><li>d</li></ul>", "-   a\n\n-   b\n\n-   c\n\n-   d"),
        ("sib_first", "<ul><ul><li>b</li></ul><li>c</li></ul>", "-   b\n\n-   c"),
        ("sib_only", "<ul><ul><li>b</li></ul></ul>", "-   b"),
        ("sib_trailing", "<ul><li>a</li><ul><li>b</li></ul></ul>", "-   a\n\n-   b"),
        ("sib_two_sublists", "<ul><li>a</li><ul><li>b</li></ul><ul><li>c</li></ul><li>d</li></ul>", "-   a\n\n-   b\n\n-   c\n\n-   d"),
        ("ol_div_child", "<ol><div>x</div><li>a</li></ol>", "x\n2.  a"),
        ("li_empty_anchor", "<ol><li><a href=\"http://x\"></a></li><li>b</li></ol>", "1.  [](http://x)\n2.  b"),
        ("ol_empty_list", "<ol></ol>", ""),
        ("ul_empty_list", "<ul></ul>", ""),
        ("attr_data_start", "<ol data-start=\"9\"><li>a</li></ol>", "1.  a"),
        ("attr_aria_start", "<ol aria-start=\"3\"><li>a</li></ol>", "1.  a"),
        ("attr_decoy_then_real", "<ol data-start=\"9\" start=\"2\"><li>a</li></ol>", "2.  a"),
        ("attr_start_in_value", "<ol title=\"start=5\"><li>a</li></ol>", "1.  a"),
        ("attr_gt_in_value", "<ol><li title=\"a>b\">x</li><li>y</li></ol>", "1.  x\n2.  y"),
        ("attr_gt_then_start", "<ol title=\"a>b\" start=\"3\"><li>x</li></ol>", "3.  x"),
        ("attr_gt_single_quoted", "<ol title='a>b' start='4'><li>x</li></ol>", "4.  x"),
        ("attr_valueless", "<ol reversed start=\"2\"><li>a</li><li>b</li></ol>", "2.  a\n3.  b"),
        ("start_hex", "<ol start=\"0x10\"><li>a</li></ol>", "16.  a"),
        ("start_exp", "<ol start=\"1e3\"><li>a</li></ol>", "1000.  a"),
        ("start_infinity", "<ol start=\"Infinity\"><li>a</li></ol>", "Infinity.  a"),
        ("start_plus", "<ol start=\"+5\"><li>a</li></ol>", "5.  a"),
        ("start_bin", "<ol start=\"0b11\"><li>a</li></ol>", "3.  a"),
        ("start_oct", "<ol start=\"0o17\"><li>a</li></ol>", "15.  a"),
        ("start_neg_hex", "<ol start=\"-0x10\"><li>a</li></ol>", "NaN.  a"),
        ("start_lower_infinity", "<ol start=\"infinity\"><li>a</li></ol>", "NaN.  a"),
        ("start_trailing_garbage", "<ol start=\"12abc\"><li>a</li></ol>", "NaN.  a"),
        ("start_ws_only", "<ol start=\" \"><li>a</li></ol>", "0.  a"),
        ("start_neg_infinity", "<ol start=\"-Infinity\"><li>a</li></ol>", "-Infinity.  a"),
        ("start_hex_big", "<ol start=\"0xffffffffffffffffffffffffffffffffffffffff\"><li>a</li></ol>", "1.461501637330903e+48.  a"),
        ("start_hex_upper", "<ol start=\"0X1A\"><li>a</li></ol>", "26.  a"),
        ("start_hex_empty", "<ol start=\"0x\"><li>a</li></ol>", "NaN.  a"),
        ("start_hex_baddigit", "<ol start=\"0xg\"><li>a</li></ol>", "NaN.  a"),
        ("start_bin_baddigit", "<ol start=\"0b2\"><li>a</li></ol>", "NaN.  a"),
        ("start_hex_float", "<ol start=\"0x1p3\"><li>a</li></ol>", "NaN.  a"),
        ("start_hex_spaced", "<ol start=\" 0x10 \"><li>a</li></ol>", "16.  a"),
        ("start_underscore", "<ol start=\"1_0\"><li>a</li></ol>", "NaN.  a"),
    ]

    @Test("list rendering is byte-identical to the oracle's turndown")
    func listsMatchOracle() throws {
        for row in Self.exact {
            let got = try NotesText.htmlToMarkdown(row.html)
            #expect(got == row.markdown,
                    "\(row.name): oracle \(row.markdown.debugDescription), port \(got.debugDescription)")
        }
    }

    /// SECURITY (H1). Both recursions in `NotesLists` are mutually reachable, so capping only
    /// one leaves the other exploitable. Before `maxDepth`, 20k nested `<ul><li>` — 160 KB of
    /// input, well under any note-size limit — SIGSEGV'd the process by exhausting the stack.
    /// A crash here is a DoS on `notes get-markdown` / `export-notes` reachable from any note
    /// body, including a synced one the operator never authored.
    ///
    /// The assertion is that it THROWS rather than that it crashes-not: a hang or a segfault
    /// fails the run, so the only way to reach the `#expect` is a bounded, non-fatal refusal.
    ///
    /// This test is why `maxDepth` is 100 and not 500 — see the note on `NotesLists.maxDepth`.
    /// It only catches an over-large cap when run alongside the rest of the suite (worker thread,
    /// small stack); filtered to itself it runs somewhere roomier and passes either way.
    @Test("deeply nested lists are refused, not fatal")
    func depthCapRefusesInsteadOfCrashing() {
        let bomb = String(repeating: "<ul><li>", count: 20_000)
        #expect(throws: NotesLists.DepthExceeded.self) {
            _ = try NotesText.htmlToMarkdown(bomb)
        }
        // The same input must not take the whole export down: `export-notes --format md`
        // degrades per-note via `try?`, which requires the error to be catchable.
        #expect((try? NotesText.htmlToMarkdown(bomb)) == nil)
    }

    @Test("nesting just under the cap still renders")
    func justUnderCapRenders() throws {
        let n = 50   // < NotesLists.maxDepth
        let html = String(repeating: "<ul><li>x", count: n) + String(repeating: "</li></ul>", count: n)
        let md = try NotesText.htmlToMarkdown(html)
        #expect(md.hasSuffix("x"))
    }

    /// A control: the corpus must actually contain the shapes this test claims to cover. Without
    /// it, a generator that emitted an empty (or truncated) list would pass vacuously.
    @Test("corpus reach control")
    func corpusCoversTheShapes() {
        // Every corpus row must be accounted for by exactly one of the two lists. A row cannot be
        // dropped from `exact` to make this suite green without also being justified in
        // `divergent`, and the total is pinned so shrinking the corpus is a visible change.
        #expect(Self.exact.count + Self.divergent.count == 84,
                "corpus size changed: \(Self.exact.count) exact + \(Self.divergent.count) divergent")
        #expect(Set(Self.exact.map(\.name)).isDisjoint(with: Set(Self.divergent.map(\.name))))
        let names = Set(Self.exact.map(\.name))
        // `sib_*` is the family the v2 parser exists for: Apple nests a sublist as a SIBLING of
        // the `<li>`, not a child, and 62 of 133 real notes use that shape. If these ever fall out
        // of the corpus the central claim of this change goes untested.
        for required in ["ol_simple", "ul_simple", "ol_start5", "ol_startnan", "ol_in_ol",
                         "ol_deep_under10", "ol_empty_item", "ol_four_deep", "ol_nested_then_text",
                         "sib_only", "sib_first", "sib_trailing", "sib_ul_apple",
                         "sib_ol_numbering", "sib_two_deep", "sib_two_sublists",
                         // attribute-scanning rows: a `start`-suffixed attribute is not `start`,
                         // and `>` inside a quoted value does not end the tag. 7 of these 8 fail
                         // against the pre-fix scanner, which is what makes them worth keeping.
                         "attr_data_start", "attr_decoy_then_real", "attr_start_in_value",
                         "attr_gt_in_value", "attr_gt_then_start", "attr_gt_single_quoted",
                         // ECMA-262 StringToNumber boundary: the forms JS accepts (hex/octal/
                         // binary/Infinity/exponent/whitespace-as-zero) AND the ones it rejects
                         // (signed hex, lowercase infinity, trailing garbage).
                         "start_hex", "start_bin", "start_oct", "start_infinity",
                         "start_neg_infinity", "start_exp", "start_ws_only",
                         "start_neg_hex", "start_lower_infinity", "start_trailing_garbage",
                         "start_hex_big", "start_hex_baddigit", "start_bin_baddigit"] {
            #expect(names.contains(required), "corpus lost coverage of \(required)")
        }
        // The goldens must not be trivially empty. Exactly THREE legitimately are, and they are
        // named rather than counted: a list whose only item is blank (turndown's blankRule replaces
        // the item, then the wrapper's newlines are trimmed away), and the two genuinely empty
        // lists. Naming them keeps the control tight — a generator that started emitting "" for
        // everything would still fail here. This assertion has already caught one wrong assumption
        // of mine (that no golden could be empty at all), so it stays exact-set, not a count.
        let empties = Set(Self.exact.filter { $0.markdown.isEmpty }.map(\.name))
        #expect(empties == ["ul_only_blanks", "ul_empty_list", "ol_empty_list"],
                "unexpected empty goldens: \(empties.sorted())")
        // ordered markers must actually appear, or the numbering claim is untested
        #expect(Self.exact.contains { $0.markdown.contains("1.  ") })
        #expect(Self.exact.contains { $0.markdown.contains("10.  ") })
        #expect(Self.exact.contains { $0.markdown.contains("NaN.  ") })
    }

    // MARK: known divergences, deliberately NOT fixed here

    /// Each divergent row is asserted from BOTH sides: the port still produces exactly what it
    /// produced when the gap was recorded, AND it still differs from the oracle. The second
    /// assertion is the one that matters - when NOTES-L1 (or img/table rendering) lands, this goes
    /// red and forces the row to be moved into `exact` deliberately, instead of the divergence
    /// quietly persisting in a file whose name claims parity.
    @Test("known divergences still diverge, and still diverge in exactly the recorded way")
    func divergencesArePinnedFromBothSides() throws {
        for row in Self.divergent {
            let got = try NotesText.htmlToMarkdown(row.html)
            #expect(got == row.port,
                    "\(row.name): port behaviour CHANGED (now \(got.debugDescription), recorded \(row.port.debugDescription)) - if the underlying gap was closed, move this row into `exact`")
            #expect(got != row.oracle,
                    "\(row.name): port now MATCHES the oracle - the gap is closed; move this row into `exact` and drop it from `divergent`")
        }
    }
}
