import Foundation
import Testing
@testable import NotesKit

/// `update-note` response-title resolution against apple-notes-mcp 2.6.12 (NOTES-M6).
///
/// GOLDEN VALUES generated by running the ORACLE'S OWN `resolveUpdateResponseTitle` /
/// `firstVisibleHtmlLine` / `decodeHtmlEntities` under node and emitting this table
/// mechanically — not hand-transcribed, so a transcription slip cannot silently define the
/// expectations.
///
/// The behaviour the port was missing: in HTML format the oracle DERIVES the response title from
/// the new body and ignores `newTitle` entirely (see the "Ignored" row). The port returned
/// `newTitle ?? current` unconditionally, so an html update reported a title Notes would not show.
@Suite("update-note response title parity")
struct UpdateTitleParityTests {

    /// (currentTitle, newTitle, html, newContent, oracle result)
    static let golden: [(String, String?, Bool, String, String)] = [
        ("Cur", nil, true, "<div>Hello</div><div>Body</div>", "Hello"),
        ("Cur", "Ignored", true, "<div>Hello</div><div>Body</div>", "Hello"),
        ("Cur", nil, true, "<div></div><div>Second is first visible</div>", "Second is first visible"),
        ("Cur", nil, true, "<div>   </div><div>Trimmed</div>", "Trimmed"),
        ("Cur", nil, true, "<b>Bold</b> then text", "Bold then text"),
        ("Cur", nil, true, "<div>a<br>b</div>", "a"),
        ("Cur", nil, true, "<script>var x = 1;</script><div>After script</div>", "After script"),
        ("Cur", nil, true, "<style>.a{}</style><div>After style</div>", "After style"),
        ("Cur", nil, true, "<div>&amp;lt; stays escaped once</div>", "&lt; stays escaped once"),
        ("Cur", nil, true, "<div>&nbsp;&nbsp;spaced</div>", "spaced"),
        ("Cur", nil, true, "<div>&#72;&#101;llo</div>", "Hello"),
        ("Cur", nil, true, "<div>&#x48;ex</div>", "Hex"),
        ("Cur", nil, true, "<div>&lt;notatag&gt;</div>", "<notatag>"),
        ("Cur", nil, true, "<div>&nbsp no semicolon</div>", "no semicolon"),
        ("Cur", nil, true, "<div>&#xD800; surrogate rejected</div>", "&#xD800; surrogate rejected"),
        ("Cur", nil, true, "<div>&#1114112; out of range</div>", "&#1114112; out of range"),
        ("Cur", nil, true, "   ", "Cur"),
        ("Cur", nil, true, "", "Cur"),
        ("Cur", nil, true, "<div>multi   internal    spaces</div>", "multi internal spaces"),
        ("Cur", nil, true, "<h1>Heading</h1><p>Para</p>", "Heading"),
        ("Cur", nil, true, "<li>Item one</li><li>Item two</li>", "Item one"),
        ("Cur", "New", false, "whatever", "New"),
        ("Cur", "", false, "whatever", "Cur"),
        ("Cur", nil, false, "whatever", "Cur"),
        ("Cur", nil, true, "<div>line1\u{2028}line2</div>", "line1"),
        ("Cur", nil, true, "<div><span><em>nested</em></span></div>", "nested"),
        ("Cur", nil, true, "<script>var x = 1;\nvar y = 2;</script><div>After script</div>", "After script"),
        ("Cur", nil, true, "<style>.a{\n color: red;\n}</style><div>After style</div>", "After style"),
        ("Cur", nil, true, "<scr<script>X</script>ipt>Body", "Cur"),
        ("Cur", nil, true, "<sty<style>X</style>le>Body", "Cur"),
        ("Cur", nil, true, "<script\u{E0}>alert(1)</script>Visible", "Visible"),
        ("Cur", nil, true, "<div>&#xFEFF;</div><div>Real</div>", "Real"),
        ("Cur", nil, true, "<div>a&#xFEFF;b</div>", "a b"),
        ("Cur", nil, true, "<div>&#x85;</div><div>Real</div>", "\u{85}"),
        ("Cur", nil, true, "<div>&nbsp\u{212A}elvin</div>", "\u{212A}elvin"),
        ("Cur", nil, true, "<div>&lt\u{17F}tuff</div>", "<\u{17F}tuff"),
        ("Cur", nil, true, "<div><scr<b>ipt>alert(1)</scr</b>ipt>visible</div>", "ipt>alert(1)ipt>visible"),
        ("Cur", nil, true, "<div><scri<x>pt>y</scri</x>pt>Shown</div>", "pt>ypt>Shown"),
        ("Cur", nil, true, "<div>&#xD83D;&#xDE00; lone surrogates</div>", "&#xD83D;&#xDE00; lone surrogates"),
        ("Cur", nil, true, "<div>&#x1F600; astral ok</div>", "\u{1F600} astral ok"),
        ("Cur", nil, true, "<div>&#xDFFF;edge</div>", "&#xDFFF;edge"),
        ("Cur", nil, true, "<div>&#55296;dec surrogate</div>", "&#55296;dec surrogate"),
        // Splice shapes: pass 1 removes an inner block whose REMOVAL joins the surrounding
        // fragments into a NEW script/style tag. These are what make the fixed-point loop
        // load-bearing — single-pass leaks the hidden body into the title.
        ("Cur", nil, true, "<scr<script>X</script>ipt>SECRET</script>", "Cur"),
        ("Cur", nil, true, "<sty<style>X</style>le>SECRET</style>", "Cur"),
        ("Cur", nil, true, "<scr<script>a</script>ipt src=z>Leaked</script>", "Cur"),
        ("Cur", nil, true, "Safe<scr<script>q</script>ipt>Leaked</script>", "Safe"),
        ("Cur", nil, true, "<<script>x</script>script>a", "Cur"),
        // CRLF: JS splits on RUNS of [\r\n  ]; Swift splits per character and yields
        // extra empties. Equivalent only because the search is for the FIRST NON-EMPTY line.
        ("Cur", nil, true, "<div>\u{0d}\n</div><div>after crlf</div>", "after crlf"),
        ("Cur", nil, true, "<div>a\u{0d}\n\u{0d}\nb</div>", "a"),
        // Multi-line script/style: JS `$` is end-of-INPUT (no `m` flag). Under ICU
        // `.anchorsMatchLines` the `|$` alternation would fire at the first line end and leak the
        // block's own source as the title.
        ("Cur", nil, true, "<style type=\"text/css\">\nbody { margin: 0 }\n</style><div>Real Title</div>", "Real Title"),
        ("Cur", nil, true, "<script>\nalert(1)</script><div>Body</div>", "Body"),
        ("Cur", nil, true, "<script>hidden\nVisible", "Cur"),
        // The close tag is LITERALLY `</name>` — the oracle's `</\1>` allows no attributes and no
        // whitespace. Without these, dropping the "`>` must follow the name" check survives all
        // 1,417 corpus rows AND all 57 rows here, while leaking script bodies into the title
        // (`<script>x</script foo>y` would report "foo>y"). Review found the mutant alive.
        ("Cur", nil, true, "<script>x</script foo>y", "Cur"),
        ("Cur", nil, true, "<script>secret</script\t>VISIBLE", "Cur"),
        ("Cur", nil, true, "<script>a</script >b", "Cur"),
        ("Cur", nil, true, "<style>a</style >b", "Cur"),
        ("Cur", nil, true, "<script>a</scriptx>b", "Cur"),
    ]

    @Test("every row matches the oracle")
    func matchesOracle() {
        for (current, newTitle, html, newContent, expected) in Self.golden {
            let got = NotesText.resolveUpdateResponseTitle(current: current, newTitle: newTitle,
                                                           html: html, newContent: newContent)
            #expect(got == expected,
                    "resolve(current: \(current), newTitle: \(newTitle ?? "nil"), html: \(html), content: \(newContent)) = \(got), oracle says \(expected)")
        }
        #expect(Self.golden.count >= 57, "control: the table is populated")
    }

    @Test("html format ignores newTitle; plaintext honours it")
    func formatDecidesWhoWins() {
        // The single most load-bearing difference, stated on its own so a future reader sees it
        // without decoding the table.
        #expect(NotesText.resolveUpdateResponseTitle(
            current: "Cur", newTitle: "Explicit", html: true,
            newContent: "<div>Derived</div>") == "Derived")
        #expect(NotesText.resolveUpdateResponseTitle(
            current: "Cur", newTitle: "Explicit", html: false, newContent: "x") == "Explicit")
    }

    /// ONE piece of this port is unreachable by construction. An earlier version of this comment
    /// claimed TWO, and review refuted the second with a counterexample — recorded here because
    /// the way the claim failed is more instructive than the claim.
    ///
    /// 1. UNREACHABLE, and independently confirmed: the TAG strip loop. `<[^>]*>` matches from a
    ///    `<` to the FIRST following `>`, so deleting that span cannot create a new tag — any `<`
    ///    still present already had its `>` beyond the deleted span. A single global pass is
    ///    already a fixed point. The loop is kept because the oracle has it.
    ///
    /// 2. NOT unreachable — the SCRIPT/STYLE strip loop, which I wrongly lumped in with the above.
    ///    Its `[\s\S]*?(?:</\1>|$)` deletes a span that can cross many `>`, so it CAN splice a new
    ///    tag together: `<scr<script>X</script>ipt>Body` removes `<script>X</script>` on pass 1,
    ///    joining `<scr` + `ipt>Body` into `<script>Body`, which pass 2 then eats via the `$`
    ///    alternation. Looped yields nil (fall back to the current title); single-pass yields
    ///    "Body". Both engines agree. Pinned by the golden rows below; making the loop single-pass
    ///    turns 7 rows red (5 when this comment was written, before the review rows landed).
    ///
    ///    Why my own 200,000-input fuzz missed it: the alphabet emitted `script`/`style` only as
    ///    WHOLE tokens, never the fragments `scr`/`ipt`, so it could not reconstruct a tag by
    ///    deletion. The fuzz was blind by construction, and a clean zero from it proved nothing.
    ///    A negative result is only as strong as the generator's reach.
    ///
    /// 3. Still redundant, correctly: the explicit surrogate/range rejection in the decoder is
    ///    load-bearing in JS (`String.fromCodePoint` builds lone surrogates) but inert in Swift,
    ///    where `Unicode.Scalar(cp)` already returns nil for U+D800–U+DFFF and above U+10FFFF.
    ///    Removing it leaves every row green. Kept to mirror the oracle.
    ///
    @Test("a body that renders nothing falls back to the current title")
    func emptyRenderFallsBack() {
        for empty in ["", "   ", "<div></div>", "<script>x</script>", "<br>"] {
            #expect(NotesText.resolveUpdateResponseTitle(
                current: "Keep", newTitle: nil, html: true, newContent: empty) == "Keep",
                    "\(empty) renders nothing, so the current title must survive")
        }
    }
}
