#!/usr/bin/env python3
"""Validate reproducible docs dependencies and Dependabot policy with stdlib only."""

from __future__ import annotations

import argparse
import os
from pathlib import Path
import re
import stat
import sys
from typing import NamedTuple, Optional


PACKAGE_NAME = r"[A-Za-z0-9][A-Za-z0-9._-]*"
VERSION = r"[A-Za-z0-9][A-Za-z0-9.+_-]*"
INPUT_PIN_PATTERN = re.compile(rf"(?P<name>{PACKAGE_NAME})==(?P<version>{VERSION})\Z")
# Only a space or a tab may sit before a continuation backslash. pip splits a requirement line's
# tokens on a space, so whatever else sits there stays inside the requirement string, and the
# requirement grammar admits only space and tab as whitespace. Both patterns match the line as
# written, after any indentation, never a stripped copy: pip continues a line only when its last
# character is the backslash (`line.endswith("\\")`), so a space or a tab after the backslash
# ends the continuation and leaves the backslash in pip's requirement or options. Trailing
# spaces and tabs are admitted only where no backslash precedes them.
LOCK_START_PATTERN = re.compile(
    rf"(?P<name>{PACKAGE_NAME})==(?P<version>{VERSION})(?:[ \t]*\\|[ \t]*)\Z"
)
HASH_PATTERN = re.compile(r"--hash=sha256:([0-9a-f]{64})(?:[ \t]*\\|[ \t]*)\Z")
MAX_REQUIREMENTS_INPUT_BYTES = 64 * 1024
MAX_LOCK_BYTES = 2 * 1024 * 1024
MAX_DEPENDABOT_BYTES = 256 * 1024
# Run from inside docs/, the directory Dependabot compiles in, so the lock's `# via` comment
# matches Dependabot's.
LOCK_COMPILE_COMMAND = (
    "uv pip compile requirements.in --python-version 3.12 "
    "--python-platform x86_64-unknown-linux-gnu --generate-hashes "
    "--output-file requirements.txt"
)
LOCK_HEADER = (
    "# This file was autogenerated by uv via the following command:\n"
    f"#    {LOCK_COMPILE_COMMAND}"
)


class LockedRequirement(NamedTuple):
    version: str
    hashes: tuple[str, ...]


def _canonical_package(name: str) -> str:
    return re.sub(r"[-_.]+", "-", name).lower()


def _refused_character(character: str) -> bool:
    """Whitespace other than space and tab, a character outside YAML's printable set, U+FEFF,
    or a bidirectional control (U+061C, U+200E, U+200F, U+202A-U+202E, U+2066-U+2069).

    COUPLING: `workflow_policy.refused_character(character, " \t")` is the same rule; keep the
    two in step (`Tests/automation/test_dependency_policy.py` checks they agree)."""
    if character.isspace():
        return character not in " \t"
    code = ord(character)
    return (code < 0x20 or 0x7F <= code <= 0x9F or 0xD800 <= code <= 0xDFFF or 0x202A <= code <= 0x202E
            or 0x2066 <= code <= 0x2069 or code in (0x061C, 0x200E, 0x200F, 0xFEFF, 0xFFFE, 0xFFFF))


def _refuse_characters(text: str) -> None:
    """Raise, naming only the line number and code point, at the first refused character.

    CONTROL PLANE — the readers below use `splitlines()`, `strip()` and `isspace()`, which
    also accept the no-break space, the other Unicode spaces and several line separators. pip
    splits a requirement line's tokens on a space and continues a line only at a trailing
    backslash, so a no-break space this reader skipped as indentation, or before the
    backslash, stays inside pip's requirement string. Such a character is refused before
    parsing, never interpreted; a carriage return is refused as well, since the tracked files
    use line feeds only. That makes this reader stricter than pip, whose own line splitting is
    Python's `splitlines()`: a lock or input pip would accept can be refused here, never the
    reverse."""
    for number, line in enumerate(text.split("\n"), start=1):
        for character in line:
            if _refused_character(character):
                raise ValueError(
                    "line {}: character U+{:04X} is refused (only space, tab and line feed may be "
                    "whitespace; no control character, byte-order mark, bidirectional control, "
                    "surrogate, U+FFFE or U+FFFF)".format(number, ord(character))
                )


def parse_input_pins(text: str) -> dict[str, str]:
    _refuse_characters(text)
    pins: dict[str, str] = {}
    for raw_line in text.splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#"):
            continue
        match = INPUT_PIN_PATTERN.fullmatch(line)
        if match is None:
            raise ValueError("every top-level docs requirement must be exactly pinned")
        name = _canonical_package(match.group("name"))
        if name in pins:
            raise ValueError("duplicate top-level docs requirement")
        pins[name] = match.group("version")
    if not pins:
        raise ValueError("docs requirements input is empty")
    return pins


def parse_hash_lock(text: str) -> dict[str, LockedRequirement]:
    _refuse_characters(text)
    requirements: dict[str, LockedRequirement] = {}
    current_name: Optional[str] = None
    current_version: Optional[str] = None
    current_hashes: list[str] = []

    def finish() -> None:
        nonlocal current_name, current_version, current_hashes
        if current_name is None or current_version is None:
            return
        if not current_hashes:
            raise ValueError("every locked docs requirement must include a sha256 hash")
        if current_name in requirements:
            raise ValueError("duplicate locked docs requirement")
        requirements[current_name] = LockedRequirement(
            current_version,
            tuple(current_hashes),
        )
        current_name = None
        current_version = None
        current_hashes = []

    # Whether the previous line ended with a continuation backslash. pip joins lines only there
    # (`join_lines`), not by indentation: a blank or comment line ends a continuation, a hash
    # line that continues nothing is dropped with a warning ("has --hash but no requirement"),
    # and a requirement line after a continued line is glued into the previous requirement's
    # options. Each of those is refused here, so the hashes read below are the ones pip attaches.
    continued = False
    # After the refusal the only line break left is a line feed, so these line numbers match the
    # refusal's.
    for number, raw_line in enumerate(text.splitlines(), start=1):
        stripped = raw_line.strip()
        if not stripped or stripped.startswith("#"):
            continued = False
            continue
        if stripped.endswith("\\") and not raw_line.endswith("\\"):
            raise ValueError(
                "line {}: a continuation backslash must be the last character on its "
                "line".format(number)
            )
        indentation = raw_line[: len(raw_line) - len(raw_line.lstrip(" \t"))]
        if indentation:
            # pip joins a continued line onto the requirement and splits the tokens on a space,
            # so a tab directly before the first hash option glues onto `--hash` and the option
            # stays inside the requirement string, which pip refuses. uv indents with spaces; a
            # tab anywhere in a continuation's indentation is refused, which is stricter than
            # pip wherever a space has already split the option off (a later hash line, or a
            # tab followed by spaces).
            if indentation.strip(" "):
                raise ValueError(
                    "line {}: locked docs requirement continuation must be indented with spaces "
                    "only".format(number)
                )
            hash_match = HASH_PATTERN.fullmatch(raw_line[len(indentation):])
            if hash_match is None or current_name is None:
                raise ValueError("locked docs requirement continuation is malformed")
            if not continued:
                raise ValueError(
                    "line {}: a hash line must follow a line that ends with a continuation "
                    "backslash".format(number)
                )
            current_hashes.append(hash_match.group(1))
            continued = raw_line.endswith("\\")
            continue
        if continued:
            raise ValueError(
                "line {}: a requirement line must not follow a line that ends with a "
                "continuation backslash".format(number)
            )
        finish()
        match = LOCK_START_PATTERN.fullmatch(raw_line)
        if match is None:
            raise ValueError("every locked docs requirement must be exactly pinned")
        current_name = _canonical_package(match.group("name"))
        current_version = match.group("version")
        continued = raw_line.endswith("\\")
    finish()
    if not requirements:
        raise ValueError("docs requirements lock is empty")
    return requirements


def _read_regular_utf8(path: Path, maximum_bytes: int) -> str:
    flags = (
        os.O_RDONLY
        | getattr(os, "O_CLOEXEC", 0)
        | getattr(os, "O_NOFOLLOW", 0)
        | getattr(os, "O_NONBLOCK", 0)
    )
    descriptor = os.open(str(path), flags)
    try:
        metadata = os.fstat(descriptor)
        if not stat.S_ISREG(metadata.st_mode):
            raise ValueError("file must be regular")
        if metadata.st_size > maximum_bytes:
            raise ValueError("file exceeds the size limit")
        with os.fdopen(descriptor, "rb", closefd=False) as handle:
            data = handle.read(maximum_bytes + 1)
        if len(data) > maximum_bytes:
            raise ValueError("file exceeds the size limit")
        return data.decode("utf-8")
    finally:
        os.close(descriptor)


def _regular_non_symlink(path: Path) -> bool:
    try:
        return stat.S_ISREG(path.lstat().st_mode)
    except OSError:
        return False


def validate_docs_dependencies(root: Path) -> list[str]:
    input_path = root / "docs" / "requirements.in"
    lock_path = root / "docs" / "requirements.txt"
    errors: list[str] = []
    try:
        input_text = _read_regular_utf8(input_path, MAX_REQUIREMENTS_INPUT_BYTES)
    except FileNotFoundError:
        errors.append("docs/requirements.in is missing")
        input_text = ""
    except (OSError, UnicodeError, ValueError):
        errors.append("docs/requirements.in must be a regular bounded UTF-8 file")
        input_text = ""
    try:
        lock_text = _read_regular_utf8(lock_path, MAX_LOCK_BYTES)
    except FileNotFoundError:
        errors.append("docs/requirements.txt is missing")
        lock_text = ""
    except (OSError, UnicodeError, ValueError):
        errors.append("docs/requirements.txt must be a regular bounded UTF-8 file")
        lock_text = ""
    try:
        pins = parse_input_pins(input_text) if input_text else {}
    except (OSError, UnicodeError, ValueError) as error:
        errors.append(f"docs/requirements.in: {error}")
        pins = {}
    locked: Optional[dict[str, LockedRequirement]]
    try:
        locked = parse_hash_lock(lock_text) if lock_text else {}
    except (OSError, UnicodeError, ValueError) as error:
        errors.append(f"docs/requirements.txt: {error}")
        locked = None
    if lock_text and not lock_text.startswith(LOCK_HEADER + "\n"):
        errors.append("docs requirements lock must record the Python 3.12 Linux hash contract")
    # A lock that failed to parse is not compared with the pins: against no lock, every pin
    # would add a stale-lock error that the lock's own fix may not need.
    if locked is not None:
        for name, version in pins.items():
            requirement = locked.get(name)
            if requirement is None or requirement.version != version:
                errors.append("docs requirements top-level lock is stale")
    return errors


DEPENDABOT_UPDATES = (
    (
        "github-actions",
        "/",
        "monday",
        "04:17",
        "build(actions)",
        "dependencies-actions",
    ),
    (
        "pip",
        "/docs",
        "tuesday",
        "04:29",
        "build(docs)",
        "dependencies-docs",
    ),
    (
        "swift",
        "/",
        "wednesday",
        "04:41",
        "build(swift)",
        "dependencies-swift",
    ),
)


def render_dependabot_policy() -> str:
    lines = ["version: 2", "updates:"]
    for index, (ecosystem, directory, day, time, prefix, label) in enumerate(
        DEPENDABOT_UPDATES
    ):
        if index:
            lines.append("")
        lines.extend(
            [
                f'  - package-ecosystem: "{ecosystem}"',
                f'    directory: "{directory}"',
                '    target-branch: "main"',
                "    schedule:",
                '      interval: "weekly"',
                f'      day: "{day}"',
                f'      time: "{time}"',
                '      timezone: "America/New_York"',
                "    open-pull-requests-limit: 5",
                "    labels:",
                '      - "dependencies"',
                f'      - "{label}"',
                "    groups:",
                "      minor-and-patch:",
                "        patterns:",
                '          - "*"',
                "        update-types:",
                '          - "minor"',
                '          - "patch"',
                "    commit-message:",
                f'      prefix: "{prefix}"',
            ]
        )
    return "\n".join(lines) + "\n"


def validate_dependabot(root: Path) -> list[str]:
    path = root / ".github" / "dependabot.yml"
    try:
        document = _read_regular_utf8(path, MAX_DEPENDABOT_BYTES)
    except FileNotFoundError:
        return [".github/dependabot.yml is missing"]
    except (OSError, UnicodeError, ValueError):
        return [".github/dependabot.yml: configuration must be a regular bounded UTF-8 file"]
    errors: list[str] = []
    if document != render_dependabot_policy():
        errors.append(".github/dependabot.yml: policy is not canonical")
    if not all(
        _regular_non_symlink(root / name)
        for name in ("Package.swift", "Package.resolved")
    ):
        errors.append("Swift root manifest files are missing")
    if not all(
        _regular_non_symlink(root / "docs" / name)
        for name in ("requirements.in", "requirements.txt")
    ):
        errors.append("docs dependency lock files are missing")
    return errors


def validate_repository(root: Path) -> list[str]:
    return validate_docs_dependencies(root) + validate_dependabot(root)


def main(argv: Optional[list[str]] = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", type=Path, default=Path(__file__).resolve().parents[2])
    arguments = parser.parse_args(argv)
    errors = validate_repository(arguments.root.resolve())
    for error in errors:
        print(error, file=sys.stderr)
    return 1 if errors else 0


if __name__ == "__main__":
    raise SystemExit(main())
