#!/usr/bin/env python3
"""Validate reproducible docs dependencies and Dependabot policy with stdlib only."""

from __future__ import annotations

import argparse
import os
from pathlib import Path
import re
import stat
import sys
from typing import NamedTuple, Optional


PACKAGE_NAME = r"[A-Za-z0-9][A-Za-z0-9._-]*"
VERSION = r"[A-Za-z0-9][A-Za-z0-9.+_-]*"
INPUT_PIN_PATTERN = re.compile(rf"(?P<name>{PACKAGE_NAME})==(?P<version>{VERSION})\Z")
LOCK_START_PATTERN = re.compile(rf"(?P<name>{PACKAGE_NAME})==(?P<version>{VERSION})(?:\s*\\)?\Z")
HASH_PATTERN = re.compile(r"--hash=sha256:([0-9a-f]{64})(?:\s*\\)?\Z")
MAX_REQUIREMENTS_INPUT_BYTES = 64 * 1024
MAX_LOCK_BYTES = 2 * 1024 * 1024
MAX_DEPENDABOT_BYTES = 256 * 1024
LOCK_COMPILE_COMMAND = (
    "uv pip compile docs/requirements.in --python-version 3.12 "
    "--python-platform x86_64-unknown-linux-gnu --generate-hashes "
    "--output-file docs/requirements.txt"
)
LOCK_HEADER = (
    "# This file was autogenerated by uv via the following command:\n"
    f"#    {LOCK_COMPILE_COMMAND}"
)


class LockedRequirement(NamedTuple):
    version: str
    hashes: tuple[str, ...]


def _canonical_package(name: str) -> str:
    return re.sub(r"[-_.]+", "-", name).lower()


def parse_input_pins(text: str) -> dict[str, str]:
    pins: dict[str, str] = {}
    for raw_line in text.splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#"):
            continue
        match = INPUT_PIN_PATTERN.fullmatch(line)
        if match is None:
            raise ValueError("every top-level docs requirement must be exactly pinned")
        name = _canonical_package(match.group("name"))
        if name in pins:
            raise ValueError("duplicate top-level docs requirement")
        pins[name] = match.group("version")
    if not pins:
        raise ValueError("docs requirements input is empty")
    return pins


def parse_hash_lock(text: str) -> dict[str, LockedRequirement]:
    requirements: dict[str, LockedRequirement] = {}
    current_name: Optional[str] = None
    current_version: Optional[str] = None
    current_hashes: list[str] = []

    def finish() -> None:
        nonlocal current_name, current_version, current_hashes
        if current_name is None or current_version is None:
            return
        if not current_hashes:
            raise ValueError("every locked docs requirement must include a sha256 hash")
        if current_name in requirements:
            raise ValueError("duplicate locked docs requirement")
        requirements[current_name] = LockedRequirement(
            current_version,
            tuple(current_hashes),
        )
        current_name = None
        current_version = None
        current_hashes = []

    for raw_line in text.splitlines():
        stripped = raw_line.strip()
        if not stripped or stripped.startswith("#"):
            continue
        if raw_line[:1].isspace():
            hash_match = HASH_PATTERN.fullmatch(stripped)
            if hash_match is None or current_name is None:
                raise ValueError("locked docs requirement continuation is malformed")
            current_hashes.append(hash_match.group(1))
            continue
        finish()
        match = LOCK_START_PATTERN.fullmatch(stripped)
        if match is None:
            raise ValueError("every locked docs requirement must be exactly pinned")
        current_name = _canonical_package(match.group("name"))
        current_version = match.group("version")
    finish()
    if not requirements:
        raise ValueError("docs requirements lock is empty")
    return requirements


def _read_regular_utf8(path: Path, maximum_bytes: int) -> str:
    flags = (
        os.O_RDONLY
        | getattr(os, "O_CLOEXEC", 0)
        | getattr(os, "O_NOFOLLOW", 0)
        | getattr(os, "O_NONBLOCK", 0)
    )
    descriptor = os.open(str(path), flags)
    try:
        metadata = os.fstat(descriptor)
        if not stat.S_ISREG(metadata.st_mode):
            raise ValueError("file must be regular")
        if metadata.st_size > maximum_bytes:
            raise ValueError("file exceeds the size limit")
        with os.fdopen(descriptor, "rb", closefd=False) as handle:
            data = handle.read(maximum_bytes + 1)
        if len(data) > maximum_bytes:
            raise ValueError("file exceeds the size limit")
        return data.decode("utf-8")
    finally:
        os.close(descriptor)


def _regular_non_symlink(path: Path) -> bool:
    try:
        return stat.S_ISREG(path.lstat().st_mode)
    except OSError:
        return False


def validate_docs_dependencies(root: Path) -> list[str]:
    input_path = root / "docs" / "requirements.in"
    lock_path = root / "docs" / "requirements.txt"
    errors: list[str] = []
    try:
        input_text = _read_regular_utf8(input_path, MAX_REQUIREMENTS_INPUT_BYTES)
    except FileNotFoundError:
        errors.append("docs/requirements.in is missing")
        input_text = ""
    except (OSError, UnicodeError, ValueError):
        errors.append("docs/requirements.in must be a regular bounded UTF-8 file")
        input_text = ""
    try:
        lock_text = _read_regular_utf8(lock_path, MAX_LOCK_BYTES)
    except FileNotFoundError:
        errors.append("docs/requirements.txt is missing")
        lock_text = ""
    except (OSError, UnicodeError, ValueError):
        errors.append("docs/requirements.txt must be a regular bounded UTF-8 file")
        lock_text = ""
    try:
        pins = parse_input_pins(input_text) if input_text else {}
    except (OSError, UnicodeError, ValueError) as error:
        errors.append(f"docs/requirements.in: {error}")
        pins = {}
    try:
        locked = parse_hash_lock(lock_text) if lock_text else {}
    except (OSError, UnicodeError, ValueError) as error:
        errors.append(f"docs/requirements.txt: {error}")
        locked = {}
    if lock_text and not lock_text.startswith(LOCK_HEADER + "\n"):
        errors.append("docs requirements lock must record the Python 3.12 Linux hash contract")
    for name, version in pins.items():
        requirement = locked.get(name)
        if requirement is None or requirement.version != version:
            errors.append("docs requirements top-level lock is stale")
    return errors


DEPENDABOT_UPDATES = (
    (
        "github-actions",
        "/",
        "monday",
        "04:17",
        "build(actions)",
        "dependencies-actions",
    ),
    (
        "pip",
        "/docs",
        "tuesday",
        "04:29",
        "build(docs)",
        "dependencies-docs",
    ),
    (
        "swift",
        "/",
        "wednesday",
        "04:41",
        "build(swift)",
        "dependencies-swift",
    ),
)


def render_dependabot_policy() -> str:
    lines = ["version: 2", "updates:"]
    for index, (ecosystem, directory, day, time, prefix, label) in enumerate(
        DEPENDABOT_UPDATES
    ):
        if index:
            lines.append("")
        lines.extend(
            [
                f'  - package-ecosystem: "{ecosystem}"',
                f'    directory: "{directory}"',
                '    target-branch: "main"',
                "    schedule:",
                '      interval: "weekly"',
                f'      day: "{day}"',
                f'      time: "{time}"',
                '      timezone: "America/New_York"',
                "    open-pull-requests-limit: 5",
                "    labels:",
                '      - "dependencies"',
                f'      - "{label}"',
                "    groups:",
                "      minor-and-patch:",
                "        patterns:",
                '          - "*"',
                "        update-types:",
                '          - "minor"',
                '          - "patch"',
                "    commit-message:",
                f'      prefix: "{prefix}"',
            ]
        )
    return "\n".join(lines) + "\n"


def validate_dependabot(root: Path) -> list[str]:
    path = root / ".github" / "dependabot.yml"
    try:
        document = _read_regular_utf8(path, MAX_DEPENDABOT_BYTES)
    except FileNotFoundError:
        return [".github/dependabot.yml is missing"]
    except (OSError, UnicodeError, ValueError):
        return [".github/dependabot.yml: configuration must be a regular bounded UTF-8 file"]
    errors: list[str] = []
    if document != render_dependabot_policy():
        errors.append(".github/dependabot.yml: policy is not canonical")
    if not all(
        _regular_non_symlink(root / name)
        for name in ("Package.swift", "Package.resolved")
    ):
        errors.append("Swift root manifest files are missing")
    if not all(
        _regular_non_symlink(root / "docs" / name)
        for name in ("requirements.in", "requirements.txt")
    ):
        errors.append("docs dependency lock files are missing")
    return errors


def validate_repository(root: Path) -> list[str]:
    return validate_docs_dependencies(root) + validate_dependabot(root)


def main(argv: Optional[list[str]] = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", type=Path, default=Path(__file__).resolve().parents[2])
    arguments = parser.parse_args(argv)
    errors = validate_repository(arguments.root.resolve())
    for error in errors:
        print(error, file=sys.stderr)
    return 1 if errors else 0


if __name__ == "__main__":
    raise SystemExit(main())
