import Foundation
import AppleKit

/// A faithful STRING-VALUE subset of Python's `string.Formatter().vformat` — the engine oracle
/// A's template render runs (`templates.py _substitute`). Template vars in this domain are all
/// strings (CLI `--var k=v` + the auto vars), so the subset is: field access chains
/// (`{x[0]}`, `{x.attr}`), conversions (`!s` `!r` `!a`), and the format mini-language as it
/// applies to `str` values (fill/align/width/`.precision`/type `s`, `0`-flag, one level of
/// nested `{ident}` spec fields) — gap37: the old scanner required `}` immediately after the
/// identifier, so a spec-bearing token was copied VERBATIM and never recorded as missing,
/// bypassing the missing_template_variable guard into outbound text.
///
/// Error PARITY: evaluation errors (unknown format code, bad conversion, attribute/index
/// access on a string) reproduce Python's message text and map to oracle A's error class for
/// them — its render catches only MailTemplateError specially, so a ValueError/AttributeError
/// lands in the generic arm as error_type "unknown". Missing variables are RECORDED (the
/// caller's missing_template_variable guard raises), matching `TemplateStore.fill`'s contract.
///
/// Semantics verified against python3 (the corpus in Tests/MailKitTests/fixtures/pyformat/ is
/// GENERATED by executing string.Formatter itself over a synthetic matrix — never reasoned).
enum PyFormat {

    struct EvalError: Error { let message: String }

    /// One parsed `{...}` replacement field.
    struct Field {
        var name: String                    // base identifier
        var accessors: [Accessor] = []      // .attr / [index] chain
        var conversion: Character? = nil    // s | r | a
        var spec: String = ""               // raw spec, may contain one nested {ident} level
    }

    enum Accessor {
        case attribute(String)
        case index(String)                  // raw text between [ ]; Python int-parses it
    }

    // MARK: token parsing

    /// Outcome of parsing one `{`-opened replacement field, mirroring Python's own two stages
    /// (formatter_parser field extraction, then get_field name resolution).
    enum FieldParse {
        case field(Field, after: String.Index)
        /// The ONE deliberate divergence (pinned + disclosed in the port spec): a lone `{`
        /// with no `}` before end-of-string (and no `[` opened) stays literal text, where
        /// Python raises "expected '}' before end of string". Everything brace-committed
        /// either parses or errors with Python's message.
        case literal
        case error(String)
    }

    /// Parse a replacement field starting at the `{` at `start`. Malformed-but-committed
    /// fields ERROR with Python's exact message (measured, not reasoned — review B3: the old
    /// nil-return let `{ recipient_name }`, `{2x}`, `{x!}` … leak verbatim into outbound text
    /// with ok:true, the very defect gap37 was filed to close). A base name that is any other
    /// raw string (spaces included) is a straight dict lookup, so a missing one lands in the
    /// caller's `missing` set exactly like Python's KeyError → missing_template_variable.
    static func parseField(_ text: String, from start: String.Index) -> FieldParse {
        var j = text.index(after: start)
        // Stage 1: extract the raw field_name up to a top-level '!' or ':' or '}', treating
        // '['…']' spans as opaque (Python consumes even '}' inside brackets — measured:
        // `{x[}` is "expected '}' before end of string", not a closed field).
        var rawName = ""
        var sawBracket = false
        var terminator: Character? = nil
        scan: while j < text.endIndex {
            let c = text[j]
            if c == "[" {
                sawBracket = true
                rawName.append(c); j = text.index(after: j)
                while j < text.endIndex, text[j] != "]" { rawName.append(text[j]); j = text.index(after: j) }
                guard j < text.endIndex else { return .error("expected '}' before end of string") }
                rawName.append("]"); j = text.index(after: j)
                continue
            }
            if c == "!" || c == ":" || c == "}" { terminator = c; break scan }
            rawName.append(c); j = text.index(after: j)
        }
        guard let term = terminator else {
            // End of string, field never closed.
            return sawBracket ? .error("expected '}' before end of string") : .literal
        }
        var f = Field(name: "")
        // Conversion.
        if term == "!" {
            j = text.index(after: j)
            guard j < text.endIndex, text[j] != "}" else {
                return .error("unmatched '{' in format spec")   // measured for `{x!}`
            }
            f.conversion = text[j]
            j = text.index(after: j)
            guard j < text.endIndex, text[j] == ":" || text[j] == "}" else {
                return .error("expected ':' after conversion specifier")
            }
        }
        // Spec (after ':'), one nesting level; unclosed nesting or missing field terminator
        // is Python's "unmatched '{' in format spec".
        if j < text.endIndex, text[j] == ":" {
            j = text.index(after: j)
            var depth = 0
            while j < text.endIndex {
                let c = text[j]
                if c == "{" { depth += 1 }
                else if c == "}" {
                    if depth == 0 { break }
                    depth -= 1
                }
                f.spec.append(c)
                j = text.index(after: j)
            }
            guard j < text.endIndex else { return .error("unmatched '{' in format spec") }
        }
        guard j < text.endIndex, text[j] == "}" else {
            return sawBracket ? .error("expected '}' before end of string") : .literal
        }
        let after = text.index(after: j)

        // Stage 2 (get_field): first part = up to the first '.' or '['; empty or all-digits
        // means positional/auto-numbered, which vformat(text, (), vars) resolves against the
        // EMPTY args tuple — measured: "tuple index out of range" (IndexError → oracle A's
        // generic arm, error_type "unknown").
        var base = ""
        var k = rawName.startIndex
        while k < rawName.endIndex, rawName[k] != ".", rawName[k] != "[" {
            base.append(rawName[k]); k = rawName.index(after: k)
        }
        if base.isEmpty || base.allSatisfy({ ("0"..."9").contains($0) }) {
            return .error("tuple index out of range")
        }
        f.name = base
        // Accessor chain over the remainder.
        while k < rawName.endIndex {
            if rawName[k] == "." {
                k = rawName.index(after: k)
                var attr = ""
                while k < rawName.endIndex, rawName[k] != ".", rawName[k] != "[" {
                    attr.append(rawName[k]); k = rawName.index(after: k)
                }
                guard !attr.isEmpty else { return .error("Empty attribute in format string") }
                f.accessors.append(.attribute(attr))
            } else {   // '['
                k = rawName.index(after: k)
                var key = ""
                while k < rawName.endIndex, rawName[k] != "]" { key.append(rawName[k]); k = rawName.index(after: k) }
                // stage 1 guaranteed the ']' exists
                if k < rawName.endIndex { k = rawName.index(after: k) }
                f.accessors.append(.index(key))
            }
        }
        return .field(f, after: after)
    }

    static func isIdentStart(_ c: Character) -> Bool {
        c == "_" || ("a"..."z").contains(c) || ("A"..."Z").contains(c)
    }
    static func isIdentChar(_ c: Character) -> Bool {
        isIdentStart(c) || ("0"..."9").contains(c)
    }

    // MARK: evaluation

    /// Resolve accessors against a string value, reproducing Python's error text.
    static func applyAccessors(_ value: String, _ accessors: [Accessor]) throws -> String {
        var v = value
        for a in accessors {
            switch a {
            case .attribute(let name):
                throw EvalError(message: "'str' object has no attribute '\(name)'")
            case .index(let raw):
                // Python's Formatter int-parses ONLY all-digit keys (`str.isdigit()`), so a
                // negative "[-1]" is a STRING key → TypeError, not a negative index — measured
                // via the golden generator, which caught the first draft accepting negatives.
                // Python's str is a CODE-POINT sequence; Swift's Character view is graphemes.
                // Differential review measured 94/321 divergences from grapheme counting —
                // the repo's most-recurring bug class. unicodeScalars IS the code-point view.
                // Digit detection mirrors Py_UNICODE_TODECIMAL (category Nd — Arabic-Indic ٣
                // int-parses in Python), via Character.wholeNumberValue over decimal digits.
                let digitVals = raw.map { (c: Character) -> Int? in
                    guard let u = c.unicodeScalars.first, c.unicodeScalars.count == 1,
                          u.properties.numericType == .decimal else { return nil }
                    return c.wholeNumberValue
                }
                guard !raw.isEmpty, !digitVals.contains(nil) else {
                    throw EvalError(message: "string indices must be integers, not 'str'")
                }
                let i = digitVals.compactMap { $0 }.reduce(0) { $0 * 10 + $1 }
                let scalars = Array(v.unicodeScalars)
                guard i < scalars.count else {
                    throw EvalError(message: "string index out of range")
                }
                v = String(String.UnicodeScalarView([scalars[i]]))
            }
        }
        return v
    }

    /// Python conversions for str values. `!s` identity; `!r` repr; `!a` ascii().
    static func applyConversion(_ value: String, _ conv: Character?) throws -> String {
        switch conv {
        case nil, "s": return value
        case "r": return pyRepr(value, asciiOnly: false)
        case "a": return pyRepr(value, asciiOnly: true)
        default:
            throw EvalError(message: "Unknown conversion specifier \(conv!)")
        }
    }

    /// Python `repr()` of a str: prefers single quotes; switches to double quotes when the
    /// text contains a single quote but no double quote. Escapes backslash, the quote char,
    /// and control characters (\n \r \t, else \xNN); `asciiOnly` additionally escapes
    /// non-ASCII as \xNN / \uNNNN / \UNNNNNNNN.
    static func pyRepr(_ s: String, asciiOnly: Bool) -> String {
        let hasSingle = s.contains("'"), hasDouble = s.contains("\"")
        let quote: Character = (hasSingle && !hasDouble) ? "\"" : "'"
        var out = String(quote)
        for scalar in s.unicodeScalars {
            switch scalar {
            case "\\": out += "\\\\"
            case Unicode.Scalar(String(quote))!: out += "\\\(quote)"
            case "\n": out += "\\n"
            case "\r": out += "\\r"
            case "\t": out += "\\t"
            default:
                if scalar.value < 0x20 || scalar.value == 0x7F {
                    out += String(format: "\\x%02x", scalar.value)
                } else if asciiOnly && scalar.value > 0x7E {
                    if scalar.value <= 0xFF { out += String(format: "\\x%02x", scalar.value) }
                    else if scalar.value <= 0xFFFF { out += String(format: "\\u%04x", scalar.value) }
                    else { out += String(format: "\\U%08x", scalar.value) }
                } else {
                    out.unicodeScalars.append(scalar)
                }
            }
        }
        out.append(quote)
        return out
    }

    /// Python `format(str_value, spec)` — the str.__format__ mini-language subset:
    /// `[[fill]align][sign][z][#][0][width][,|_][.precision][type]` with the string rules:
    /// sign/'='-align/','/'_'/'#' are errors for str; type must be 's' or absent; '0' flag
    /// means fill '0' (align stays '<' for str); precision truncates.
    static func formatString(_ value: String, spec: String) throws -> String {
        if spec.isEmpty { return value }
        let chars = Array(spec)
        var i = 0
        var fill: Character = " "
        var align: Character? = nil
        var fillSpecified = false
        // [[fill]align] — CPython gates the later '0' flag on fill_char_specified (set ONLY by
        // the two-char form), not on align presence: `{x:<05}` fills with '0' in Python.
        if chars.count >= 2, ["<", ">", "^", "="].contains(chars[1]) {
            fill = chars[0]; align = chars[1]; fillSpecified = true; i = 2
        } else if chars.count >= 1, ["<", ">", "^", "="].contains(chars[0]) {
            align = chars[0]; i = 1
        }
        if i < chars.count, chars[i] == " " {
            throw EvalError(message: "Space not allowed in string format specifier")
        }
        if i < chars.count, ["+", "-"].contains(chars[i]) {
            throw EvalError(message: "Sign not allowed in string format specifier")
        }
        if i < chars.count, chars[i] == "z" {
            throw EvalError(message: "Negative zero coercion (z) not allowed in string format specifier")
        }
        if i < chars.count, chars[i] == "#" {
            throw EvalError(message: "Alternate form (#) not allowed in string format specifier")
        }
        if i < chars.count, chars[i] == "0" {
            if !fillSpecified { fill = "0" }
            i += 1
        }
        var widthStr = ""
        while i < chars.count, chars[i].isNumber { widthStr.append(chars[i]); i += 1 }
        if !widthStr.isEmpty, Int(widthStr) == nil {
            throw EvalError(message: "Too many decimal digits in format string")
        }
        // DoS bound (security review): Python allows any parseable width and MemoryErrors past
        // RAM; an OOM abort here would emit NO JSON envelope at all, breaking the machine
        // contract. Deliberate STRICTER divergence, disclosed in the port spec.
        if let w = Int(widthStr), w > 1_000_000 {
            throw EvalError(message: "Invalid format specifier '\(spec)' for object of type 'str'")
        }
        if i < chars.count, chars[i] == "," || chars[i] == "_" {
            throw EvalError(message: "Cannot specify '\(chars[i])' with 's'.")
        }
        var precision: Int? = nil
        if i < chars.count, chars[i] == "." {
            i += 1
            var p = ""
            while i < chars.count, chars[i].isNumber { p.append(chars[i]); i += 1 }
            guard !p.isEmpty else { throw EvalError(message: "Format specifier missing precision") }
            guard let pv = Int(p) else { throw EvalError(message: "Too many decimal digits in format string") }
            precision = pv
        }
        if i < chars.count {
            let t = chars[i]
            if t == "s", i == chars.count - 1 { i += 1 }
            else if i == chars.count - 1 {
                throw EvalError(message: "Unknown format code '\(t)' for object of type 'str'")
            } else {
                throw EvalError(message: "Invalid format specifier '\(spec)' for object of type 'str'")
            }
        }
        if align == "=" {
            throw EvalError(message: "'=' alignment not allowed in string format specifier")
        }
        var v = value
        // Code-point semantics again (B1): precision truncates CODE POINTS and width counts
        // them — a decomposed é is 2, a ZWJ family emoji is 7, exactly as Python sees them.
        if let precision { v = String(String.UnicodeScalarView(Array(v.unicodeScalars.prefix(precision)))) }
        let width = Int(widthStr) ?? 0
        let n = v.unicodeScalars.count
        if n >= width { return v }
        let pad = width - n
        switch align ?? "<" {
        case ">": return String(repeating: String(fill), count: pad) + v
        case "^":
            let left = pad / 2, right = pad - left
            return String(repeating: String(fill), count: left) + v + String(repeating: String(fill), count: right)
        default:  return v + String(repeating: String(fill), count: pad)
        }
    }

    /// Resolve one level of nested `{ident}` fields inside a spec (Python allows nesting in
    /// the spec; templates here only ever nest simple identifiers). A missing nested var is
    /// recorded in `missing` and the field left verbatim (caller raises on missing).
    static func resolveSpec(_ spec: String, vars: [String: String], missing: inout Set<String>) -> String {
        var out = ""
        var i = spec.startIndex
        while i < spec.endIndex {
            if spec[i] == "{" {
                var j = spec.index(after: i)
                var name = ""
                while j < spec.endIndex, isIdentChar(spec[j]) { name.append(spec[j]); j = spec.index(after: j) }
                if j < spec.endIndex, spec[j] == "}", !name.isEmpty {
                    if let v = vars[name] { out += v } else { missing.insert(name); out += "{\(name)}" }
                    i = spec.index(after: j)
                    continue
                }
            }
            out.append(spec[i])
            i = spec.index(after: i)
        }
        return out
    }
}
