import Testing
import Foundation
import AppleKit
@testable import MailKit

/// gap37 pins: `TemplateStore.fill` must agree with THE ORACLE'S OWN engine —
/// `string.Formatter().vformat` (what apple-mail-mcp templates.py `_substitute` calls) — on
/// every row of a golden corpus GENERATED BY EXECUTING PYTHON (fixtures/pyformat/gen-goldens.py;
/// synthetic inputs only). Output rows compare rendered text; error rows compare Python's own
/// error message, which the CLI maps to oracle A's class for evaluation errors (its render
/// catches only MailTemplateError specially → generic arm → error_type "unknown").
@Suite("PyFormat golden parity (gap37)")
struct PyFormatGoldenTests {

    struct Corpus: Decodable {
        let vars: [String: String]
        let rows: [Row]
    }
    struct Row: Decodable {
        let template: String
        let output: String?
        let error: String?
    }

    static let corpus: Corpus = {
        let url = URL(fileURLWithPath: #filePath)
            .deletingLastPathComponent()
            .appendingPathComponent("fixtures/pyformat/goldens.json")
        return try! JSONDecoder().decode(Corpus.self, from: Data(contentsOf: url))
    }()

    /// Row-count pin: shrinking the corpus (e.g. dropping the error rows) must fail loudly.
    @Test func corpusIsComplete() {
        #expect(Self.corpus.rows.count == 91)
        #expect(Self.corpus.rows.filter { $0.error != nil }.count == 35)
    }

    @Test(arguments: corpus.rows.indices)
    func rowAgreesWithPython(_ idx: Int) throws {
        let row = Self.corpus.rows[idx]
        var missing = Set<String>()
        if let expected = row.output {
            let got = try TemplateStore.fill(row.template, vars: Self.corpus.vars, missing: &missing)
            #expect(got == expected, "template \(row.template)")
            #expect(missing.isEmpty, "template \(row.template) reported missing \(missing)")
        } else if let err = row.error, err.hasPrefix("KeyError:") {
            // Python's KeyError = a missing dict lookup. The CLI's contract for that class is
            // RECORD-in-missing (render then raises missing_template_variable, the oracle's
            // own arm for it) — so fill succeeds, the raw name lands in `missing`, and the
            // field stays verbatim in the (unused) return text.
            let name = String(err.dropFirst("KeyError:".count))
            _ = try TemplateStore.fill(row.template, vars: Self.corpus.vars, missing: &missing)
            #expect(missing.contains(name), "template \(row.template): expected missing '\(name)', got \(missing)")
        } else {
            do {
                _ = try TemplateStore.fill(row.template, vars: Self.corpus.vars, missing: &missing)
                Issue.record("template \(row.template) should have thrown '\(row.error ?? "")'")
            } catch let e as AppleError {
                #expect(e.message == row.error, "template \(row.template)")
            }
        }
    }

    /// The gap itself: a spec-bearing field with an ABSENT base variable must be RECORDED as
    /// missing (the old scanner copied `{zzz:>5}` verbatim and recorded nothing, bypassing the
    /// missing_template_variable guard into outbound text).
    @Test func specBearingMissingVariableIsRecorded() throws {
        var missing = Set<String>()
        let out = try TemplateStore.fill("Hello {zzz:>5}", vars: [:], missing: &missing)
        #expect(missing == ["zzz"])
        #expect(out == "Hello {zzz:>5}")   // verbatim text is unused by callers that raise
    }

    /// A missing NESTED spec field (`{x:{width}}` with width absent) is recorded too.
    @Test func missingNestedSpecFieldIsRecorded() throws {
        var missing = Set<String>()
        _ = try TemplateStore.fill("{x:{width}}", vars: ["x": "hi"], missing: &missing)
        #expect(missing.contains("width"))
    }
}
