import Testing
import Foundation
@testable import MailKit

/// Q11-C pins (gap19/gap20/extra17/extra18/extra19): the pure halves of the rich-draft oracle
/// port. Every expected value below was generated by EXECUTING the oracle's own Python
/// (`_safe_eml_name`, `_build_html_from_text`, `_prepare_rich_bodies` — tools/compose.py),
/// never reasoned about — the goldens live in scratchpad/richdraft-golden.json for regeneration.
@Suite("Rich draft oracle port (Q11-C)")
struct RichDraftTests {

    /// `_safe_eml_name`, python-executed goldens (regex runs → "-", strip "-._" edges,
    /// fallback, 80 cap — pure ASCII output so the cap unit cannot diverge).
    @Test func safeEmlNameMatchesPython() {
        let cases: [(String, String)] = [
            ("", "rich-email-draft"),
            ("  ", "rich-email-draft"),
            ("Q3 report/final", "Q3-report-final"),
            ("...", "rich-email-draft"),
            ("héllo wörld", "h-llo-w-rld"),
            ("__init__.py", "init__.py"),
            ("Re: Budget?", "Re-Budget"),
            ("日本語タイトル", "rich-email-draft"),
            (String(repeating: "x", count: 200), String(repeating: "x", count: 80)),
            ("a/b\\c", "a-b-c"),
            ("dots..mid", "dots..mid"),
            // COLLISION row (disclosed hazard --no-clobber guards): sanitization is lossy,
            // so DIFFERENT subjects map to the SAME filename.
            ("Q3 report/final", "Q3-report-final"),
            ("Q3-report-final", "Q3-report-final"),
        ]
        for (input, want) in cases {
            #expect(RichDraft.safeEmlName(input) == want, "input \(input)")
        }
    }

    /// gap20: the default destination is DETERMINISTIC and subject-named — preview/execute
    /// path identity is the contract the per-run temp UUID broke.
    @Test func defaultPathIsDeterministicAndSubjectNamed() {
        let a = RichDraft.defaultPath(subject: "Weekly Plan")
        let b = RichDraft.defaultPath(subject: "Weekly Plan")
        #expect(a == b)
        #expect(a.lastPathComponent == "Weekly-Plan.eml")
        #expect(a.path.contains("Library/Caches/apple-cli/rich-drafts"))
    }

    /// `_build_html_from_text`, python-executed golden — including the quote entities
    /// (`html.escape` defaults quote=True: `"` → &quot;, `'` → &#x27;) the first draft missed.
    @Test func htmlFromTextMatchesPython() {
        let got = RichDraft.htmlFromText("He said \"hi\" & <waved> 'once'\nnew line")
        let want = "<html><body style=\"font-family: -apple-system, BlinkMacSystemFont, "
            + "'Segoe UI', Arial, sans-serif; line-height: 1.45; color: #111111;\">"
            + "<pre style=\"white-space: pre-wrap; font: inherit; margin: 0;\">"
            + "He said &quot;hi&quot; &amp; &lt;waved&gt; &#x27;once&#x27;\nnew line"
            + "</pre></body></html>"
        #expect(got == want)
    }

    /// `_prepare_rich_bodies` — all three arms, python-executed.
    @Test func prepareBodiesMatchesPython() {
        // Both empty → Draft outline + wrapped HTML + missing ["body"].
        let empty = RichDraft.prepareBodies(subject: "Subj", text: nil, html: nil)
        #expect(empty.plain == "Draft outline\n\n- Add recipients\n- Add the final rich-text content\n- Review before sending")
        #expect(empty.html == RichDraft.htmlFromText(empty.plain))
        #expect(empty.missing == ["body"])
        // HTML-only → plain fallback carries the TRIMMED subject prefix.
        let htmlOnly = RichDraft.prepareBodies(subject: "  Subj  ", text: nil, html: "<b>hi</b>")
        #expect(htmlOnly.plain == "Subj\n\nThis message contains rich HTML content. Open it in Mail for the rendered version.")
        #expect(htmlOnly.html == "<b>hi</b>")
        #expect(htmlOnly.missing.isEmpty)
        // HTML-only, empty subject → no prefix.
        let noSubj = RichDraft.prepareBodies(subject: "", text: nil, html: "<b>hi</b>")
        #expect(noSubj.plain == "This message contains rich HTML content. Open it in Mail for the rendered version.")
        // Newline-only subject: Python str.strip() strips newlines — python-verified — so no
        // prefix here either (review L1: CharacterSet.whitespaces missed \n at both sites).
        let nlSubj = RichDraft.prepareBodies(subject: "\n", text: nil, html: "<b>hi</b>")
        #expect(nlSubj.plain == "This message contains rich HTML content. Open it in Mail for the rendered version.")
        // VT and the C0 separator US are Python-whitespace too (review M1, measured
        // end-to-end vs the executed oracle: `.whitespaces` diverged on VT/FF/FS-US/NEL/LS).
        for ws in ["\u{0B}", "\u{1F}", "\u{0C}"] {
            let wsSubj = RichDraft.prepareBodies(subject: ws + "Subj" + ws, text: nil, html: "<b>hi</b>")
            #expect(wsSubj.plain == "Subj\n\nThis message contains rich HTML content. Open it in Mail for the rendered version.", Comment(rawValue: ws))
        }
        // Text-only → HTML wrapper over the escaped text.
        let textOnly = RichDraft.prepareBodies(subject: "S", text: "plain & <text>", html: nil)
        #expect(textOnly.plain == "plain & <text>")
        #expect(textOnly.html == RichDraft.htmlFromText("plain & <text>"))
        #expect(textOnly.missing.isEmpty)
    }

    /// gap19: the oracle's missing_details assembly (subject → to → body, in that order).
    @Test func missingDetailsMatchesOracleOrder() {
        #expect(RichDraft.missingDetails(subject: " ", to: [], bodyMissing: ["body"]) == ["subject", "to", "body"])
        #expect(RichDraft.missingDetails(subject: "\n", to: [], bodyMissing: []) == ["subject", "to"])
        // Python isspace's full set: VT / FF / the C0 separators / NEL / LINE SEPARATOR all
        // strip to empty (oracle-measured divergence classes, review M1).
        for ws in ["\u{0B}", "\u{0C}", "\u{1C}", "\u{1D}", "\u{1E}", "\u{1F}", "\u{85}", "\u{2028}"] {
            #expect(RichDraft.missingDetails(subject: ws, to: ["a@example.com"], bodyMissing: []) == ["subject"], Comment(rawValue: ws))
        }
        #expect(RichDraft.missingDetails(subject: "S", to: ["a@example.com"], bodyMissing: []).isEmpty)
        #expect(RichDraft.missingDetails(subject: "S", to: [], bodyMissing: []) == ["to"])
    }

    /// extra19: the save script is the oracle's verbatim shape — `every outgoing message whose
    /// subject is`, save item 1, typed sentinels (source pin; execution needs live Mail).
    @Test func saveOpenDraftScriptCarriesTheOracleShape() {
        let src = MailScript.saveOpenDraftScriptSource
        #expect(src.contains("on run argv"))
        #expect(src.contains("every outgoing message whose subject is wantedSubject"))
        #expect(src.contains("save item 1 of matchingMessages"))
        #expect(src.contains("return \"not-found\""))
        #expect(src.contains("return \"saved\""))
    }
}
